package session

import (
	"context"
	"fmt"

	"github.com/7-Dany/store/backend/internal/audit"
	"github.com/7-Dany/store/backend/internal/db"
	authshared "github.com/7-Dany/store/backend/internal/domain/auth/shared"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

// compile-time check that *Store satisfies Storer.
var _ Storer = (*Store)(nil)

// Store provides data access for the session feature.
// It embeds authshared.BaseStore for pool management, transaction handling,
// and type-conversion helpers.
type Store struct {
	authshared.BaseStore
}

// NewStore constructs a Store backed by pool.
func NewStore(pool *pgxpool.Pool) *Store {
	return &Store{BaseStore: authshared.NewBaseStore(pool)}
}

// WithQuerier returns a shallow copy of s bound to q with TxBound=true.
// Used in tests to scope all writes inside a rolled-back transaction.
func (s *Store) WithQuerier(q db.Querier) *Store {
	c := *s
	c.BaseStore = s.BaseStore.WithQuerier(q)
	return &c
}

// ── GetRefreshTokenByJTI ──────────────────────────────────────────────────────

// GetRefreshTokenByJTI fetches a refresh_tokens row by its jti.
// Returns authshared.ErrTokenNotFound when the jti is absent.
func (s *Store) GetRefreshTokenByJTI(ctx context.Context, jti [16]byte) (StoredRefreshToken, error) {
	row, err := s.Queries.GetRefreshTokenByJTI(ctx, s.ToPgtypeUUID(jti))
	if err != nil {
		if s.IsNoRows(err) {
			return StoredRefreshToken{}, authshared.ErrTokenNotFound
		}
		return StoredRefreshToken{}, fmt.Errorf("store.GetRefreshTokenByJTI: query: %w", err)
	}
	return StoredRefreshToken{
		JTI:       row.Jti.Bytes,
		UserID:    row.UserID.Bytes,
		SessionID: row.SessionID.Bytes,
		FamilyID:  row.FamilyID.Bytes,
		ExpiresAt: row.ExpiresAt.Time.UTC(),
		IsRevoked: row.RevokedAt.Valid,
	}, nil
}

// ── GetUserVerifiedAndLocked ─────────────────────────────────────────────────

// GetUserVerifiedAndLocked fetches email_verified, is_locked, and is_active
// for the given user. Returns authshared.ErrUserNotFound on no-rows.
func (s *Store) GetUserVerifiedAndLocked(ctx context.Context, userID [16]byte) (UserStatusResult, error) {
	row, err := s.Queries.GetUserVerifiedAndLocked(ctx, s.ToPgtypeUUID(userID))
	if err != nil {
		if s.IsNoRows(err) {
			return UserStatusResult{}, authshared.ErrUserNotFound
		}
		return UserStatusResult{}, fmt.Errorf("store.GetUserVerifiedAndLocked: query: %w", err)
	}
	return UserStatusResult{
		EmailVerified: row.EmailVerified,
		IsLocked:      row.IsLocked,
		IsActive:      row.IsActive,
	}, nil
}

// ── RotateRefreshTokenTx ──────────────────────────────────────────────────────

// RotateRefreshTokenTx atomically:
//  1. Revokes the current token (revoke_reason = 'rotated').
//  2. Inserts a new child refresh token (same family_id, same session_id,
//     parent_jti = current jti, new jti generated by DB DEFAULT).
//  3. Stamps last_active_at on the session.
//  4. Stamps last_login_at for the user.
//  5. Writes an audit log row event_type = 'token_refreshed'.
//
// Returns the new token's jti and expiry for JWT signing by the handler.
func (s *Store) RotateRefreshTokenTx(ctx context.Context, in RotateTxInput) (RotatedSession, error) {
	h, err := s.BeginOrBind(ctx)
	// Unreachable: BeginOrBind with TxBound=true never calls Pool.Begin
	// and always returns nil error. No test can trigger this branch.
	if err != nil {
		return RotatedSession{}, fmt.Errorf("store.RotateRefreshTokenTx: begin tx: %w", err)
	}

	currentJTIPg := s.ToPgtypeUUID(in.CurrentJTI)
	userPgUUID := s.ToPgtypeUUID(in.UserID)
	sessionPgUUID := s.ToPgtypeUUID(in.SessionID)
	familyPgUUID := s.ToPgtypeUUID(in.FamilyID)

	// 1. Mark current token as rotated (FOR UPDATE semantics: the UPDATE acquires
	//    a row-level lock; if another transaction already rotated this token the
	//    UPDATE affects 0 rows and we abort, preventing double-rotation).
	tag, err := h.Q.RevokeRefreshTokenByJTI(ctx, db.RevokeRefreshTokenByJTIParams{
		Reason: "rotated",
		Jti:    currentJTIPg,
	})
	if err != nil {
		h.Rollback()
		return RotatedSession{}, fmt.Errorf("store.RotateRefreshTokenTx: revoke current token: %w", err)
	}
	if tag.RowsAffected() == 0 {
		// Security: 0 rows affected means the token was already rotated by a
		// concurrent request. Treat as reuse so the caller can revoke the family.
		h.Rollback()
		return RotatedSession{}, authshared.ErrTokenAlreadyConsumed
	}

	// 2. Insert child refresh token with the same family_id and session_id.
	newToken, err := h.Q.CreateRotatedRefreshToken(ctx, db.CreateRotatedRefreshTokenParams{
		UserID:    userPgUUID,
		SessionID: sessionPgUUID,
		FamilyID:  familyPgUUID,
		ParentJti: currentJTIPg,
	})
	if err != nil {
		h.Rollback()
		return RotatedSession{}, fmt.Errorf("store.RotateRefreshTokenTx: create child token: %w", err)
	}

	// 3. Stamp last_active_at on the session so active-device visibility is accurate.
	if err := h.Q.UpdateSessionLastActive(ctx, sessionPgUUID); err != nil {
		h.Rollback()
		return RotatedSession{}, fmt.Errorf("store.RotateRefreshTokenTx: update session last active: %w", err)
	}

	// 4. Stamp last_login_at. Mirrors what LoginTx does.
	if err := h.Q.UpdateLastLoginAt(ctx, userPgUUID); err != nil {
		h.Rollback()
		return RotatedSession{}, fmt.Errorf("store.RotateRefreshTokenTx: update last login at: %w", err)
	}

	// 5. Audit log.
	if err := h.Q.InsertAuditLog(ctx, db.InsertAuditLogParams{
		UserID:    userPgUUID,
		EventType: string(audit.EventTokenRefreshed),
		Provider:  db.AuthProviderEmail,
		IpAddress: s.IPToNullable(in.IPAddress),
		UserAgent: s.ToText(s.TruncateUserAgent(in.UserAgent)),
		Metadata:  []byte("{}"),
	}); err != nil {
		h.Rollback()
		return RotatedSession{}, fmt.Errorf("store.RotateRefreshTokenTx: audit log: %w", err)
	}

	// Unreachable via QuerierProxy: on the TxBound path commitFn is a no-op
	// that always returns nil; on the non-TxBound path commitFn wraps
	// pgx.Tx.Commit which the proxy cannot intercept.
	if err := h.Commit(); err != nil {
		return RotatedSession{}, fmt.Errorf("store.RotateRefreshTokenTx: commit: %w", err)
	}

	return RotatedSession{
		NewRefreshJTI: newToken.Jti.Bytes,
		RefreshExpiry: newToken.ExpiresAt.Time.UTC(),
	}, nil
}

// ── RevokeFamilyTokens ────────────────────────────────────────────────────────

// RevokeFamilyTokensTx revokes every non-revoked token in the given token family
// and writes an audit row for the revocation. The operation is idempotent:
// tokens already revoked are left untouched by the AND revoked_at IS NULL guard.
//
// userID is required for the audit row — a zero UUID is forensically useless.
func (s *Store) RevokeFamilyTokensTx(ctx context.Context, userID, familyID [16]byte, reason string) error {
	h, err := s.BeginOrBind(ctx)
	// Unreachable: BeginOrBind with TxBound=true never calls Pool.Begin
	// and always returns nil error. No test can trigger this branch.
	if err != nil {
		return fmt.Errorf("store.RevokeFamilyTokensTx: begin tx: %w", err)
	}

	// 1. Revoke every non-revoked token in the family.
	if err := h.Q.RevokeFamilyRefreshTokens(ctx, db.RevokeFamilyRefreshTokensParams{
		Reason:   reason,
		FamilyID: s.ToPgtypeUUID(familyID),
	}); err != nil {
		h.Rollback()
		return fmt.Errorf("store.RevokeFamilyTokensTx: revoke family: %w", err)
	}

	// 2. Audit log.
	// Security: detach unconditionally so the audit row cannot be aborted by a
	// client disconnect — callers outside this package may not apply WithoutCancel.
	if err := h.Q.InsertAuditLog(context.WithoutCancel(ctx), db.InsertAuditLogParams{
		UserID:    s.ToPgtypeUUID(userID),
		EventType: string(audit.EventTokenFamilyRevoked),
		Provider:  db.AuthProviderEmail,
		IpAddress: nil,
		UserAgent: s.ToText(""),
		Metadata:  []byte("{}"),
	}); err != nil {
		h.Rollback()
		return fmt.Errorf("store.RevokeFamilyTokensTx: audit log: %w", err)
	}

	// Unreachable via QuerierProxy: on the TxBound path commitFn is a no-op
	// that always returns nil; on the non-TxBound path commitFn wraps
	// pgx.Tx.Commit which the proxy cannot intercept.
	if err := h.Commit(); err != nil {
		return fmt.Errorf("store.RevokeFamilyTokensTx: commit: %w", err)
	}
	return nil
}

// ── RevokeAllUserTokens ───────────────────────────────────────────────────────

// RevokeAllUserTokensTx atomically revokes every active refresh token, ends
// every open session, and writes an audit row for the given user in a single
// transaction: (1) revoke tokens, (2) end sessions, (3) audit log.
//
// reason is stored verbatim in refresh_tokens.revoke_reason. The operation is
// idempotent via AND revoked_at IS NULL and AND ended_at IS NULL guards.
func (s *Store) RevokeAllUserTokensTx(ctx context.Context, userID [16]byte, reason, ipAddress, userAgent string) error {
	h, err := s.BeginOrBind(ctx)
	// Unreachable: BeginOrBind with TxBound=true never calls Pool.Begin
	// and always returns nil error. No test can trigger this branch.
	if err != nil {
		return fmt.Errorf("store.RevokeAllUserTokensTx: begin tx: %w", err)
	}

	userPgUUID := s.ToPgtypeUUID(userID)

	// 1. Revoke all active (non-expired, non-revoked) refresh tokens.
	if err := h.Q.RevokeAllUserRefreshTokens(ctx, db.RevokeAllUserRefreshTokensParams{
		UserID: userPgUUID,
		Reason: reason,
	}); err != nil {
		h.Rollback()
		return fmt.Errorf("store.RevokeAllUserTokensTx: revoke refresh tokens: %w", err)
	}

	// 2. Close all open sessions. Ordered after token revocation so the token
	// ledger is already clean if a concurrent refresh races the commit.
	if err := h.Q.EndAllUserSessions(ctx, userPgUUID); err != nil {
		h.Rollback()
		return fmt.Errorf("store.RevokeAllUserTokensTx: end sessions: %w", err)
	}

	// 3. Audit log.
	// Security: detach from the request context so a client disconnect cannot
	// suppress the all_sessions_revoked audit row.
	if err := h.Q.InsertAuditLog(context.WithoutCancel(ctx), db.InsertAuditLogParams{
		UserID:    userPgUUID,
		EventType: string(audit.EventAllSessionsRevoked),
		Provider:  db.AuthProviderEmail,
		IpAddress: s.IPToNullable(ipAddress),
		UserAgent: s.ToText(s.TruncateUserAgent(userAgent)),
		Metadata:  []byte("{}"),
	}); err != nil {
		h.Rollback()
		return fmt.Errorf("store.RevokeAllUserTokensTx: audit log: %w", err)
	}

	// Unreachable via QuerierProxy: on the TxBound path commitFn is a no-op
	// that always returns nil; on the non-TxBound path commitFn wraps
	// pgx.Tx.Commit which the proxy cannot intercept.
	if err := h.Commit(); err != nil {
		return fmt.Errorf("store.RevokeAllUserTokensTx: commit: %w", err)
	}
	return nil
}

// ── WriteRefreshFailedAuditTx ───────────────────────────────────────────────

// WriteRefreshFailedAuditTx writes a single refresh_failed audit row.
// userID is always zero — the token was not found or has expired, so no trusted
// user identity is available at this point.
func (s *Store) WriteRefreshFailedAuditTx(ctx context.Context, ipAddress, userAgent string) error {
	h, err := s.BeginOrBind(ctx)
	// Unreachable: BeginOrBind with TxBound=true never calls Pool.Begin
	// and always returns nil error. No test can trigger this branch.
	if err != nil {
		return fmt.Errorf("store.WriteRefreshFailedAuditTx: begin tx: %w", err)
	}

	// 1. Audit row with NULL userID — no trusted identity is available at this
	// point (token not found or expired), so we cannot associate the row with a
	// real user. A zero UUID would violate the FK on auth_audit_log.user_id;
	// NULL is the correct sentinel for an unauthenticated audit event.
	if err := h.Q.InsertAuditLog(ctx, db.InsertAuditLogParams{
		UserID:    pgtype.UUID{}, // NULL — no trusted identity available (FK-safe)
		EventType: string(audit.EventRefreshFailed),
		Provider:  db.AuthProviderEmail,
		IpAddress: s.IPToNullable(ipAddress),
		UserAgent: s.ToText(s.TruncateUserAgent(userAgent)),
		Metadata:  []byte("{}"),
	}); err != nil {
		h.Rollback()
		return fmt.Errorf("store.WriteRefreshFailedAuditTx: audit log: %w", err)
	}

	// Unreachable via QuerierProxy: on the TxBound path commitFn is a no-op
	// that always returns nil; on the non-TxBound path commitFn wraps
	// pgx.Tx.Commit which the proxy cannot intercept.
	if err := h.Commit(); err != nil {
		return fmt.Errorf("store.WriteRefreshFailedAuditTx: commit: %w", err)
	}
	return nil
}

// ── LogoutTx ──────────────────────────────────────────────────────────────────

// LogoutTx atomically:
//  1. Revokes the token identified by JTI (reason = 'logout').
//  2. Ends the session identified by SessionID.
//  3. Writes an audit log row event_type = 'logout'.
//
// The fn_revoke_token_family trigger intentionally skips reason='logout', so
// only this device's token is invalidated — sibling tokens in the same family
// remain valid. Each device manages its own session independently.
func (s *Store) LogoutTx(ctx context.Context, in LogoutTxInput) error {
	h, err := s.BeginOrBind(ctx)
	// Unreachable: BeginOrBind with TxBound=true never calls Pool.Begin
	// and always returns nil error. No test can trigger this branch.
	if err != nil {
		return fmt.Errorf("store.LogoutTx: begin tx: %w", err)
	}

	jtiPg := s.ToPgtypeUUID(in.JTI)
	sessionPg := s.ToPgtypeUUID(in.SessionID)
	userPg := s.ToPgtypeUUID(in.UserID)

	// 1. Revoke this token only (single row; AND revoked_at IS NULL is idempotent).
	if _, err := h.Q.RevokeRefreshTokenByJTI(ctx, db.RevokeRefreshTokenByJTIParams{
		Reason: "logout",
		Jti:    jtiPg,
	}); err != nil {
		h.Rollback()
		return fmt.Errorf("store.LogoutTx: revoke token: %w", err)
	}

	// 2. End the device session (AND ended_at IS NULL is idempotent).
	if err := h.Q.EndUserSession(ctx, sessionPg); err != nil {
		h.Rollback()
		return fmt.Errorf("store.LogoutTx: end session: %w", err)
	}

	// 3. Audit log.
	if err := h.Q.InsertAuditLog(ctx, db.InsertAuditLogParams{
		UserID:    userPg,
		EventType: string(audit.EventLogout),
		Provider:  db.AuthProviderEmail,
		IpAddress: s.IPToNullable(in.IPAddress),
		UserAgent: s.ToText(s.TruncateUserAgent(in.UserAgent)),
		Metadata:  []byte("{}"),
	}); err != nil {
		h.Rollback()
		return fmt.Errorf("store.LogoutTx: audit log: %w", err)
	}

	// Unreachable via QuerierProxy: on the TxBound path commitFn is a no-op
	// that always returns nil; on the non-TxBound path commitFn wraps
	// pgx.Tx.Commit which the proxy cannot intercept.
	if err := h.Commit(); err != nil {
		return fmt.Errorf("store.LogoutTx: commit: %w", err)
	}
	return nil
}
