Write-Host "==============================================================================" -ForegroundColor White
Write-Host " PostgreSQL + Goose + SQLC + Go Makefile" -ForegroundColor Cyan
Write-Host "==============================================================================" -ForegroundColor White
Write-Host ""
Write-Host "QUICK START:" -ForegroundColor Cyan
Write-Host "  make setup              - Complete initial setup"
Write-Host "  make fresh              - Reset database and regenerate code"
Write-Host "  make rebuild            - Rollback all, migrate up, seed, generate"
Write-Host ""
Write-Host "DATABASE:" -ForegroundColor Cyan
Write-Host "  make db-create          - Create database"
Write-Host "  make db-drop            - Drop database"
Write-Host "  make db-reset           - Drop, create, migrate, seed"
Write-Host "  make db-connect         - Connect with psql"
Write-Host "  make db-dump            - Backup database"
Write-Host "  make db-restore         - Restore from backup (BACKUP_FILE=path)"
Write-Host ""
Write-Host "MIGRATIONS:" -ForegroundColor Cyan
Write-Host "  make migrate-status     - Show migration status"
Write-Host "  make migrate-up         - Apply all pending migrations"
Write-Host "  make migrate-up-one     - Apply next single migration"
Write-Host "  make migrate-up-to      - Migrate up to version (VERSION=N)"
Write-Host "  make migrate-down       - Rollback last migration"
Write-Host "  make migrate-down-to    - Rollback to version (VERSION=N)"
Write-Host "  make migrate-reset      - Rollback all migrations (prompts for confirmation)"
Write-Host "  make migrate-refresh    - Rollback ALL then re-apply ALL (no confirmation)"
Write-Host "  make migrate-redo       - Rollback then re-apply last migration"
Write-Host "  make migrate-create     - Create migration (NAME=name)"
Write-Host "  make migrate-validate   - Validate migration files"
Write-Host "  make migrate-version    - Show current migration version"
Write-Host ""
Write-Host "SEEDS:" -ForegroundColor Cyan
Write-Host "  make seed               - Apply seed data"
Write-Host "  make seed-reset         - Reset seed data"
Write-Host "  make seed-status        - Show which seed files have been applied"
Write-Host ""
Write-Host "GO TESTS:" -ForegroundColor Cyan
Write-Host "  make test               - Run unit tests (fast, no DB)"
Write-Host "  make test-integration   - Run integration tests (requires TEST_DATABASE_URL)"
Write-Host "  make test-all           - Run unit + integration tests"
Write-Host "  make test-coverage      - Unit tests with HTML coverage report"
Write-Host ""
Write-Host "CODE GENERATION (SQLC):" -ForegroundColor Cyan
Write-Host "  make sqlc-generate      - Generate Go code from SQL"
Write-Host "  make sqlc-vet           - Vet SQL queries with sqlc"
Write-Host "  make sqlc-compile       - Compile SQL without generating code"
Write-Host ""
Write-Host "SCHEMA TESTING (pgTAP):" -ForegroundColor Cyan
Write-Host "  make db-test-schema               - Run all pgTAP schema tests"
Write-Host "  make db-test-schema-verbose       - Run tests with full TAP output + timing"
Write-Host "  make db-test-schema-file          - Run one file (TEST_FILE=path)"
Write-Host "  make db-test-schema-fresh         - migrate-up then run all tests"
Write-Host "  make db-test-schema-install-pgtap - Install pgTAP extension"
Write-Host "  make db-test-schema-check-deps    - Check pgTAP is ready"
Write-Host ""
Write-Host "DOCKER:" -ForegroundColor Cyan
Write-Host "  make docker-up                - Start Docker containers"
Write-Host "  make docker-down              - Stop Docker containers"
Write-Host "  make docker-logs              - Tail container logs"
Write-Host "  make docker-setup             - Full setup inside Docker"
Write-Host "  make docker-db-tables         - List tables in Docker DB"
Write-Host "  make docker-db-schema         - Show schema in Docker DB"
Write-Host "  make docker-db-indexes        - List indexes in Docker DB"
Write-Host "  make docker-db-functions      - List functions in Docker DB"
Write-Host "  make docker-db-size           - Show Docker DB size"
Write-Host "  make docker-db-table-sizes    - Show per-table sizes in Docker DB"
Write-Host "  make docker-db-connect        - Connect to Docker DB with psql"
Write-Host "  make docker-db-dump           - Backup Docker database"
Write-Host "  make docker-db-restore        - Restore into Docker DB (BACKUP_FILE=path)"
Write-Host "  make docker-db-reset          - Drop, create, migrate, seed in Docker"
Write-Host "  make docker-migrate-status    - Show migrations in Docker DB"
Write-Host "  make docker-migrate-up        - Apply all migrations in Docker DB"
Write-Host "  make docker-migrate-down      - Rollback last migration in Docker DB"
Write-Host "  make docker-migrate-reset     - Rollback all migrations in Docker DB"
Write-Host "  make docker-migrate-redo      - Redo last migration in Docker DB"
Write-Host "  make docker-migrate-version   - Show migration version in Docker DB"
Write-Host "  make docker-seed              - Apply seed data to Docker DB"
Write-Host "  make docker-seed-reset        - Reset seed data in Docker DB"
Write-Host "  make docker-seed-status       - Show seed status in Docker DB"
Write-Host ""
Write-Host "TEST DATABASE:" -ForegroundColor Cyan
Write-Host "  make test-db-setup          - Create test DB + migrate (first-run)"
Write-Host "  make test-db-reset          - Drop, create, and migrate test DB"
Write-Host "  make test-db-create         - Create test database"
Write-Host "  make test-db-drop           - Drop test database"
Write-Host "  make test-db-connect        - Connect to test database with psql"
Write-Host ""
Write-Host "TEST MIGRATIONS:" -ForegroundColor Cyan
Write-Host "  make test-migrate-status    - Show migration status of test DB"
Write-Host "  make test-migrate-up        - Apply all pending migrations to test DB"
Write-Host "  make test-migrate-down      - Rollback last migration on test DB"
Write-Host "  make test-migrate-reset     - Rollback ALL migrations on test DB"
Write-Host "  make test-migrate-refresh   - Rollback ALL then re-apply ALL on test DB"
Write-Host "  make test-migrate-version   - Show migration version of test DB"
Write-Host ""
Write-Host "TEST SEEDS:" -ForegroundColor Cyan
Write-Host "  make test-seed              - Apply seed data to test DB"
Write-Host "  make test-seed-reset        - Reset seed data on test DB"
Write-Host "  make test-seed-status       - Show seed status of test DB"
Write-Host ""
Write-Host "LINTING:" -ForegroundColor Cyan
Write-Host "  make lint              - Run all linters (local - TODOs are warnings)"
Write-Host "  make lint-ci           - Run linters in CI mode (TODOs/FIXMEs fail)"
Write-Host "  make lint-fix          - Auto-fix lint issues where possible"
Write-Host "  make install-lint      - Install golangci-lint"
Write-Host ""
Write-Host "TOOLS:" -ForegroundColor Cyan
Write-Host "  make install-tools      - Install goose, sqlc, and golangci-lint"
Write-Host "  make install-goose      - Install goose only"
Write-Host "  make install-sqlc       - Install sqlc only"
Write-Host ""
Write-Host "INSPECTION:" -ForegroundColor Cyan
Write-Host "  make db-tables          - List all tables"
Write-Host "  make db-schema          - Show complete schema"
Write-Host "  make db-indexes         - List all indexes"
Write-Host "  make db-functions       - List all functions/procedures"
Write-Host "  make db-size            - Show database size"
Write-Host "  make db-table-sizes     - Show per-table sizes"
Write-Host ""
Write-Host "VALIDATION & CI:" -ForegroundColor Cyan
Write-Host "  make check              - Run all validations"
Write-Host "  make ci-test            - CI/CD pipeline: setup and validate"
Write-Host "  make ci-clean           - CI/CD cleanup: drop test database"
Write-Host "  make test-makefile      - Self-test: check dirs and tools exist"
Write-Host ""
Write-Host "E2E TESTS (Newman):" -ForegroundColor Cyan
Write-Host "  make e2e-install        - Install Newman globally"
Write-Host "  make e2e                - Run ALL e2e suites (requires Gmail token)"
Write-Host "  make e2e-ci             - Run ALL e2e suites in CI mode (no Gmail token)"
Write-Host "  make e2e-auth           - Run auth E2E folders 1-4 (requires Gmail token)"
Write-Host "  make e2e-auth-ci        - Run auth E2E folders 2-4 (CI safe, no Gmail)"
Write-Host "  make e2e-auth-expiry    - Run auth E2E folder 5 (token expiry, needs SQL change)"
Write-Host ""
Write-Host "UTILITIES:" -ForegroundColor Cyan
Write-Host "  make env                - Show configuration"
Write-Host "  make env-create         - Create .env from .env.example"
Write-Host "  make db-debug           - Debug connection"
Write-Host "  make clean              - Clean generated files"
Write-Host ""
Write-Host "For detailed help: Select-String '##' Makefile"
Write-Host "==============================================================================" -ForegroundColor White
