//go:build integration_test

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_test.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const AdminLockUserForTest = `-- name: AdminLockUserForTest :exec
UPDATE user_secrets
SET admin_locked        = TRUE,
    admin_locked_reason = 'test lock',
    admin_locked_at     = NOW()
FROM users
WHERE user_secrets.user_id = users.id
  AND users.email = $1::text
`

// Locks an account by setting admin_locked = TRUE for test isolation.
// Mirrors LockUserForTest but exercises the admin-lock code path. Production
// admin-lock logic is handled by the RBAC admin flow; this helper exists only
// to drive the admin_locked guard in store integration tests.
// admin_locked, admin_locked_reason, and admin_locked_at all live in user_secrets
// (001_core.sql schema split). chk_us_admin_lock_coherent requires reason and
// timestamp to be non-NULL whenever admin_locked = TRUE.
// @email::text produces a string parameter instead of pgtype.Text.
func (q *Queries) AdminLockUserForTest(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, AdminLockUserForTest, email)
	return err
}

const BackdateTokenCreatedAt = `-- name: BackdateTokenCreatedAt :exec
UPDATE one_time_tokens
SET created_at = NOW() - INTERVAL '3 minutes'
WHERE email      = $1
  AND token_type = 'email_verification'
  AND used_at    IS NULL
`

// Moves created_at backwards past the resend cooldown window (2 minutes).
// Shifts only created_at, not expires_at, so the token remains valid for consumption.
//
// Constraint check:
//
//	chk_ott_expires_future (expires_at > created_at):
//	  expires_at stays at NOW() + 15 min; created_at moves to NOW() - 3 min → holds.
//	chk_ott_ev_ttl_max (expires_at <= created_at + 30 min):
//	  (NOW() + 15 min) <= (NOW() - 3 min + 30 min) = NOW() + 27 min → holds.
func (q *Queries) BackdateTokenCreatedAt(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, BackdateTokenCreatedAt, email)
	return err
}

const CountActiveRefreshTokensBySession = `-- name: CountActiveRefreshTokensBySession :one
SELECT COUNT(*)::int AS count
FROM refresh_tokens
WHERE session_id = $1::uuid
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

// Returns the number of active (non-revoked, non-expired) refresh tokens for a session.
// Used in profile tests to verify that RevokeSessionTx revokes all session tokens.
func (q *Queries) CountActiveRefreshTokensBySession(ctx context.Context, sessionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, CountActiveRefreshTokensBySession, sessionID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const CountActiveRefreshTokensByUser = `-- name: CountActiveRefreshTokensByUser :one
SELECT COUNT(*)::int AS count
FROM refresh_tokens
WHERE user_id = $1::uuid
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

// Returns the number of active (non-revoked, non-expired) refresh tokens for a user.
// Used in tests to verify that UpdatePasswordHashTx revokes all tokens.
func (q *Queries) CountActiveRefreshTokensByUser(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, CountActiveRefreshTokensByUser, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const CountAuditEventsByUser = `-- name: CountAuditEventsByUser :one
SELECT COUNT(*)::int AS count
FROM auth_audit_log
WHERE user_id    = $1::uuid
  AND event_type = $2
`

type CountAuditEventsByUserParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	EventType string      `db:"event_type" json:"event_type"`
}

// Returns the count of auth_audit_log rows matching a (user_id, event_type) pair.
// Used in store tests to assert that CreateUserTx and LoginTx write the expected
// audit rows without resorting to raw tx.QueryRow calls.
func (q *Queries) CountAuditEventsByUser(ctx context.Context, arg CountAuditEventsByUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, CountAuditEventsByUser, arg.UserID, arg.EventType)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const CountOpenSessionsByUser = `-- name: CountOpenSessionsByUser :one
SELECT COUNT(*)::int AS count
FROM user_sessions
WHERE user_id = $1::uuid
  AND ended_at IS NULL
`

// Returns the number of open sessions (ended_at IS NULL) for a user.
// Used in tests to verify that UpdatePasswordHashTx ends all sessions.
func (q *Queries) CountOpenSessionsByUser(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, CountOpenSessionsByUser, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const CreateVerifiedUserWithUsername = `-- name: CreateVerifiedUserWithUsername :one
WITH new_user AS (
    INSERT INTO users (
        email,
        username,
        display_name,
        is_active,
        email_verified
    )
    VALUES (
        $1,
        $2,
        'Test User',
        TRUE,
        TRUE
    )
    RETURNING id
),
secrets AS (
    INSERT INTO user_secrets (user_id, password_hash)
    SELECT id, $3 FROM new_user
)
SELECT id FROM new_user
`

type CreateVerifiedUserWithUsernameParams struct {
	Email        pgtype.Text `db:"email" json:"email"`
	Username     pgtype.Text `db:"username" json:"username"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

// Inserts a fully-verified, active user with both email and username set.
// Sets is_active = TRUE and email_verified = TRUE directly, bypassing the OTP flow.
// Used in TestLogin_SuccessByUsername to exercise the username login path without
// a real registration + verification cycle.
// display_name is pinned to 'Test User' — irrelevant to the login path under test.
// password_hash was moved to user_secrets (001_core.sql schema split); both rows
// are inserted atomically via a CTE and the new users.id is returned.
func (q *Queries) CreateVerifiedUserWithUsername(ctx context.Context, arg CreateVerifiedUserWithUsernameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, CreateVerifiedUserWithUsername, arg.Email, arg.Username, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const DeleteOTPTokenByID = `-- name: DeleteOTPTokenByID :exec
/*
  Test-support queries for the auth package.

  !! FOR TEST USE ONLY !!
  These queries expose mutations that production code must never perform directly:
  back-dating timestamps, pinning attempt counters, force-deleting users, and
  coercing account states. They are generated into the db package alongside
  production queries and restricted to integration test binaries via the
  //go:build integration_test tag added by the sqlc-generate make target.
*/


DELETE FROM one_time_tokens
WHERE id = $1::uuid
`

// Permanently removes a one_time_tokens row by primary key.
// Used in tests that commit token rows outside a rolled-back transaction
// (e.g. IncrementAttemptsTx independence tests) to clean up via t.Cleanup
// without cascading through user deletion.
func (q *Queries) DeleteOTPTokenByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOTPTokenByID, id)
	return err
}

const DeleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users
WHERE email = $1::text
`

// Permanently deletes a user row by email address.
// Used in tests that commit data to the DB (e.g. IncrementAttemptsTx independence
// tests that require a real INSERT) and then clean up via t.Cleanup.
// @email::text produces a string parameter instead of pgtype.Text, matching
// every other email parameter in the test suite.
func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, DeleteUserByEmail, email)
	return err
}

const ExpirePasswordResetToken = `-- name: ExpirePasswordResetToken :exec
UPDATE one_time_tokens
SET expires_at = created_at + INTERVAL '1 millisecond'
WHERE email      = $1
  AND token_type = 'password_reset'
  AND used_at    IS NULL
`

// Expires a password_reset token by setting expires_at just past created_at.
// created_at is immutable (trg_one_time_tokens_deny_created_at_change) so we
// only touch expires_at. Setting expires_at = created_at + 1 ms satisfies
// chk_ott_expires_future (expires_at > created_at) while placing the expiry
// well in the past by the time any subsequent service call reads the token.
//
// Constraint check:
//
//	chk_ott_expires_future: created_at + 1ms > created_at → holds.
func (q *Queries) ExpirePasswordResetToken(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, ExpirePasswordResetToken, email)
	return err
}

const ExpireVerificationToken = `-- name: ExpireVerificationToken :exec
UPDATE one_time_tokens
SET expires_at = created_at + INTERVAL '1 millisecond'
WHERE email      = $1
  AND token_type = 'email_verification'
  AND used_at    IS NULL
`

// Expires an email_verification token by setting expires_at just past created_at.
// created_at is immutable (trg_one_time_tokens_deny_created_at_change) so we
// only touch expires_at. Setting expires_at = created_at + 1 ms satisfies
// chk_ott_expires_future (expires_at > created_at) and chk_ott_ev_ttl_max
// (created_at + 1ms <= created_at + 15min) while placing the expiry well in
// the past by the time any subsequent service call reads the token.
//
// Constraint checks:
//
//	chk_ott_expires_future: created_at + 1ms > created_at → holds.
//	chk_ott_ev_ttl_max: created_at + 1ms <= created_at + 15min → holds.
func (q *Queries) ExpireVerificationToken(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, ExpireVerificationToken, email)
	return err
}

const GetAuditEventsByUser = `-- name: GetAuditEventsByUser :many
SELECT event_type
FROM auth_audit_log
WHERE user_id = $1::uuid
ORDER BY created_at DESC
`

// Returns all event_type values from auth_audit_log for a given user.
// Used in register tests to verify that the correct audit event was written.
func (q *Queries) GetAuditEventsByUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, GetAuditEventsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var event_type string
		if err := rows.Scan(&event_type); err != nil {
			return nil, err
		}
		items = append(items, event_type)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetLatestRefreshTokenByUser = `-- name: GetLatestRefreshTokenByUser :one
SELECT jti, revoked_at, revoke_reason
FROM refresh_tokens
WHERE user_id = $1::uuid
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestRefreshTokenByUserRow struct {
	Jti          pgtype.UUID        `db:"jti" json:"jti"`
	RevokedAt    pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason pgtype.Text        `db:"revoke_reason" json:"revoke_reason"`
}

// Returns jti, revoked_at and revoke_reason for the most recently created
// refresh token owned by the user.
// Used in TestRevokeAllUserTokens to assert that RevokeAllUserTokens stamps
// revoked_at without resorting to raw SQL.
func (q *Queries) GetLatestRefreshTokenByUser(ctx context.Context, userID pgtype.UUID) (GetLatestRefreshTokenByUserRow, error) {
	row := q.db.QueryRow(ctx, GetLatestRefreshTokenByUser, userID)
	var i GetLatestRefreshTokenByUserRow
	err := row.Scan(&i.Jti, &i.RevokedAt, &i.RevokeReason)
	return i, err
}

const GetLatestSessionByUser = `-- name: GetLatestSessionByUser :one
SELECT id, ended_at
FROM user_sessions
WHERE user_id = $1::uuid
ORDER BY started_at DESC
LIMIT 1
`

type GetLatestSessionByUserRow struct {
	ID      uuid.UUID          `db:"id" json:"id"`
	EndedAt pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
}

// Returns id and ended_at for the most recently started session owned by the user.
// Used in TestRevokeAllUserTokens to assert that RevokeAllUserTokens stamps
// ended_at without resorting to raw SQL.
func (q *Queries) GetLatestSessionByUser(ctx context.Context, userID pgtype.UUID) (GetLatestSessionByUserRow, error) {
	row := q.db.QueryRow(ctx, GetLatestSessionByUser, userID)
	var i GetLatestSessionByUserRow
	err := row.Scan(&i.ID, &i.EndedAt)
	return i, err
}

const GetRefreshTokenExpiry = `-- name: GetRefreshTokenExpiry :one
SELECT expires_at
FROM refresh_tokens
WHERE jti = $1::uuid
`

// Returns expires_at for a refresh token by jti.
// Used in rotation tests to verify that the new token has a fresh 30-day TTL
// rather than inheriting the remaining TTL of the rotated parent.
func (q *Queries) GetRefreshTokenExpiry(ctx context.Context, jti pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, GetRefreshTokenExpiry, jti)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const GetTokenAttempts = `-- name: GetTokenAttempts :one
SELECT attempts
FROM one_time_tokens
WHERE id = $1::uuid
`

// Returns the current attempts counter for a one-time token.
// Used in tests to verify that IncrementAttemptsTx actually incremented the counter.
func (q *Queries) GetTokenAttempts(ctx context.Context, id pgtype.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, GetTokenAttempts, id)
	var attempts int16
	err := row.Scan(&attempts)
	return attempts, err
}

const GetUserIsLocked = `-- name: GetUserIsLocked :one
SELECT is_locked
FROM user_secrets
WHERE user_id = $1::uuid
`

// Returns the is_locked flag for a user.
// Used in tests to assert that account locking logic fired correctly.
// is_locked was moved to user_secrets (001_core.sql schema split).
func (q *Queries) GetUserIsLocked(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, GetUserIsLocked, id)
	var is_locked bool
	err := row.Scan(&is_locked)
	return is_locked, err
}

const GetUserLastLoginAt = `-- name: GetUserLastLoginAt :one
SELECT last_login_at
FROM users
WHERE id = $1::uuid
`

// Returns last_login_at for the given user UUID.
// Used in TestLoginTx_LastLoginAtIsStamped to verify that LoginTx stamps the
// column without resorting to a raw tx.QueryRow call.
func (q *Queries) GetUserLastLoginAt(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, GetUserLastLoginAt, userID)
	var last_login_at pgtype.Timestamptz
	err := row.Scan(&last_login_at)
	return last_login_at, err
}

const LockUserForTest = `-- name: LockUserForTest :exec
WITH target AS (
    UPDATE user_secrets
    SET is_locked = TRUE
    FROM users
    WHERE user_secrets.user_id = users.id
      AND users.email = $1::text
    RETURNING user_secrets.user_id
)
UPDATE users
SET is_active = FALSE
WHERE id = (SELECT user_id FROM target)
`

// Locks an account by setting is_locked = TRUE (OTP-brute-force path) and
// is_active = FALSE for test isolation purposes.
// is_active = FALSE keeps the account in a consistent pre-verification-like state
// for tests that verify the guard order: is_locked is checked BEFORE is_active
// in the login service, so ErrAccountLocked fires regardless of is_active.
// is_locked lives in user_secrets; is_active lives in users. Both are updated
// atomically via a CTE so only one round-trip is needed.
// @email::text produces a string parameter instead of pgtype.Text.
// Production lock logic lives in LockAccount (OTP brute-force path).
func (q *Queries) LockUserForTest(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, LockUserForTest, email)
	return err
}

const PinTokenAttemptsToMax = `-- name: PinTokenAttemptsToMax :exec
UPDATE one_time_tokens
SET attempts = max_attempts
WHERE email      = $1
  AND token_type = 'email_verification'
  AND used_at    IS NULL
`

// Sets attempts = max_attempts for the active email_verification token.
// Used to exercise the brute-force-ceiling guard (Guard 2) in VerifyEmail without
// actually submitting max_attempts wrong codes, which would be slow.
func (q *Queries) PinTokenAttemptsToMax(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, PinTokenAttemptsToMax, email)
	return err
}

const SetAvatarURLForTest = `-- name: SetAvatarURLForTest :exec
UPDATE users
SET avatar_url = $1::text
WHERE id = $2::uuid
`

type SetAvatarURLForTestParams struct {
	AvatarURL string      `db:"avatar_url" json:"avatar_url"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

// Sets avatar_url to a given value for test isolation.
// Used to assert that GetUserProfile correctly populates AvatarURL when non-NULL.
// @avatar_url::text accepts a plain string; @user_id::uuid accepts pgtype.UUID.
func (q *Queries) SetAvatarURLForTest(ctx context.Context, arg SetAvatarURLForTestParams) error {
	_, err := q.db.Exec(ctx, SetAvatarURLForTest, arg.AvatarURL, arg.UserID)
	return err
}

const SuspendUserForTest = `-- name: SuspendUserForTest :exec
UPDATE users
SET is_active = FALSE
WHERE email = $1::text
`

// Suspends an active account by setting is_active = FALSE while leaving is_locked = FALSE.
// The account remains email_verified = TRUE so the is_locked and email_verified guards
// pass, and the is_active guard fires (ErrAccountInactive path in service.Login).
// @email::text produces a string parameter instead of pgtype.Text.
func (q *Queries) SuspendUserForTest(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, SuspendUserForTest, email)
	return err
}
