// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: btc_test.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const TestCountActiveMonitoringRecords = `-- name: TestCountActiveMonitoringRecords :one
SELECT COUNT(*)::integer AS count
FROM invoice_address_monitoring
WHERE network = $1
  AND status  = 'active'
`

// Assert the watch list size for a network.
func (q *Queries) TestCountActiveMonitoringRecords(ctx context.Context, network string) (int32, error) {
	row := q.db.QueryRow(ctx, TestCountActiveMonitoringRecords, network)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const TestDeleteBitcoinTxStatusesByUser = `-- name: TestDeleteBitcoinTxStatusesByUser :exec
DELETE FROM btc_tracked_transactions WHERE user_id = $1::uuid
`

func (q *Queries) TestDeleteBitcoinTxStatusesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, TestDeleteBitcoinTxStatusesByUser, userID)
	return err
}

const TestDeleteBitcoinWatchesByUser = `-- name: TestDeleteBitcoinWatchesByUser :exec
DELETE FROM btc_watches WHERE user_id = $1::uuid
`

func (q *Queries) TestDeleteBitcoinWatchesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, TestDeleteBitcoinWatchesByUser, userID)
	return err
}

const TestDeleteBlockHistory = `-- name: TestDeleteBlockHistory :exec
DELETE FROM bitcoin_block_history WHERE network = $1
`

// Clear block history for a network between tests.
func (q *Queries) TestDeleteBlockHistory(ctx context.Context, network string) error {
	_, err := q.db.Exec(ctx, TestDeleteBlockHistory, network)
	return err
}

const TestDeleteExchangeRateLog = `-- name: TestDeleteExchangeRateLog :exec
DELETE FROM btc_exchange_rate_log WHERE network = $1
`

// Clear rate log entries for a network between tests.
func (q *Queries) TestDeleteExchangeRateLog(ctx context.Context, network string) error {
	_, err := q.db.Exec(ctx, TestDeleteExchangeRateLog, network)
	return err
}

const TestDeleteFinancialAuditEventsByInvoice = `-- name: TestDeleteFinancialAuditEventsByInvoice :exec
DELETE FROM financial_audit_events WHERE invoice_id = $1::uuid
`

// Remove financial audit events for a test invoice.
// financial_audit_events is normally immutable but test teardown requires
// cleaning up test data. This query ONLY exists in the test query file.
func (q *Queries) TestDeleteFinancialAuditEventsByInvoice(ctx context.Context, invoiceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, TestDeleteFinancialAuditEventsByInvoice, invoiceID)
	return err
}

const TestDeleteInvoicesByVendor = `-- name: TestDeleteInvoicesByVendor :exec
/* ════════════════════════════════════════════════════════════
   CLEANUP — for test teardown
   ════════════════════════════════════════════════════════════ */

DELETE FROM invoices WHERE vendor_id = $1::uuid
`

// Remove all invoices for a test vendor. Cascades to invoice_addresses,
// invoice_address_monitoring, and invoice_payments via FK constraints.
// NOTE: financial_audit_events rows with invoice_id are RESTRICT FK — delete
// those first if needed, or use TestDeleteFinancialAuditEventsByInvoice.
func (q *Queries) TestDeleteInvoicesByVendor(ctx context.Context, vendorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, TestDeleteInvoicesByVendor, vendorID)
	return err
}

const TestDeleteOutageLog = `-- name: TestDeleteOutageLog :exec
DELETE FROM btc_outage_log WHERE network = $1
`

// Clear outage records for a network between tests.
func (q *Queries) TestDeleteOutageLog(ctx context.Context, network string) error {
	_, err := q.db.Exec(ctx, TestDeleteOutageLog, network)
	return err
}

const TestDeletePayoutsByVendor = `-- name: TestDeletePayoutsByVendor :exec
DELETE FROM payout_records WHERE vendor_id = $1::uuid
`

// Remove all payout records for a test vendor.
func (q *Queries) TestDeletePayoutsByVendor(ctx context.Context, vendorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, TestDeletePayoutsByVendor, vendorID)
	return err
}

const TestDeleteSSETokensByVendor = `-- name: TestDeleteSSETokensByVendor :exec
DELETE FROM sse_token_issuances WHERE vendor_id = $1::uuid
`

func (q *Queries) TestDeleteSSETokensByVendor(ctx context.Context, vendorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, TestDeleteSSETokensByVendor, vendorID)
	return err
}

const TestDeleteWebhookDeliveriesByVendor = `-- name: TestDeleteWebhookDeliveriesByVendor :exec
DELETE FROM webhook_deliveries WHERE vendor_id = $1::uuid
`

func (q *Queries) TestDeleteWebhookDeliveriesByVendor(ctx context.Context, vendorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, TestDeleteWebhookDeliveriesByVendor, vendorID)
	return err
}

const TestDeleteZMQDeadLettersByNetwork = `-- name: TestDeleteZMQDeadLettersByNetwork :exec
DELETE FROM btc_zmq_dead_letter WHERE network = $1
`

func (q *Queries) TestDeleteZMQDeadLettersByNetwork(ctx context.Context, network string) error {
	_, err := q.db.Exec(ctx, TestDeleteZMQDeadLettersByNetwork, network)
	return err
}

const TestForceInvoiceStatus = `-- name: TestForceInvoiceStatus :exec
UPDATE invoices
SET
    status     = $1::btc_invoice_status,
    updated_at = NOW()
WHERE id = $2::uuid
`

type TestForceInvoiceStatusParams struct {
	Status    BtcInvoiceStatus `db:"status" json:"status"`
	InvoiceID pgtype.UUID      `db:"invoice_id" json:"invoice_id"`
}

// Directly set an invoice status, bypassing the optimistic-locking WHERE clause.
// Used in tests to set up specific preconditions without running the full
// state machine. Never call this in production code.
func (q *Queries) TestForceInvoiceStatus(ctx context.Context, arg TestForceInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, TestForceInvoiceStatus, arg.Status, arg.InvoiceID)
	return err
}

const TestGetAllOutages = `-- name: TestGetAllOutages :many
SELECT id, network, started_at, ended_at FROM btc_outage_log WHERE network = $1 ORDER BY started_at ASC
`

// Return all outage records for a network for assertion.
func (q *Queries) TestGetAllOutages(ctx context.Context, network string) ([]BtcOutageLog, error) {
	rows, err := q.db.Query(ctx, TestGetAllOutages, network)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BtcOutageLog{}
	for rows.Next() {
		var i BtcOutageLog
		if err := rows.Scan(
			&i.ID,
			&i.Network,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestGetBitcoinSyncState = `-- name: TestGetBitcoinSyncState :one
SELECT network, last_processed_height, updated_at FROM bitcoin_sync_state WHERE network = $1
`

func (q *Queries) TestGetBitcoinSyncState(ctx context.Context, network string) (BitcoinSyncState, error) {
	row := q.db.QueryRow(ctx, TestGetBitcoinSyncState, network)
	var i BitcoinSyncState
	err := row.Scan(&i.Network, &i.LastProcessedHeight, &i.UpdatedAt)
	return i, err
}

const TestGetBitcoinTxStatusByID = `-- name: TestGetBitcoinTxStatusByID :one
SELECT id, user_id, network, tracking_mode, address, txid, status, confirmations, amount_sat, fee_rate_sat_vbyte, first_seen_at, last_seen_at, confirmed_at, block_hash, block_height, replacement_txid, created_at, updated_at FROM btc_tracked_transactions WHERE id = $1::bigint
`

// Fetch one raw btc_tracked_transactions row for assertion.
func (q *Queries) TestGetBitcoinTxStatusByID(ctx context.Context, id int64) (BtcTrackedTransaction, error) {
	row := q.db.QueryRow(ctx, TestGetBitcoinTxStatusByID, id)
	var i BtcTrackedTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Network,
		&i.TrackingMode,
		&i.Address,
		&i.Txid,
		&i.Status,
		&i.Confirmations,
		&i.AmountSat,
		&i.FeeRateSatVbyte,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ConfirmedAt,
		&i.BlockHash,
		&i.BlockHeight,
		&i.ReplacementTxid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const TestGetBitcoinWatchByID = `-- name: TestGetBitcoinWatchByID :one
SELECT id, user_id, network, watch_type, address, txid, status, created_at, updated_at FROM btc_watches WHERE id = $1::bigint
`

// Fetch one raw btc_watches row for assertion.
func (q *Queries) TestGetBitcoinWatchByID(ctx context.Context, id int64) (BtcWatch, error) {
	row := q.db.QueryRow(ctx, TestGetBitcoinWatchByID, id)
	var i BtcWatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Network,
		&i.WatchType,
		&i.Address,
		&i.Txid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const TestGetBlockHistory = `-- name: TestGetBlockHistory :many
SELECT height, network, block_hash, pruned, processed_at FROM bitcoin_block_history
WHERE network = $1
ORDER BY height ASC
`

// Return all processed block records for a network in ascending height order.
func (q *Queries) TestGetBlockHistory(ctx context.Context, network string) ([]BitcoinBlockHistory, error) {
	rows, err := q.db.Query(ctx, TestGetBlockHistory, network)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BitcoinBlockHistory{}
	for rows.Next() {
		var i BitcoinBlockHistory
		if err := rows.Scan(
			&i.Height,
			&i.Network,
			&i.BlockHash,
			&i.Pruned,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestGetFinancialAuditEvents = `-- name: TestGetFinancialAuditEvents :many
SELECT id, event_type, timestamp, network, actor_type, actor_id, actor_label, invoice_id, payout_record_id, references_event_id, amount_sat, balance_before_sat, balance_after_sat, fiat_equivalent, fiat_currency_code, rate_stale, metadata FROM financial_audit_events
WHERE invoice_id = $1::uuid
ORDER BY id ASC
`

// Return all audit events for an invoice ordered by id (insertion order).
func (q *Queries) TestGetFinancialAuditEvents(ctx context.Context, invoiceID pgtype.UUID) ([]FinancialAuditEvent, error) {
	rows, err := q.db.Query(ctx, TestGetFinancialAuditEvents, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinancialAuditEvent{}
	for rows.Next() {
		var i FinancialAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Timestamp,
			&i.Network,
			&i.ActorType,
			&i.ActorID,
			&i.ActorLabel,
			&i.InvoiceID,
			&i.PayoutRecordID,
			&i.ReferencesEventID,
			&i.AmountSat,
			&i.BalanceBeforeSat,
			&i.BalanceAfterSat,
			&i.FiatEquivalent,
			&i.FiatCurrencyCode,
			&i.RateStale,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestGetInvoice = `-- name: TestGetInvoice :one
/* ============================================================
   sql/queries_test/btc_test.sql
   Bitcoin payment system test-only queries for sqlc code generation.

   These queries are for tests only — never use them in production code.

   They exist to:
     1. Read internal state for test assertions (bypassing the application
        layer so tests can verify DB-level invariants directly).
     2. Insert fixture data that would normally require multi-step application
        flows (e.g. a pre-settled invoice for a payout test).
     3. Clean up test data between test cases.

   Naming convention: all queries are prefixed with "Test" so the generated
   Go symbols are immediately recognisable as test-only helpers.

   Depends on: 009_btc.sql, 010_btc_payouts.sql
   ============================================================ */


/* ════════════════════════════════════════════════════════════
   DIRECT READS — for test assertions
   ════════════════════════════════════════════════════════════ */

SELECT id, vendor_id, buyer_id, tier_id, network, status, amount_sat, fiat_amount, fiat_currency_code, btc_rate_at_creation, wallet_mode, bridge_destination_address, auto_sweep_threshold_sat, processing_fee_rate, confirmation_depth, miner_fee_cap_sat_vbyte, payment_tolerance_pct, minimum_invoice_sat, overpayment_relative_threshold_pct, overpayment_absolute_threshold_sat, expected_batch_size, invoice_expiry_minutes, expires_at, detected_txid, detected_at, fiat_equiv_at_detection, mempool_absent_since, first_confirmed_block_height, settling_source, sweep_completed, retry_count, fiat_equiv_at_settlement, buyer_refund_address, expired_at, cancelled_at, settled_at, refunded_at, closed_at, created_at, updated_at FROM invoices WHERE id = $1::uuid
`

// Read a raw invoice row for assertion. Includes every column including
// internal fields not normally exposed via application queries.
func (q *Queries) TestGetInvoice(ctx context.Context, invoiceID pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, TestGetInvoice, invoiceID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.BuyerID,
		&i.TierID,
		&i.Network,
		&i.Status,
		&i.AmountSat,
		&i.FiatAmount,
		&i.FiatCurrencyCode,
		&i.BtcRateAtCreation,
		&i.WalletMode,
		&i.BridgeDestinationAddress,
		&i.AutoSweepThresholdSat,
		&i.ProcessingFeeRate,
		&i.ConfirmationDepth,
		&i.MinerFeeCapSatVbyte,
		&i.PaymentTolerancePct,
		&i.MinimumInvoiceSat,
		&i.OverpaymentRelativeThresholdPct,
		&i.OverpaymentAbsoluteThresholdSat,
		&i.ExpectedBatchSize,
		&i.InvoiceExpiryMinutes,
		&i.ExpiresAt,
		&i.DetectedTxid,
		&i.DetectedAt,
		&i.FiatEquivAtDetection,
		&i.MempoolAbsentSince,
		&i.FirstConfirmedBlockHeight,
		&i.SettlingSource,
		&i.SweepCompleted,
		&i.RetryCount,
		&i.FiatEquivAtSettlement,
		&i.BuyerRefundAddress,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.SettledAt,
		&i.RefundedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const TestGetInvoiceAddress = `-- name: TestGetInvoiceAddress :one
SELECT id, invoice_id, address, network, hd_derivation_index, label, created_at FROM invoice_addresses WHERE invoice_id = $1::uuid
`

// Fetch the address record allocated to an invoice.
func (q *Queries) TestGetInvoiceAddress(ctx context.Context, invoiceID pgtype.UUID) (InvoiceAddress, error) {
	row := q.db.QueryRow(ctx, TestGetInvoiceAddress, invoiceID)
	var i InvoiceAddress
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Address,
		&i.Network,
		&i.HdDerivationIndex,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const TestGetInvoiceAddressMonitoring = `-- name: TestGetInvoiceAddressMonitoring :one
SELECT id, invoice_id, address, network, monitor_until, status, created_at, updated_at FROM invoice_address_monitoring WHERE invoice_id = $1::uuid
`

// Fetch the (single active) monitoring record for an invoice.
func (q *Queries) TestGetInvoiceAddressMonitoring(ctx context.Context, invoiceID pgtype.UUID) (InvoiceAddressMonitoring, error) {
	row := q.db.QueryRow(ctx, TestGetInvoiceAddressMonitoring, invoiceID)
	var i InvoiceAddressMonitoring
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Address,
		&i.Network,
		&i.MonitorUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const TestGetInvoicePayments = `-- name: TestGetInvoicePayments :many
SELECT id, invoice_id, txid, vout_index, value_sat, detected_at, double_payment, post_settlement FROM invoice_payments
WHERE invoice_id = $1::uuid
ORDER BY detected_at ASC
`

// Return all payment records for an invoice, ordered by detection time.
func (q *Queries) TestGetInvoicePayments(ctx context.Context, invoiceID pgtype.UUID) ([]InvoicePayment, error) {
	rows, err := q.db.Query(ctx, TestGetInvoicePayments, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoicePayment{}
	for rows.Next() {
		var i InvoicePayment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Txid,
			&i.VoutIndex,
			&i.ValueSat,
			&i.DetectedAt,
			&i.DoublePayment,
			&i.PostSettlement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestGetLatestExchangeRate = `-- name: TestGetLatestExchangeRate :one
SELECT id, network, fiat_currency, rate, source, fetched_at, anomaly_flag, anomaly_reason FROM btc_exchange_rate_log
WHERE network       = $1
  AND fiat_currency = $2
ORDER BY fetched_at DESC
LIMIT 1
`

type TestGetLatestExchangeRateParams struct {
	Network      string `db:"network" json:"network"`
	FiatCurrency string `db:"fiat_currency" json:"fiat_currency"`
}

func (q *Queries) TestGetLatestExchangeRate(ctx context.Context, arg TestGetLatestExchangeRateParams) (BtcExchangeRateLog, error) {
	row := q.db.QueryRow(ctx, TestGetLatestExchangeRate, arg.Network, arg.FiatCurrency)
	var i BtcExchangeRateLog
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.FiatCurrency,
		&i.Rate,
		&i.Source,
		&i.FetchedAt,
		&i.AnomalyFlag,
		&i.AnomalyReason,
	)
	return i, err
}

const TestGetOpenOutage = `-- name: TestGetOpenOutage :one
SELECT id, network, started_at, ended_at FROM btc_outage_log
WHERE network  = $1
  AND ended_at IS NULL
`

func (q *Queries) TestGetOpenOutage(ctx context.Context, network string) (BtcOutageLog, error) {
	row := q.db.QueryRow(ctx, TestGetOpenOutage, network)
	var i BtcOutageLog
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const TestGetPayoutRecord = `-- name: TestGetPayoutRecord :one
SELECT id, invoice_id, vendor_id, network, status, net_satoshis, platform_fee_satoshis, wallet_mode, destination_address, batch_id, batch_txid, vout_index_in_batch, fee_rate_sat_vbyte, miner_fee_satoshis, original_txid, fee_breakdown, kyc_status, resolution_reason, resolution_admin_id, broadcast_at, confirmed_at, rpc_ambiguous, created_at, updated_at, hold_reason, dispute_id FROM payout_records WHERE id = $1::uuid
`

// Fetch a raw payout record for assertion.
func (q *Queries) TestGetPayoutRecord(ctx context.Context, payoutID pgtype.UUID) (PayoutRecord, error) {
	row := q.db.QueryRow(ctx, TestGetPayoutRecord, payoutID)
	var i PayoutRecord
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.VendorID,
		&i.Network,
		&i.Status,
		&i.NetSatoshis,
		&i.PlatformFeeSatoshis,
		&i.WalletMode,
		&i.DestinationAddress,
		&i.BatchID,
		&i.BatchTxid,
		&i.VoutIndexInBatch,
		&i.FeeRateSatVbyte,
		&i.MinerFeeSatoshis,
		&i.OriginalTxid,
		&i.FeeBreakdown,
		&i.KycStatus,
		&i.ResolutionReason,
		&i.ResolutionAdminID,
		&i.BroadcastAt,
		&i.ConfirmedAt,
		&i.RpcAmbiguous,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HoldReason,
		&i.DisputeID,
	)
	return i, err
}

const TestGetPayoutRecordByInvoice = `-- name: TestGetPayoutRecordByInvoice :one
SELECT id, invoice_id, vendor_id, network, status, net_satoshis, platform_fee_satoshis, wallet_mode, destination_address, batch_id, batch_txid, vout_index_in_batch, fee_rate_sat_vbyte, miner_fee_satoshis, original_txid, fee_breakdown, kyc_status, resolution_reason, resolution_admin_id, broadcast_at, confirmed_at, rpc_ambiguous, created_at, updated_at, hold_reason, dispute_id FROM payout_records WHERE invoice_id = $1::uuid
`

// Fetch the payout record for an invoice directly.
func (q *Queries) TestGetPayoutRecordByInvoice(ctx context.Context, invoiceID pgtype.UUID) (PayoutRecord, error) {
	row := q.db.QueryRow(ctx, TestGetPayoutRecordByInvoice, invoiceID)
	var i PayoutRecord
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.VendorID,
		&i.Network,
		&i.Status,
		&i.NetSatoshis,
		&i.PlatformFeeSatoshis,
		&i.WalletMode,
		&i.DestinationAddress,
		&i.BatchID,
		&i.BatchTxid,
		&i.VoutIndexInBatch,
		&i.FeeRateSatVbyte,
		&i.MinerFeeSatoshis,
		&i.OriginalTxid,
		&i.FeeBreakdown,
		&i.KycStatus,
		&i.ResolutionReason,
		&i.ResolutionAdminID,
		&i.BroadcastAt,
		&i.ConfirmedAt,
		&i.RpcAmbiguous,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HoldReason,
		&i.DisputeID,
	)
	return i, err
}

const TestGetPlatformConfig = `-- name: TestGetPlatformConfig :one
SELECT network, treasury_reserve_satoshis, sweep_hold_mode, sweep_hold_reason, sweep_hold_activated_at, platform_wallet_mode_legal_approved, reconciliation_start_height, kyc_enabled, fatf_enabled, webhooks_enabled, disputes_enabled, gdpr_erasure_job_enabled, updated_at, consolidation_enabled, consolidation_max_fee_sat_vbyte, consolidation_window_start, consolidation_window_end FROM platform_config WHERE network = $1
`

func (q *Queries) TestGetPlatformConfig(ctx context.Context, network string) (PlatformConfig, error) {
	row := q.db.QueryRow(ctx, TestGetPlatformConfig, network)
	var i PlatformConfig
	err := row.Scan(
		&i.Network,
		&i.TreasuryReserveSatoshis,
		&i.SweepHoldMode,
		&i.SweepHoldReason,
		&i.SweepHoldActivatedAt,
		&i.PlatformWalletModeLegalApproved,
		&i.ReconciliationStartHeight,
		&i.KycEnabled,
		&i.FatfEnabled,
		&i.WebhooksEnabled,
		&i.DisputesEnabled,
		&i.GdprErasureJobEnabled,
		&i.UpdatedAt,
		&i.ConsolidationEnabled,
		&i.ConsolidationMaxFeeSatVbyte,
		&i.ConsolidationWindowStart,
		&i.ConsolidationWindowEnd,
	)
	return i, err
}

const TestGetReconciliationJobState = `-- name: TestGetReconciliationJobState :one
SELECT network, last_successful_run_at, last_run_at, last_run_result, last_discrepancy_sat, updated_at FROM reconciliation_job_state WHERE network = $1
`

func (q *Queries) TestGetReconciliationJobState(ctx context.Context, network string) (ReconciliationJobState, error) {
	row := q.db.QueryRow(ctx, TestGetReconciliationJobState, network)
	var i ReconciliationJobState
	err := row.Scan(
		&i.Network,
		&i.LastSuccessfulRunAt,
		&i.LastRunAt,
		&i.LastRunResult,
		&i.LastDiscrepancySat,
		&i.UpdatedAt,
	)
	return i, err
}

const TestGetSSETokenIssuances = `-- name: TestGetSSETokenIssuances :many
SELECT id, vendor_id, network, jti_hash, source_ip_hash, expires_at, issued_at, erased FROM sse_token_issuances
WHERE vendor_id = $1::uuid
ORDER BY issued_at ASC
`

// Return all SSE token issuance records for a vendor.
func (q *Queries) TestGetSSETokenIssuances(ctx context.Context, vendorID pgtype.UUID) ([]SseTokenIssuance, error) {
	rows, err := q.db.Query(ctx, TestGetSSETokenIssuances, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SseTokenIssuance{}
	for rows.Next() {
		var i SseTokenIssuance
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Network,
			&i.JtiHash,
			&i.SourceIpHash,
			&i.ExpiresAt,
			&i.IssuedAt,
			&i.Erased,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestGetVendorBalance = `-- name: TestGetVendorBalance :one
SELECT vendor_id, network, balance_satoshis, updated_at FROM vendor_balances
WHERE vendor_id = $1::uuid
  AND network   = $2
`

type TestGetVendorBalanceParams struct {
	VendorID pgtype.UUID `db:"vendor_id" json:"vendor_id"`
	Network  string      `db:"network" json:"network"`
}

// Fetch the raw vendor balance for assertion.
func (q *Queries) TestGetVendorBalance(ctx context.Context, arg TestGetVendorBalanceParams) (VendorBalance, error) {
	row := q.db.QueryRow(ctx, TestGetVendorBalance, arg.VendorID, arg.Network)
	var i VendorBalance
	err := row.Scan(
		&i.VendorID,
		&i.Network,
		&i.BalanceSatoshis,
		&i.UpdatedAt,
	)
	return i, err
}

const TestGetWebhookDeliveries = `-- name: TestGetWebhookDeliveries :many
SELECT id, vendor_id, event_type, payload, invoice_id, payout_record_id, status, attempt_count, max_attempts, next_retry_at, last_error, delivered_at, created_at FROM webhook_deliveries
WHERE vendor_id = $1::uuid
ORDER BY created_at ASC
`

// Return all webhook delivery records for a vendor, ordered by creation.
func (q *Queries) TestGetWebhookDeliveries(ctx context.Context, vendorID pgtype.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, TestGetWebhookDeliveries, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.EventType,
			&i.Payload,
			&i.InvoiceID,
			&i.PayoutRecordID,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestGetZMQDeadLetters = `-- name: TestGetZMQDeadLetters :many
SELECT id, network, event_type, raw_payload, reason, received_at, resolved, resolved_at, resolution_note FROM btc_zmq_dead_letter
WHERE network = $1
ORDER BY received_at ASC
`

// Return all dead letter records for a network.
func (q *Queries) TestGetZMQDeadLetters(ctx context.Context, network string) ([]BtcZmqDeadLetter, error) {
	rows, err := q.db.Query(ctx, TestGetZMQDeadLetters, network)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BtcZmqDeadLetter{}
	for rows.Next() {
		var i BtcZmqDeadLetter
		if err := rows.Scan(
			&i.ID,
			&i.Network,
			&i.EventType,
			&i.RawPayload,
			&i.Reason,
			&i.ReceivedAt,
			&i.Resolved,
			&i.ResolvedAt,
			&i.ResolutionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestInsertBlockHistory = `-- name: TestInsertBlockHistory :exec
INSERT INTO bitcoin_block_history (height, network, block_hash, pruned)
VALUES ($1::bigint, $2, $3, $4::boolean)
ON CONFLICT (height, network) DO NOTHING
`

type TestInsertBlockHistoryParams struct {
	Height    int64       `db:"height" json:"height"`
	Network   string      `db:"network" json:"network"`
	BlockHash pgtype.Text `db:"block_hash" json:"block_hash"`
	Pruned    bool        `db:"pruned" json:"pruned"`
}

// Insert a block history record directly for reconciliation tests.
func (q *Queries) TestInsertBlockHistory(ctx context.Context, arg TestInsertBlockHistoryParams) error {
	_, err := q.db.Exec(ctx, TestInsertBlockHistory,
		arg.Height,
		arg.Network,
		arg.BlockHash,
		arg.Pruned,
	)
	return err
}

const TestInsertOutageRecord = `-- name: TestInsertOutageRecord :one
INSERT INTO btc_outage_log (network, started_at, ended_at)
VALUES (
    $1,
    $2::timestamptz,
    $3::timestamptz
)
RETURNING id, network, started_at, ended_at
`

type TestInsertOutageRecordParams struct {
	Network   string             `db:"network" json:"network"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
}

// Insert an outage record with explicit started_at for time-sensitive tests.
func (q *Queries) TestInsertOutageRecord(ctx context.Context, arg TestInsertOutageRecordParams) (BtcOutageLog, error) {
	row := q.db.QueryRow(ctx, TestInsertOutageRecord, arg.Network, arg.StartedAt, arg.EndedAt)
	var i BtcOutageLog
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const TestInsertVendorBalance = `-- name: TestInsertVendorBalance :exec
/* ════════════════════════════════════════════════════════════
   FIXTURE INSERTS — for setting up test state directly
   Use these to create pre-existing state that would normally
   require multi-step flows (e.g. a pre-settled invoice).
   ════════════════════════════════════════════════════════════ */

INSERT INTO vendor_balances (vendor_id, network, balance_satoshis)
VALUES (
    $1::uuid,
    $2,
    $3::bigint
)
ON CONFLICT (vendor_id, network) DO UPDATE SET
    balance_satoshis = EXCLUDED.balance_satoshis,
    updated_at       = NOW()
`

type TestInsertVendorBalanceParams struct {
	VendorID        pgtype.UUID `db:"vendor_id" json:"vendor_id"`
	Network         string      `db:"network" json:"network"`
	BalanceSatoshis int64       `db:"balance_satoshis" json:"balance_satoshis"`
}

// Directly insert a vendor_balances row for test fixture setup.
// Used when a test needs a vendor to have an existing balance.
func (q *Queries) TestInsertVendorBalance(ctx context.Context, arg TestInsertVendorBalanceParams) error {
	_, err := q.db.Exec(ctx, TestInsertVendorBalance, arg.VendorID, arg.Network, arg.BalanceSatoshis)
	return err
}

const TestListBitcoinTxStatusRelatedAddresses = `-- name: TestListBitcoinTxStatusRelatedAddresses :many
SELECT tracked_transaction_id, address, amount_sat, created_at, updated_at FROM btc_tracked_transaction_addresses
WHERE tracked_transaction_id = $1::bigint
ORDER BY address ASC
`

// Return all related addresses for one tracked tx row.
func (q *Queries) TestListBitcoinTxStatusRelatedAddresses(ctx context.Context, txStatusID int64) ([]BtcTrackedTransactionAddress, error) {
	rows, err := q.db.Query(ctx, TestListBitcoinTxStatusRelatedAddresses, txStatusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BtcTrackedTransactionAddress{}
	for rows.Next() {
		var i BtcTrackedTransactionAddress
		if err := rows.Scan(
			&i.TrackedTransactionID,
			&i.Address,
			&i.AmountSat,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestListBitcoinTxStatusesByUser = `-- name: TestListBitcoinTxStatusesByUser :many
SELECT id, user_id, network, tracking_mode, address, txid, status, confirmations, amount_sat, fee_rate_sat_vbyte, first_seen_at, last_seen_at, confirmed_at, block_hash, block_height, replacement_txid, created_at, updated_at FROM btc_tracked_transactions
WHERE user_id = $1::uuid
ORDER BY COALESCE(confirmed_at, first_seen_at) DESC, id DESC
`

// Return all txstatus rows for one user, newest first.
func (q *Queries) TestListBitcoinTxStatusesByUser(ctx context.Context, userID pgtype.UUID) ([]BtcTrackedTransaction, error) {
	rows, err := q.db.Query(ctx, TestListBitcoinTxStatusesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BtcTrackedTransaction{}
	for rows.Next() {
		var i BtcTrackedTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Network,
			&i.TrackingMode,
			&i.Address,
			&i.Txid,
			&i.Status,
			&i.Confirmations,
			&i.AmountSat,
			&i.FeeRateSatVbyte,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ConfirmedAt,
			&i.BlockHash,
			&i.BlockHeight,
			&i.ReplacementTxid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestListBitcoinWatchesByUser = `-- name: TestListBitcoinWatchesByUser :many
SELECT id, user_id, network, watch_type, address, txid, status, created_at, updated_at FROM btc_watches
WHERE user_id = $1::uuid
  AND status  = 'active'
ORDER BY created_at DESC, id DESC
`

// Return active watch resources for one user.
func (q *Queries) TestListBitcoinWatchesByUser(ctx context.Context, userID pgtype.UUID) ([]BtcWatch, error) {
	rows, err := q.db.Query(ctx, TestListBitcoinWatchesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BtcWatch{}
	for rows.Next() {
		var i BtcWatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Network,
			&i.WatchType,
			&i.Address,
			&i.Txid,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestResetBitcoinSyncState = `-- name: TestResetBitcoinSyncState :exec
UPDATE bitcoin_sync_state
SET
    last_processed_height = -1,
    updated_at            = NOW()
WHERE network = $1
`

// Reset the block-height cursor to -1 (fresh deployment sentinel).
func (q *Queries) TestResetBitcoinSyncState(ctx context.Context, network string) error {
	_, err := q.db.Exec(ctx, TestResetBitcoinSyncState, network)
	return err
}

const TestResetReconciliationState = `-- name: TestResetReconciliationState :exec
UPDATE reconciliation_job_state
SET
    last_successful_run_at = NULL,
    last_run_at            = NULL,
    last_run_result        = NULL,
    last_discrepancy_sat   = NULL,
    updated_at             = NOW()
WHERE network = $1
`

// Reset the reconciliation job state for a network to its initial state.
func (q *Queries) TestResetReconciliationState(ctx context.Context, network string) error {
	_, err := q.db.Exec(ctx, TestResetReconciliationState, network)
	return err
}

const TestSetInvoiceFirstConfirmedHeight = `-- name: TestSetInvoiceFirstConfirmedHeight :exec
UPDATE invoices
SET
    first_confirmed_block_height = $1::bigint,
    updated_at                   = NOW()
WHERE id = $2::uuid
`

type TestSetInvoiceFirstConfirmedHeightParams struct {
	Height    int64       `db:"height" json:"height"`
	InvoiceID pgtype.UUID `db:"invoice_id" json:"invoice_id"`
}

// Directly set first_confirmed_block_height for reorg rollback tests.
func (q *Queries) TestSetInvoiceFirstConfirmedHeight(ctx context.Context, arg TestSetInvoiceFirstConfirmedHeightParams) error {
	_, err := q.db.Exec(ctx, TestSetInvoiceFirstConfirmedHeight, arg.Height, arg.InvoiceID)
	return err
}

const TestSetVendorBalance = `-- name: TestSetVendorBalance :exec
UPDATE vendor_balances
SET balance_satoshis = $1::bigint,
    updated_at       = NOW()
WHERE vendor_id = $2::uuid
  AND network   = $3
`

type TestSetVendorBalanceParams struct {
	BalanceSatoshis int64       `db:"balance_satoshis" json:"balance_satoshis"`
	VendorID        pgtype.UUID `db:"vendor_id" json:"vendor_id"`
	Network         string      `db:"network" json:"network"`
}

// Directly overwrite a vendor balance. Used in tests to set up
// specific starting conditions without going through stored procedures.
func (q *Queries) TestSetVendorBalance(ctx context.Context, arg TestSetVendorBalanceParams) error {
	_, err := q.db.Exec(ctx, TestSetVendorBalance, arg.BalanceSatoshis, arg.VendorID, arg.Network)
	return err
}
