// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Actions an approver can take on a pending request.
type ApprovalActionEnum string

const (
	ApprovalActionEnumApproved ApprovalActionEnum = "approved"
	ApprovalActionEnumRejected ApprovalActionEnum = "rejected"
)

func (e *ApprovalActionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalActionEnum(s)
	case string:
		*e = ApprovalActionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalActionEnum: %T", src)
	}
	return nil
}

type NullApprovalActionEnum struct {
	ApprovalActionEnum ApprovalActionEnum `json:"approval_action_enum"`
	Valid              bool               `json:"valid"` // Valid is true if ApprovalActionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalActionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalActionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalActionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalActionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalActionEnum), nil
}

func (e ApprovalActionEnum) Valid() bool {
	switch e {
	case ApprovalActionEnumApproved,
		ApprovalActionEnumRejected:
		return true
	}
	return false
}

func AllApprovalActionEnumValues() []ApprovalActionEnum {
	return []ApprovalActionEnum{
		ApprovalActionEnumApproved,
		ApprovalActionEnumRejected,
	}
}

// Mutation kind recorded in all *_audit tables. Populated by AFTER INSERT/UPDATE/DELETE triggers.
type AuditChangeTypeEnum string

const (
	AuditChangeTypeEnumCreated AuditChangeTypeEnum = "created"
	AuditChangeTypeEnumUpdated AuditChangeTypeEnum = "updated"
	AuditChangeTypeEnumDeleted AuditChangeTypeEnum = "deleted"
)

func (e *AuditChangeTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditChangeTypeEnum(s)
	case string:
		*e = AuditChangeTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditChangeTypeEnum: %T", src)
	}
	return nil
}

type NullAuditChangeTypeEnum struct {
	AuditChangeTypeEnum AuditChangeTypeEnum `json:"audit_change_type_enum"`
	Valid               bool                `json:"valid"` // Valid is true if AuditChangeTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditChangeTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AuditChangeTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditChangeTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditChangeTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditChangeTypeEnum), nil
}

func (e AuditChangeTypeEnum) Valid() bool {
	switch e {
	case AuditChangeTypeEnumCreated,
		AuditChangeTypeEnumUpdated,
		AuditChangeTypeEnumDeleted:
		return true
	}
	return false
}

func AllAuditChangeTypeEnumValues() []AuditChangeTypeEnum {
	return []AuditChangeTypeEnum{
		AuditChangeTypeEnumCreated,
		AuditChangeTypeEnumUpdated,
		AuditChangeTypeEnumDeleted,
	}
}

// Supported authentication providers. Add values with ALTER TYPE … ADD VALUE; never remove a value referenced by existing rows.
type AuthProvider string

const (
	AuthProviderEmail     AuthProvider = "email"
	AuthProviderMagicLink AuthProvider = "magic_link"
	AuthProviderGoogle    AuthProvider = "google"
	AuthProviderTelegram  AuthProvider = "telegram"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

func (e AuthProvider) Valid() bool {
	switch e {
	case AuthProviderEmail,
		AuthProviderMagicLink,
		AuthProviderGoogle,
		AuthProviderTelegram:
		return true
	}
	return false
}

func AllAuthProviderValues() []AuthProvider {
	return []AuthProvider{
		AuthProviderEmail,
		AuthProviderMagicLink,
		AuthProviderGoogle,
		AuthProviderTelegram,
	}
}

// Delivery channels for request_notifications. One row per event per channel.
type DeliveryChannelEnum string

const (
	DeliveryChannelEnumEmail DeliveryChannelEnum = "email"
	DeliveryChannelEnumSms   DeliveryChannelEnum = "sms"
	DeliveryChannelEnumPush  DeliveryChannelEnum = "push"
	DeliveryChannelEnumInApp DeliveryChannelEnum = "in_app"
)

func (e *DeliveryChannelEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryChannelEnum(s)
	case string:
		*e = DeliveryChannelEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryChannelEnum: %T", src)
	}
	return nil
}

type NullDeliveryChannelEnum struct {
	DeliveryChannelEnum DeliveryChannelEnum `json:"delivery_channel_enum"`
	Valid               bool                `json:"valid"` // Valid is true if DeliveryChannelEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryChannelEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryChannelEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryChannelEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryChannelEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryChannelEnum), nil
}

func (e DeliveryChannelEnum) Valid() bool {
	switch e {
	case DeliveryChannelEnumEmail,
		DeliveryChannelEnumSms,
		DeliveryChannelEnumPush,
		DeliveryChannelEnumInApp:
		return true
	}
	return false
}

func AllDeliveryChannelEnumValues() []DeliveryChannelEnum {
	return []DeliveryChannelEnum{
		DeliveryChannelEnumEmail,
		DeliveryChannelEnumSms,
		DeliveryChannelEnumPush,
		DeliveryChannelEnumInApp,
	}
}

// Status of a single execution attempt. Terminal: success, failed.
type ExecutionStatusEnum string

const (
	ExecutionStatusEnumPending    ExecutionStatusEnum = "pending"
	ExecutionStatusEnumInProgress ExecutionStatusEnum = "in_progress"
	ExecutionStatusEnumSuccess    ExecutionStatusEnum = "success"
	ExecutionStatusEnumFailed     ExecutionStatusEnum = "failed"
	ExecutionStatusEnumRetrying   ExecutionStatusEnum = "retrying"
)

func (e *ExecutionStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionStatusEnum(s)
	case string:
		*e = ExecutionStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionStatusEnum: %T", src)
	}
	return nil
}

type NullExecutionStatusEnum struct {
	ExecutionStatusEnum ExecutionStatusEnum `json:"execution_status_enum"`
	Valid               bool                `json:"valid"` // Valid is true if ExecutionStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionStatusEnum), nil
}

func (e ExecutionStatusEnum) Valid() bool {
	switch e {
	case ExecutionStatusEnumPending,
		ExecutionStatusEnumInProgress,
		ExecutionStatusEnumSuccess,
		ExecutionStatusEnumFailed,
		ExecutionStatusEnumRetrying:
		return true
	}
	return false
}

func AllExecutionStatusEnumValues() []ExecutionStatusEnum {
	return []ExecutionStatusEnum{
		ExecutionStatusEnumPending,
		ExecutionStatusEnumInProgress,
		ExecutionStatusEnumSuccess,
		ExecutionStatusEnumFailed,
		ExecutionStatusEnumRetrying,
	}
}

// Events that produce a notification row in request_notifications.
type NotificationTypeEnum string

const (
	NotificationTypeEnumRequestCreated   NotificationTypeEnum = "request_created"
	NotificationTypeEnumRequestApproved  NotificationTypeEnum = "request_approved"
	NotificationTypeEnumRequestRejected  NotificationTypeEnum = "request_rejected"
	NotificationTypeEnumRequestExecuted  NotificationTypeEnum = "request_executed"
	NotificationTypeEnumRequestFailed    NotificationTypeEnum = "request_failed"
	NotificationTypeEnumRequestCancelled NotificationTypeEnum = "request_cancelled"
)

func (e *NotificationTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationTypeEnum(s)
	case string:
		*e = NotificationTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationTypeEnum: %T", src)
	}
	return nil
}

type NullNotificationTypeEnum struct {
	NotificationTypeEnum NotificationTypeEnum `json:"notification_type_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if NotificationTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationTypeEnum), nil
}

func (e NotificationTypeEnum) Valid() bool {
	switch e {
	case NotificationTypeEnumRequestCreated,
		NotificationTypeEnumRequestApproved,
		NotificationTypeEnumRequestRejected,
		NotificationTypeEnumRequestExecuted,
		NotificationTypeEnumRequestFailed,
		NotificationTypeEnumRequestCancelled:
		return true
	}
	return false
}

func AllNotificationTypeEnumValues() []NotificationTypeEnum {
	return []NotificationTypeEnum{
		NotificationTypeEnumRequestCreated,
		NotificationTypeEnumRequestApproved,
		NotificationTypeEnumRequestRejected,
		NotificationTypeEnumRequestExecuted,
		NotificationTypeEnumRequestFailed,
		NotificationTypeEnumRequestCancelled,
	}
}

// Discriminator for one_time_tokens. Add values with ALTER TYPE … ADD VALUE.
type OneTimeTokenType string

const (
	OneTimeTokenTypeEmailVerification  OneTimeTokenType = "email_verification"
	OneTimeTokenTypePasswordReset      OneTimeTokenType = "password_reset"
	OneTimeTokenTypeMagicLink          OneTimeTokenType = "magic_link"
	OneTimeTokenTypeAccountUnlock      OneTimeTokenType = "account_unlock"
	OneTimeTokenTypeEmailChangeVerify  OneTimeTokenType = "email_change_verify"
	OneTimeTokenTypeEmailChangeConfirm OneTimeTokenType = "email_change_confirm"
	OneTimeTokenTypeAccountDeletion    OneTimeTokenType = "account_deletion"
)

func (e *OneTimeTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OneTimeTokenType(s)
	case string:
		*e = OneTimeTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for OneTimeTokenType: %T", src)
	}
	return nil
}

type NullOneTimeTokenType struct {
	OneTimeTokenType OneTimeTokenType `json:"one_time_token_type"`
	Valid            bool             `json:"valid"` // Valid is true if OneTimeTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOneTimeTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.OneTimeTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OneTimeTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOneTimeTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OneTimeTokenType), nil
}

func (e OneTimeTokenType) Valid() bool {
	switch e {
	case OneTimeTokenTypeEmailVerification,
		OneTimeTokenTypePasswordReset,
		OneTimeTokenTypeMagicLink,
		OneTimeTokenTypeAccountUnlock,
		OneTimeTokenTypeEmailChangeVerify,
		OneTimeTokenTypeEmailChangeConfirm,
		OneTimeTokenTypeAccountDeletion:
		return true
	}
	return false
}

func AllOneTimeTokenTypeValues() []OneTimeTokenType {
	return []OneTimeTokenType{
		OneTimeTokenTypeEmailVerification,
		OneTimeTokenTypePasswordReset,
		OneTimeTokenTypeMagicLink,
		OneTimeTokenTypeAccountUnlock,
		OneTimeTokenTypeEmailChangeVerify,
		OneTimeTokenTypeEmailChangeConfirm,
		OneTimeTokenTypeAccountDeletion,
	}
}

// Request lifecycle states. Terminal: rejected, cancelled, completed, failed.
type RequestStatusEnum string

const (
	RequestStatusEnumPending   RequestStatusEnum = "pending"
	RequestStatusEnumApproved  RequestStatusEnum = "approved"
	RequestStatusEnumRejected  RequestStatusEnum = "rejected"
	RequestStatusEnumCancelled RequestStatusEnum = "cancelled"
	RequestStatusEnumExecuting RequestStatusEnum = "executing"
	RequestStatusEnumCompleted RequestStatusEnum = "completed"
	RequestStatusEnumFailed    RequestStatusEnum = "failed"
)

func (e *RequestStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatusEnum(s)
	case string:
		*e = RequestStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatusEnum: %T", src)
	}
	return nil
}

type NullRequestStatusEnum struct {
	RequestStatusEnum RequestStatusEnum `json:"request_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if RequestStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatusEnum), nil
}

func (e RequestStatusEnum) Valid() bool {
	switch e {
	case RequestStatusEnumPending,
		RequestStatusEnumApproved,
		RequestStatusEnumRejected,
		RequestStatusEnumCancelled,
		RequestStatusEnumExecuting,
		RequestStatusEnumCompleted,
		RequestStatusEnumFailed:
		return true
	}
	return false
}

func AllRequestStatusEnumValues() []RequestStatusEnum {
	return []RequestStatusEnum{
		RequestStatusEnumPending,
		RequestStatusEnumApproved,
		RequestStatusEnumRejected,
		RequestStatusEnumCancelled,
		RequestStatusEnumExecuting,
		RequestStatusEnumCompleted,
		RequestStatusEnumFailed,
	}
}

// Permanent record of hard-purged accounts. user_id has no FK constraint because the users row is deleted before this record is written.
type AccountPurgeLog struct {
	ID       uuid.UUID          `db:"id" json:"id"`
	UserID   pgtype.UUID        `db:"user_id" json:"user_id"`
	PurgedAt pgtype.Timestamptz `db:"purged_at" json:"purged_at"`
	Metadata []byte             `db:"metadata" json:"metadata"`
}

// Security event log. Rows are deleted when the owning user is deleted (ON DELETE CASCADE) or by periodic retention sweeps. trg_deny_audit_update enforces immutability — existing rows may not be edited.
type AuthAuditLog struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	EventType string           `db:"event_type" json:"event_type"`
	Provider  NullAuthProvider `db:"provider" json:"provider"`
	IpAddress *netip.Addr      `db:"ip_address" json:"ip_address"`
	UserAgent pgtype.Text      `db:"user_agent" json:"user_agent"`
	Metadata  []byte           `db:"metadata" json:"metadata"`
	CreatedAt time.Time        `db:"created_at" json:"created_at"`
}

// Single-table token store for email_verification, password_reset, magic_link, account_unlock, email_change_verify, and email_change_confirm flows.
type OneTimeToken struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	TokenType OneTimeTokenType `db:"token_type" json:"token_type"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	Email     string           `db:"email" json:"email"`
	TokenHash pgtype.Text      `db:"token_hash" json:"token_hash"`
	CodeHash  pgtype.Text      `db:"code_hash" json:"code_hash"`
	// Auxiliary payload keyed by token_type. email_change_verify stores {"new_email": "..."} so the confirm step can retrieve the destination address without a separate KV lookup.
	Metadata []byte `db:"metadata" json:"metadata"`
	Attempts int16  `db:"attempts" json:"attempts"`
	// 0 = no attempt limit (non-OTP types). OTP types use 3.
	MaxAttempts int16 `db:"max_attempts" json:"max_attempts"`
	// Timestamp of the most recent failed OTP attempt.
	LastAttemptAt pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	RedirectTo    pgtype.Text        `db:"redirect_to" json:"redirect_to"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt        pgtype.Timestamptz `db:"used_at" json:"used_at"`
	IpAddress     *netip.Addr        `db:"ip_address" json:"ip_address"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
}

// Permission definitions. Canonical form: resource_type:name (e.g. product:create). Soft-delete via is_active.
type Permission struct {
	ID uuid.UUID `db:"id" json:"id"`
	// Action verb: create, read, update, delete, approve, export, etc.
	Name string `db:"name" json:"name"`
	// Resource domain: product, request, vendor_payout, analytics, etc.
	ResourceType string      `db:"resource_type" json:"resource_type"`
	Description  pgtype.Text `db:"description" json:"description"`
	// Generated: resource_type || ':' || name. Used for fast canonical-name lookups.
	CanonicalName pgtype.Text `db:"canonical_name" json:"canonical_name"`
	IsActive      pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
}

// Per-permission rules defining valid ABAC conditions on grants. Structural checks enforced by DB trigger; value validation in app layer.
type PermissionConditionTemplate struct {
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	// Keys that MUST be present in conditions on any grant for this permission.
	RequiredConditions []byte `db:"required_conditions" json:"required_conditions"`
	// Keys that MUST NOT appear in conditions — prevents known privilege escalation paths.
	ForbiddenConditions []byte `db:"forbidden_conditions" json:"forbidden_conditions"`
	// Per-key type/range/enum constraints. Evaluated in the app layer; adding new rule types requires no DB migration.
	ValidationRules []byte    `db:"validation_rules" json:"validation_rules"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}

// Groups permissions for UI organisation and bulk role assignment. A permission may belong to multiple groups.
type PermissionGroup struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Description  pgtype.Text `db:"description" json:"description"`
	DisplayLabel pgtype.Text `db:"display_label" json:"display_label"`
	Icon         pgtype.Text `db:"icon" json:"icon"`
	// Hex colour for UI badges. Must be #RRGGBB — enforced by chk_pg_color_hex_format.
	ColorHex     pgtype.Text `db:"color_hex" json:"color_hex"`
	DisplayOrder pgtype.Int4 `db:"display_order" json:"display_order"`
	// FALSE = hidden from non-admin interfaces (e.g. internal or system-only groups).
	IsVisible pgtype.Bool `db:"is_visible" json:"is_visible"`
	IsActive  pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt time.Time   `db:"updated_at" json:"updated_at"`
}

// Many-to-many join between permission_groups and permissions. CASCADE DELETE on both sides.
type PermissionGroupMember struct {
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
}

// Server-side refresh token ledger with individual revocation and family-based reuse detection (RFC 6819 §5.2.2.3).
type RefreshToken struct {
	Jti       pgtype.UUID        `db:"jti" json:"jti"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	SessionID pgtype.UUID        `db:"session_id" json:"session_id"`
	FamilyID  pgtype.UUID        `db:"family_id" json:"family_id"`
	ParentJti pgtype.UUID        `db:"parent_jti" json:"parent_jti"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	// Max 256 chars. Known values: logout, rotated, reuse_detected, pre_verification, session_revoked, session_expired, password_changed, forced_logout, family_revoked:<reason>.
	RevokeReason pgtype.Text `db:"revoke_reason" json:"revoke_reason"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time   `db:"updated_at" json:"updated_at"`
}

// Approval requests with flexible JSONB payloads and quorum support.
type Request struct {
	ID uuid.UUID `db:"id" json:"id"`
	// Discriminator: product_creation, vendor_withdrawal, etc.
	RequestType string            `db:"request_type" json:"request_type"`
	RequesterID pgtype.UUID       `db:"requester_id" json:"requester_id"`
	Status      RequestStatusEnum `db:"status" json:"status"`
	// Flexible payload. Structure validated against request_type_schemas.
	RequestData []byte `db:"request_data" json:"request_data"`
	// Higher = more urgent. Used to order the approval queue.
	Priority pgtype.Int4 `db:"priority" json:"priority"`
	// Number of approvals needed before the request transitions to approved.
	ApprovalsRequired pgtype.Int4 `db:"approvals_required" json:"approvals_required"`
	// Auto-reject if still pending past this time.
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt  time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time          `db:"updated_at" json:"updated_at"`
	ResolvedAt pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
}

// Immutable audit trail of approval/rejection actions.
type RequestApproval struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	RequestID  pgtype.UUID `db:"request_id" json:"request_id"`
	ApproverID pgtype.UUID `db:"approver_id" json:"approver_id"`
	// Role that authorised this approval. RESTRICT preserves the reference even if the role is soft-deleted.
	RoleUsed   pgtype.UUID        `db:"role_used" json:"role_used"`
	Action     ApprovalActionEnum `db:"action" json:"action"`
	Comment    pgtype.Text        `db:"comment" json:"comment"`
	ApprovedAt pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
}

// Tracks execution of approved requests with retry support and idempotency.
type RequestExecution struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	RequestID pgtype.UUID `db:"request_id" json:"request_id"`
	// Prevents duplicate execution attempts for the same request.
	IdempotencyKey pgtype.UUID `db:"idempotency_key" json:"idempotency_key"`
	// What action was taken, e.g. product_created, payment_sent.
	ExecutedAction string `db:"executed_action" json:"executed_action"`
	// JSONB result data: IDs, hashes, metadata, etc.
	ExecutionResult []byte              `db:"execution_result" json:"execution_result"`
	Status          ExecutionStatusEnum `db:"status" json:"status"`
	ErrorMessage    pgtype.Text         `db:"error_message" json:"error_message"`
	RetryCount      pgtype.Int4         `db:"retry_count" json:"retry_count"`
	ExecutedBy      pgtype.UUID         `db:"executed_by" json:"executed_by"`
	StartedAt       pgtype.Timestamptz  `db:"started_at" json:"started_at"`
	// Set when status transitions to success or failed.
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

// Notification queue for request status changes with per-channel delivery tracking.
type RequestNotification struct {
	ID               uuid.UUID               `db:"id" json:"id"`
	RequestID        pgtype.UUID             `db:"request_id" json:"request_id"`
	UserID           pgtype.UUID             `db:"user_id" json:"user_id"`
	NotificationType NotificationTypeEnum    `db:"notification_type" json:"notification_type"`
	DeliveryChannel  NullDeliveryChannelEnum `db:"delivery_channel" json:"delivery_channel"`
	// NULL = queued, non-NULL = delivered.
	SentAt pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	// NULL = unread. Set when the user views the notification.
	ReadAt           pgtype.Timestamptz `db:"read_at" json:"read_at"`
	DeliveryAttempts pgtype.Int4        `db:"delivery_attempts" json:"delivery_attempts"`
	LastAttemptAt    pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	DeliveryError    pgtype.Text        `db:"delivery_error" json:"delivery_error"`
	Title            pgtype.Text        `db:"title" json:"title"`
	Message          pgtype.Text        `db:"message" json:"message"`
	CreatedAt        time.Time          `db:"created_at" json:"created_at"`
}

// Per-user, per-type sliding window counters for request creation rate limiting.
type RequestRateLimit struct {
	UserID               pgtype.UUID `db:"user_id" json:"user_id"`
	RequestType          string      `db:"request_type" json:"request_type"`
	RequestsCreatedCount pgtype.Int4 `db:"requests_created_count" json:"requests_created_count"`
	// Start of the current rate-limit window. Reset when the window expires.
	WindowStart   pgtype.Timestamptz `db:"window_start" json:"window_start"`
	LastRequestAt pgtype.Timestamptz `db:"last_request_at" json:"last_request_at"`
}

// Which roles can approve each request, with multi-level hierarchy support.
type RequestRequiredApprover struct {
	RequestID pgtype.UUID `db:"request_id" json:"request_id"`
	RoleID    pgtype.UUID `db:"role_id" json:"role_id"`
	// Hierarchical level: 0 = first, 1 = second, etc.
	ApprovalLevel pgtype.Int4 `db:"approval_level" json:"approval_level"`
	MinRequired   pgtype.Int4 `db:"min_required" json:"min_required"`
	// TRUE = all lower levels must be satisfied before this level can act.
	MustCompletePreviousLevel pgtype.Bool `db:"must_complete_previous_level" json:"must_complete_previous_level"`
	Conditions                []byte      `db:"conditions" json:"conditions"`
	CreatedAt                 time.Time   `db:"created_at" json:"created_at"`
}

// SLA thresholds per request_type for alerting and violation detection.
type RequestSlaConfig struct {
	RequestType          string      `db:"request_type" json:"request_type"`
	PendingMaxHours      int32       `db:"pending_max_hours" json:"pending_max_hours"`
	ExecutionMaxMinutes  int32       `db:"execution_max_minutes" json:"execution_max_minutes"`
	NotifyApproachingSla pgtype.Bool `db:"notify_approaching_sla" json:"notify_approaching_sla"`
	// Alert is triggered when this percentage of the SLA window has elapsed.
	ApproachingThresholdPercent pgtype.Int4 `db:"approaching_threshold_percent" json:"approaching_threshold_percent"`
	CreatedAt                   time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt                   time.Time   `db:"updated_at" json:"updated_at"`
}

// Records SLA breaches for monitoring, alerting, and reporting.
type RequestSlaViolation struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	RequestID pgtype.UUID `db:"request_id" json:"request_id"`
	// pending_timeout = request sat in pending too long; execution_timeout = execution took too long.
	ViolationType string             `db:"violation_type" json:"violation_type"`
	DetectedAt    pgtype.Timestamptz `db:"detected_at" json:"detected_at"`
	ResolvedAt    pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	Notified      pgtype.Bool        `db:"notified" json:"notified"`
}

// JSON Schema validation rules for request_data keyed by request_type.
type RequestTypeSchema struct {
	RequestType string `db:"request_type" json:"request_type"`
	// JSON Schema defining required fields, types, and constraints for this request_type.
	JsonSchema []byte    `db:"json_schema" json:"json_schema"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

// Role definitions (Owner, Admin, Vendor, Customer, etc.). Soft-delete via is_active — hard DELETE is blocked by RESTRICT FKs on audit tables.
type Role struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	// TRUE = built-in role managed by ops. Cannot be deleted by end users.
	IsSystemRole pgtype.Bool `db:"is_system_role" json:"is_system_role"`
	// TRUE = unrestricted access. chk_roles_owner_must_be_system requires is_system_role = TRUE simultaneously.
	IsOwnerRole pgtype.Bool `db:"is_owner_role" json:"is_owner_role"`
	// FALSE = soft-deleted. Always filter WHERE is_active = TRUE.
	IsActive  pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt time.Time   `db:"updated_at" json:"updated_at"`
}

// Maps roles → permissions with optional ABAC conditions. Every grant requires a named accountable human. All mutations logged to role_permissions_audit.
type RolePermission struct {
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	// JSONB object narrowing when the permission applies. Validated against permission_condition_templates in the app layer.
	Conditions []byte `db:"conditions" json:"conditions"`
	// RESTRICT prevents that user being deleted while the grant exists.
	GrantedBy     pgtype.UUID `db:"granted_by" json:"granted_by"`
	GrantedReason string      `db:"granted_reason" json:"granted_reason"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
}

// Immutable audit log for role_permissions. Populated by trg_audit_role_permissions. RESTRICT FKs prevent deletion of referenced rows while history exists.
type RolePermissionsAudit struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	Conditions   []byte      `db:"conditions" json:"conditions"`
	// Snapshot of conditions before the mutation. NULL on INSERT.
	PreviousConditions []byte              `db:"previous_conditions" json:"previous_conditions"`
	ChangeType         AuditChangeTypeEnum `db:"change_type" json:"change_type"`
	ChangedBy          pgtype.UUID         `db:"changed_by" json:"changed_by"`
	ChangedAt          pgtype.Timestamptz  `db:"changed_at" json:"changed_at"`
	ChangeReason       pgtype.Text         `db:"change_reason" json:"change_reason"`
}

// Core identity record. trg_require_auth_method enforces at least one auth method per row.
type User struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	Email       pgtype.Text `db:"email" json:"email"`
	Username    pgtype.Text `db:"username" json:"username"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	AvatarURL   pgtype.Text `db:"avatar_url" json:"avatar_url"`
	// bcrypt hash ($2a/$2b, length 60). NULL for OAuth-only users. Never store plaintext.
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
	// FALSE until email verification completes.
	IsActive      bool `db:"is_active" json:"is_active"`
	EmailVerified bool `db:"email_verified" json:"email_verified"`
	// Set by OTP brute-force exhaustion (LockAccount). Cleared by the account-unlock OTP flow or by admin action. Never self-clears.
	IsLocked bool `db:"is_locked" json:"is_locked"`
	// Set and cleared exclusively by admin action (RBAC). The user-facing OTP unlock flow must never touch this field. Independent of is_locked.
	AdminLocked                  bool               `db:"admin_locked" json:"admin_locked"`
	FailedLoginAttempts          int16              `db:"failed_login_attempts" json:"failed_login_attempts"`
	LoginLockedUntil             pgtype.Timestamptz `db:"login_locked_until" json:"login_locked_until"`
	FailedChangePasswordAttempts int16              `db:"failed_change_password_attempts" json:"failed_change_password_attempts"`
	CreatedAt                    time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt                    time.Time          `db:"updated_at" json:"updated_at"`
	LastLoginAt                  pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	DeletedAt                    *time.Time         `db:"deleted_at" json:"deleted_at"`
}

// OAuth / external auth identities. One row per (provider, external account).
type UserIdentity struct {
	ID            uuid.UUID    `db:"id" json:"id"`
	UserID        pgtype.UUID  `db:"user_id" json:"user_id"`
	Provider      AuthProvider `db:"provider" json:"provider"`
	ProviderUid   string       `db:"provider_uid" json:"provider_uid"`
	ProviderEmail pgtype.Text  `db:"provider_email" json:"provider_email"`
	DisplayName   pgtype.Text  `db:"display_name" json:"display_name"`
	AvatarURL     pgtype.Text  `db:"avatar_url" json:"avatar_url"`
	// AES-256-GCM ciphertext with enc: prefix. chk_ui_access_token_encrypted rejects unencrypted values.
	AccessToken          pgtype.Text        `db:"access_token" json:"access_token"`
	AccessTokenExpiresAt pgtype.Timestamptz `db:"access_token_expires_at" json:"access_token_expires_at"`
	RefreshTokenProvider pgtype.Text        `db:"refresh_token_provider" json:"refresh_token_provider"`
	RawProfile           []byte             `db:"raw_profile" json:"raw_profile"`
	CreatedAt            time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time          `db:"updated_at" json:"updated_at"`
}

// Temporary direct permission grants — exceptions to the role model. Revocation = DELETE; history preserved in user_permissions_audit. Granter must hold the permission themselves (trg_prevent_privilege_escalation).
type UserPermission struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	// ABAC conditions in the same vocabulary as role_permissions. Validated against permission_condition_templates in the app layer.
	Conditions    []byte      `db:"conditions" json:"conditions"`
	GrantedBy     pgtype.UUID `db:"granted_by" json:"granted_by"`
	GrantedReason string      `db:"granted_reason" json:"granted_reason"`
	// REQUIRED. Bounded by trg_validate_user_permission_expiry: min 5 min, max 90 days from now.
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt time.Time          `db:"updated_at" json:"updated_at"`
}

// Immutable audit log for user_permissions — highest-risk RBAC table; every mutation is tracked unconditionally. Populated by trg_audit_user_permissions.
type UserPermissionsAudit struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	Conditions   []byte      `db:"conditions" json:"conditions"`
	// Snapshot of conditions before the mutation. NULL on INSERT.
	PreviousConditions []byte              `db:"previous_conditions" json:"previous_conditions"`
	ChangeType         AuditChangeTypeEnum `db:"change_type" json:"change_type"`
	ChangedBy          pgtype.UUID         `db:"changed_by" json:"changed_by"`
	ChangedAt          pgtype.Timestamptz  `db:"changed_at" json:"changed_at"`
	ChangeReason       pgtype.Text         `db:"change_reason" json:"change_reason"`
}

// Assigns exactly one role per user. user_id PK enforces this at the DB level. Deletion of the last active owner is blocked by trg_prevent_orphaned_owner.
type UserRole struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	RoleID pgtype.UUID `db:"role_id" json:"role_id"`
	// RESTRICT prevents that user being deleted while the assignment exists.
	GrantedBy     pgtype.UUID `db:"granted_by" json:"granted_by"`
	GrantedReason string      `db:"granted_reason" json:"granted_reason"`
	// NULL = permanent. Always filter: (expires_at IS NULL OR expires_at > NOW()).
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt time.Time          `db:"updated_at" json:"updated_at"`
}

// Immutable audit log for user_roles. Populated by trg_audit_user_roles. RESTRICT FKs prevent deletion of referenced rows while history exists.
type UserRolesAudit struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	RoleID pgtype.UUID `db:"role_id" json:"role_id"`
	// Snapshot of role_id before the change. NULL on the initial grant.
	PreviousRoleID pgtype.UUID         `db:"previous_role_id" json:"previous_role_id"`
	ChangeType     AuditChangeTypeEnum `db:"change_type" json:"change_type"`
	ChangedBy      pgtype.UUID         `db:"changed_by" json:"changed_by"`
	ChangedAt      pgtype.Timestamptz  `db:"changed_at" json:"changed_at"`
	ChangeReason   pgtype.Text         `db:"change_reason" json:"change_reason"`
}

// Login sessions for active-device visibility and audit. Not used for token validation.
type UserSession struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	AuthProvider NullAuthProvider   `db:"auth_provider" json:"auth_provider"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	LastActiveAt pgtype.Timestamptz `db:"last_active_at" json:"last_active_at"`
	EndedAt      pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	UserAgent    pgtype.Text        `db:"user_agent" json:"user_agent"`
	IpAddress    *netip.Addr        `db:"ip_address" json:"ip_address"`
	DeviceName   pgtype.Text        `db:"device_name" json:"device_name"`
}
