// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Actions an approver can take on a pending request.
type ApprovalActionEnum string

const (
	ApprovalActionEnumApproved ApprovalActionEnum = "approved"
	ApprovalActionEnumRejected ApprovalActionEnum = "rejected"
)

func (e *ApprovalActionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalActionEnum(s)
	case string:
		*e = ApprovalActionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalActionEnum: %T", src)
	}
	return nil
}

type NullApprovalActionEnum struct {
	ApprovalActionEnum ApprovalActionEnum `json:"approval_action_enum"`
	Valid              bool               `json:"valid"` // Valid is true if ApprovalActionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalActionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalActionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalActionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalActionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalActionEnum), nil
}

func (e ApprovalActionEnum) Valid() bool {
	switch e {
	case ApprovalActionEnumApproved,
		ApprovalActionEnumRejected:
		return true
	}
	return false
}

func AllApprovalActionEnumValues() []ApprovalActionEnum {
	return []ApprovalActionEnum{
		ApprovalActionEnumApproved,
		ApprovalActionEnumRejected,
	}
}

// Mutation kind recorded in all *_audit tables. Populated by AFTER INSERT/UPDATE/DELETE triggers.
type AuditChangeTypeEnum string

const (
	AuditChangeTypeEnumCreated AuditChangeTypeEnum = "created"
	AuditChangeTypeEnumUpdated AuditChangeTypeEnum = "updated"
	AuditChangeTypeEnumDeleted AuditChangeTypeEnum = "deleted"
)

func (e *AuditChangeTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditChangeTypeEnum(s)
	case string:
		*e = AuditChangeTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditChangeTypeEnum: %T", src)
	}
	return nil
}

type NullAuditChangeTypeEnum struct {
	AuditChangeTypeEnum AuditChangeTypeEnum `json:"audit_change_type_enum"`
	Valid               bool                `json:"valid"` // Valid is true if AuditChangeTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditChangeTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AuditChangeTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditChangeTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditChangeTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditChangeTypeEnum), nil
}

func (e AuditChangeTypeEnum) Valid() bool {
	switch e {
	case AuditChangeTypeEnumCreated,
		AuditChangeTypeEnumUpdated,
		AuditChangeTypeEnumDeleted:
		return true
	}
	return false
}

func AllAuditChangeTypeEnumValues() []AuditChangeTypeEnum {
	return []AuditChangeTypeEnum{
		AuditChangeTypeEnumCreated,
		AuditChangeTypeEnumUpdated,
		AuditChangeTypeEnumDeleted,
	}
}

// Supported authentication providers. Add values with ALTER TYPE … ADD VALUE; never remove a value referenced by existing rows.
type AuthProvider string

const (
	AuthProviderEmail     AuthProvider = "email"
	AuthProviderMagicLink AuthProvider = "magic_link"
	AuthProviderGoogle    AuthProvider = "google"
	AuthProviderTelegram  AuthProvider = "telegram"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

func (e AuthProvider) Valid() bool {
	switch e {
	case AuthProviderEmail,
		AuthProviderMagicLink,
		AuthProviderGoogle,
		AuthProviderTelegram:
		return true
	}
	return false
}

func AllAuthProviderValues() []AuthProvider {
	return []AuthProvider{
		AuthProviderEmail,
		AuthProviderMagicLink,
		AuthProviderGoogle,
		AuthProviderTelegram,
	}
}

// Delivery channels for request_notifications. One row per event per channel.
type DeliveryChannelEnum string

const (
	DeliveryChannelEnumEmail DeliveryChannelEnum = "email"
	DeliveryChannelEnumSms   DeliveryChannelEnum = "sms"
	DeliveryChannelEnumPush  DeliveryChannelEnum = "push"
	DeliveryChannelEnumInApp DeliveryChannelEnum = "in_app"
)

func (e *DeliveryChannelEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryChannelEnum(s)
	case string:
		*e = DeliveryChannelEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryChannelEnum: %T", src)
	}
	return nil
}

type NullDeliveryChannelEnum struct {
	DeliveryChannelEnum DeliveryChannelEnum `json:"delivery_channel_enum"`
	Valid               bool                `json:"valid"` // Valid is true if DeliveryChannelEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryChannelEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryChannelEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryChannelEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryChannelEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryChannelEnum), nil
}

func (e DeliveryChannelEnum) Valid() bool {
	switch e {
	case DeliveryChannelEnumEmail,
		DeliveryChannelEnumSms,
		DeliveryChannelEnumPush,
		DeliveryChannelEnumInApp:
		return true
	}
	return false
}

func AllDeliveryChannelEnumValues() []DeliveryChannelEnum {
	return []DeliveryChannelEnum{
		DeliveryChannelEnumEmail,
		DeliveryChannelEnumSms,
		DeliveryChannelEnumPush,
		DeliveryChannelEnumInApp,
	}
}

// Job lifecycle states. Terminal: succeeded, failed, dead, cancelled.
//
//	Add values with ALTER TYPE … ADD VALUE; never remove a value referenced by existing rows.
type JobStatusEnum string

const (
	JobStatusEnumPending   JobStatusEnum = "pending"
	JobStatusEnumRunning   JobStatusEnum = "running"
	JobStatusEnumSucceeded JobStatusEnum = "succeeded"
	JobStatusEnumFailed    JobStatusEnum = "failed"
	JobStatusEnumCancelled JobStatusEnum = "cancelled"
	JobStatusEnumDead      JobStatusEnum = "dead"
)

func (e *JobStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatusEnum(s)
	case string:
		*e = JobStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatusEnum: %T", src)
	}
	return nil
}

type NullJobStatusEnum struct {
	JobStatusEnum JobStatusEnum `json:"job_status_enum"`
	Valid         bool          `json:"valid"` // Valid is true if JobStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatusEnum), nil
}

func (e JobStatusEnum) Valid() bool {
	switch e {
	case JobStatusEnumPending,
		JobStatusEnumRunning,
		JobStatusEnumSucceeded,
		JobStatusEnumFailed,
		JobStatusEnumCancelled,
		JobStatusEnumDead:
		return true
	}
	return false
}

func AllJobStatusEnumValues() []JobStatusEnum {
	return []JobStatusEnum{
		JobStatusEnumPending,
		JobStatusEnumRunning,
		JobStatusEnumSucceeded,
		JobStatusEnumFailed,
		JobStatusEnumCancelled,
		JobStatusEnumDead,
	}
}

// Events that produce a notification row in request_notifications.
type NotificationTypeEnum string

const (
	NotificationTypeEnumRequestCreated   NotificationTypeEnum = "request_created"
	NotificationTypeEnumRequestApproved  NotificationTypeEnum = "request_approved"
	NotificationTypeEnumRequestRejected  NotificationTypeEnum = "request_rejected"
	NotificationTypeEnumRequestExecuted  NotificationTypeEnum = "request_executed"
	NotificationTypeEnumRequestFailed    NotificationTypeEnum = "request_failed"
	NotificationTypeEnumRequestCancelled NotificationTypeEnum = "request_cancelled"
)

func (e *NotificationTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationTypeEnum(s)
	case string:
		*e = NotificationTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationTypeEnum: %T", src)
	}
	return nil
}

type NullNotificationTypeEnum struct {
	NotificationTypeEnum NotificationTypeEnum `json:"notification_type_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if NotificationTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationTypeEnum), nil
}

func (e NotificationTypeEnum) Valid() bool {
	switch e {
	case NotificationTypeEnumRequestCreated,
		NotificationTypeEnumRequestApproved,
		NotificationTypeEnumRequestRejected,
		NotificationTypeEnumRequestExecuted,
		NotificationTypeEnumRequestFailed,
		NotificationTypeEnumRequestCancelled:
		return true
	}
	return false
}

func AllNotificationTypeEnumValues() []NotificationTypeEnum {
	return []NotificationTypeEnum{
		NotificationTypeEnumRequestCreated,
		NotificationTypeEnumRequestApproved,
		NotificationTypeEnumRequestRejected,
		NotificationTypeEnumRequestExecuted,
		NotificationTypeEnumRequestFailed,
		NotificationTypeEnumRequestCancelled,
	}
}

// Discriminator for one_time_tokens. Add values with ALTER TYPE … ADD VALUE.
type OneTimeTokenType string

const (
	OneTimeTokenTypeEmailVerification  OneTimeTokenType = "email_verification"
	OneTimeTokenTypePasswordReset      OneTimeTokenType = "password_reset"
	OneTimeTokenTypeMagicLink          OneTimeTokenType = "magic_link"
	OneTimeTokenTypeAccountUnlock      OneTimeTokenType = "account_unlock"
	OneTimeTokenTypeEmailChangeVerify  OneTimeTokenType = "email_change_verify"
	OneTimeTokenTypeEmailChangeConfirm OneTimeTokenType = "email_change_confirm"
	OneTimeTokenTypeAccountDeletion    OneTimeTokenType = "account_deletion"
)

func (e *OneTimeTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OneTimeTokenType(s)
	case string:
		*e = OneTimeTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for OneTimeTokenType: %T", src)
	}
	return nil
}

type NullOneTimeTokenType struct {
	OneTimeTokenType OneTimeTokenType `json:"one_time_token_type"`
	Valid            bool             `json:"valid"` // Valid is true if OneTimeTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOneTimeTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.OneTimeTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OneTimeTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOneTimeTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OneTimeTokenType), nil
}

func (e OneTimeTokenType) Valid() bool {
	switch e {
	case OneTimeTokenTypeEmailVerification,
		OneTimeTokenTypePasswordReset,
		OneTimeTokenTypeMagicLink,
		OneTimeTokenTypeAccountUnlock,
		OneTimeTokenTypeEmailChangeVerify,
		OneTimeTokenTypeEmailChangeConfirm,
		OneTimeTokenTypeAccountDeletion:
		return true
	}
	return false
}

func AllOneTimeTokenTypeValues() []OneTimeTokenType {
	return []OneTimeTokenType{
		OneTimeTokenTypeEmailVerification,
		OneTimeTokenTypePasswordReset,
		OneTimeTokenTypeMagicLink,
		OneTimeTokenTypeAccountUnlock,
		OneTimeTokenTypeEmailChangeVerify,
		OneTimeTokenTypeEmailChangeConfirm,
		OneTimeTokenTypeAccountDeletion,
	}
}

// How a role or direct grant surfaces a permission at runtime. Middleware acts on this value.
type PermissionAccessType string

const (
	PermissionAccessTypeDirect      PermissionAccessType = "direct"
	PermissionAccessTypeConditional PermissionAccessType = "conditional"
	PermissionAccessTypeRequest     PermissionAccessType = "request"
	PermissionAccessTypeDenied      PermissionAccessType = "denied"
)

func (e *PermissionAccessType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionAccessType(s)
	case string:
		*e = PermissionAccessType(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionAccessType: %T", src)
	}
	return nil
}

type NullPermissionAccessType struct {
	PermissionAccessType PermissionAccessType `json:"permission_access_type"`
	Valid                bool                 `json:"valid"` // Valid is true if PermissionAccessType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionAccessType) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionAccessType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionAccessType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionAccessType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionAccessType), nil
}

func (e PermissionAccessType) Valid() bool {
	switch e {
	case PermissionAccessTypeDirect,
		PermissionAccessTypeConditional,
		PermissionAccessTypeRequest,
		PermissionAccessTypeDenied:
		return true
	}
	return false
}

func AllPermissionAccessTypeValues() []PermissionAccessType {
	return []PermissionAccessType{
		PermissionAccessTypeDirect,
		PermissionAccessTypeConditional,
		PermissionAccessTypeRequest,
		PermissionAccessTypeDenied,
	}
}

// Resource visibility injected into context by Require middleware for downstream query scoping.
type PermissionScope string

const (
	PermissionScopeOwn PermissionScope = "own"
	PermissionScopeAll PermissionScope = "all"
)

func (e *PermissionScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionScope(s)
	case string:
		*e = PermissionScope(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionScope: %T", src)
	}
	return nil
}

type NullPermissionScope struct {
	PermissionScope PermissionScope `json:"permission_scope"`
	Valid           bool            `json:"valid"` // Valid is true if PermissionScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionScope) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionScope), nil
}

func (e PermissionScope) Valid() bool {
	switch e {
	case PermissionScopeOwn,
		PermissionScopeAll:
		return true
	}
	return false
}

func AllPermissionScopeValues() []PermissionScope {
	return []PermissionScope{
		PermissionScopeOwn,
		PermissionScopeAll,
	}
}

// Declares which scope values are valid when creating a grant for this permission. 'none' = scope field is not meaningful; 'any' = caller chooses own or all.
type PermissionScopePolicy string

const (
	PermissionScopePolicyNone PermissionScopePolicy = "none"
	PermissionScopePolicyOwn  PermissionScopePolicy = "own"
	PermissionScopePolicyAll  PermissionScopePolicy = "all"
	PermissionScopePolicyAny  PermissionScopePolicy = "any"
)

func (e *PermissionScopePolicy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionScopePolicy(s)
	case string:
		*e = PermissionScopePolicy(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionScopePolicy: %T", src)
	}
	return nil
}

type NullPermissionScopePolicy struct {
	PermissionScopePolicy PermissionScopePolicy `json:"permission_scope_policy"`
	Valid                 bool                  `json:"valid"` // Valid is true if PermissionScopePolicy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionScopePolicy) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionScopePolicy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionScopePolicy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionScopePolicy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionScopePolicy), nil
}

func (e PermissionScopePolicy) Valid() bool {
	switch e {
	case PermissionScopePolicyNone,
		PermissionScopePolicyOwn,
		PermissionScopePolicyAll,
		PermissionScopePolicyAny:
		return true
	}
	return false
}

func AllPermissionScopePolicyValues() []PermissionScopePolicy {
	return []PermissionScopePolicy{
		PermissionScopePolicyNone,
		PermissionScopePolicyOwn,
		PermissionScopePolicyAll,
		PermissionScopePolicyAny,
	}
}

// Request lifecycle states. Terminal: rejected, cancelled, completed, failed.
type RequestStatusEnum string

const (
	RequestStatusEnumPending   RequestStatusEnum = "pending"
	RequestStatusEnumApproved  RequestStatusEnum = "approved"
	RequestStatusEnumRejected  RequestStatusEnum = "rejected"
	RequestStatusEnumCancelled RequestStatusEnum = "cancelled"
	RequestStatusEnumExecuting RequestStatusEnum = "executing"
	RequestStatusEnumCompleted RequestStatusEnum = "completed"
	RequestStatusEnumFailed    RequestStatusEnum = "failed"
)

func (e *RequestStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatusEnum(s)
	case string:
		*e = RequestStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatusEnum: %T", src)
	}
	return nil
}

type NullRequestStatusEnum struct {
	RequestStatusEnum RequestStatusEnum `json:"request_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if RequestStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatusEnum), nil
}

func (e RequestStatusEnum) Valid() bool {
	switch e {
	case RequestStatusEnumPending,
		RequestStatusEnumApproved,
		RequestStatusEnumRejected,
		RequestStatusEnumCancelled,
		RequestStatusEnumExecuting,
		RequestStatusEnumCompleted,
		RequestStatusEnumFailed:
		return true
	}
	return false
}

func AllRequestStatusEnumValues() []RequestStatusEnum {
	return []RequestStatusEnum{
		RequestStatusEnumPending,
		RequestStatusEnumApproved,
		RequestStatusEnumRejected,
		RequestStatusEnumCancelled,
		RequestStatusEnumExecuting,
		RequestStatusEnumCompleted,
		RequestStatusEnumFailed,
	}
}

// SLA breach categories. Extend with ALTER TYPE … ADD VALUE.
type SlaViolationTypeEnum string

const (
	SlaViolationTypeEnumPendingTimeout   SlaViolationTypeEnum = "pending_timeout"
	SlaViolationTypeEnumExecutionTimeout SlaViolationTypeEnum = "execution_timeout"
)

func (e *SlaViolationTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SlaViolationTypeEnum(s)
	case string:
		*e = SlaViolationTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SlaViolationTypeEnum: %T", src)
	}
	return nil
}

type NullSlaViolationTypeEnum struct {
	SlaViolationTypeEnum SlaViolationTypeEnum `json:"sla_violation_type_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if SlaViolationTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSlaViolationTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SlaViolationTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SlaViolationTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSlaViolationTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SlaViolationTypeEnum), nil
}

func (e SlaViolationTypeEnum) Valid() bool {
	switch e {
	case SlaViolationTypeEnumPendingTimeout,
		SlaViolationTypeEnumExecutionTimeout:
		return true
	}
	return false
}

func AllSlaViolationTypeEnumValues() []SlaViolationTypeEnum {
	return []SlaViolationTypeEnum{
		SlaViolationTypeEnumPendingTimeout,
		SlaViolationTypeEnumExecutionTimeout,
	}
}

// Dispatcher instance states. offline = heartbeat TTL expired.
//
//	Add values with ALTER TYPE … ADD VALUE.
type WorkerStatusEnum string

const (
	WorkerStatusEnumIdle     WorkerStatusEnum = "idle"
	WorkerStatusEnumBusy     WorkerStatusEnum = "busy"
	WorkerStatusEnumDraining WorkerStatusEnum = "draining"
	WorkerStatusEnumOffline  WorkerStatusEnum = "offline"
)

func (e *WorkerStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkerStatusEnum(s)
	case string:
		*e = WorkerStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkerStatusEnum: %T", src)
	}
	return nil
}

type NullWorkerStatusEnum struct {
	WorkerStatusEnum WorkerStatusEnum `json:"worker_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if WorkerStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkerStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.WorkerStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkerStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkerStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkerStatusEnum), nil
}

func (e WorkerStatusEnum) Valid() bool {
	switch e {
	case WorkerStatusEnumIdle,
		WorkerStatusEnumBusy,
		WorkerStatusEnumDraining,
		WorkerStatusEnumOffline:
		return true
	}
	return false
}

func AllWorkerStatusEnumValues() []WorkerStatusEnum {
	return []WorkerStatusEnum{
		WorkerStatusEnumIdle,
		WorkerStatusEnumBusy,
		WorkerStatusEnumDraining,
		WorkerStatusEnumOffline,
	}
}

// Permanent record of hard-purged accounts. user_id has no FK constraint because the users row is deleted before this record is written.
type AccountPurgeLog struct {
	ID       uuid.UUID          `db:"id" json:"id"`
	UserID   pgtype.UUID        `db:"user_id" json:"user_id"`
	PurgedAt pgtype.Timestamptz `db:"purged_at" json:"purged_at"`
	// JSONB audit payload. Expected keys: purged_by (UUID of acting admin or system job),
	//  reason (string), anonymized_email (one-way hash of purged email for re-registration dedup).
	//  Minimum required: {"deleted_at": "<RFC3339>"}.
	Metadata []byte `db:"metadata" json:"metadata"`
}

// Pre-filtered view of non-deleted users. Use this in all application read paths
//
//	to avoid accidentally returning soft-deleted accounts.
//	Queries with grace-period or special logic (GetUserForLogin, GetUserForDeletion)
//	must use the base table directly with their own filter.
type ActiveUser struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Email         pgtype.Text        `db:"email" json:"email"`
	Username      pgtype.Text        `db:"username" json:"username"`
	DisplayName   pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarURL     pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at" json:"updated_at"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	DeletedAt     *time.Time         `db:"deleted_at" json:"deleted_at"`
}

// Security event log. user_id is NULLed (not deleted) when the owning user is purged,
//
//	preserving the audit trail post-deletion.
//	Retention: rows older than 90 days are swept by the retention job.
//	Sweep uses idx_aal_cleanup (ASC) for efficient range deletion.
//	trg_deny_audit_update enforces immutability — existing rows may not be edited.
type AuthAuditLog struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	EventType string           `db:"event_type" json:"event_type"`
	Provider  NullAuthProvider `db:"provider" json:"provider"`
	IpAddress *netip.Addr      `db:"ip_address" json:"ip_address"`
	UserAgent pgtype.Text      `db:"user_agent" json:"user_agent"`
	Metadata  []byte           `db:"metadata" json:"metadata"`
	CreatedAt time.Time        `db:"created_at" json:"created_at"`
}

// Persistent job queue. Workers claim rows using SELECT FOR UPDATE SKIP LOCKED.
//
//	Status flow: pending → running → succeeded | failed | dead | cancelled.
//	Failed jobs with attempt < max_attempts are retried via run_after update (no goroutine sleep).
//	Claim query uses effective_priority = priority + LEAST(minutes_waited, 50) to prevent
//	low-priority job starvation under sustained high load.
type Job struct {
	ID      uuid.UUID     `db:"id" json:"id"`
	Kind    string        `db:"kind" json:"kind"`
	Payload []byte        `db:"payload" json:"payload"`
	Status  JobStatusEnum `db:"status" json:"status"`
	// Base priority -100 to 100. Effective priority at claim time adds up to +50 points based on
	//  how long the job has been waiting (1 point per minute, configurable via ManagerConfig).
	Priority    int32 `db:"priority" json:"priority"`
	Attempt     int32 `db:"attempt" json:"attempt"`
	MaxAttempts int32 `db:"max_attempts" json:"max_attempts"`
	// Worker will not claim this job before this timestamp. Used for retry backoff and deferred scheduling.
	RunAfter pgtype.Timestamptz `db:"run_after" json:"run_after"`
	// If a running job exceeds this many seconds, StallDetector resets it to pending.
	TimeoutSeconds int32 `db:"timeout_seconds" json:"timeout_seconds"`
	// Routes this job to the named worker pool. Default = 'default'. Workers poll only their assigned queue(s). Use dedicated queues for priority isolation (e.g. 'critical', 'bulk') or tenant separation.
	QueueName string `db:"queue_name" json:"queue_name"`
	// Advisory reference to workers.id. No FK is enforced because workers is defined after jobs. May be stale after worker cleanup.
	WorkerID  pgtype.UUID `db:"worker_id" json:"worker_id"`
	CreatedBy pgtype.UUID `db:"created_by" json:"created_by"`
	// Optional caller-supplied dedup key. INSERT ... ON CONFLICT DO NOTHING returns the existing row. uniqueness is enforced by partial index uq_jobs_idempotency_key on active rows only, so the same key may be reused after a job reaches a terminal state.
	IdempotencyKey pgtype.Text `db:"idempotency_key" json:"idempotency_key"`
	// JSON output of the handler. NULL until the job transitions to succeeded.
	Result []byte `db:"result" json:"result"`
	// Last error message from a failed attempt. Overwritten on each retry.
	LastError   pgtype.Text        `db:"last_error" json:"last_error"`
	CreatedAt   time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time          `db:"updated_at" json:"updated_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	// Set when attempt = max_attempts and the job transitions to dead. NULL otherwise.
	DeadAt pgtype.Timestamptz `db:"dead_at" json:"dead_at"`
}

// Persistent pause registry for job kinds. Replaces the in-memory pause map —
//
//	survives Dispatcher restarts. A row here means all jobs of that kind are paused.
type JobPausedKind struct {
	Kind string `db:"kind" json:"kind"`
	// User who paused this kind. NULL if the user was subsequently deleted.
	PausedBy pgtype.UUID        `db:"paused_by" json:"paused_by"`
	PausedAt pgtype.Timestamptz `db:"paused_at" json:"paused_at"`
	// Human-readable reason for the pause.
	Reason pgtype.Text `db:"reason" json:"reason"`
}

// DB-stored cron / interval schedule definitions. ScheduleWatcher polls every 10s,
//
//	inserts job rows for due entries, and updates next_run_at. Zero goroutines per schedule.
//	Multi-instance safe via FOR UPDATE SKIP LOCKED on the due-schedule query.
//	next_run_at computed by robfig/cron parser for cron_expression, or NOW() + interval_seconds.
type JobSchedule struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Kind            string      `db:"kind" json:"kind"`
	QueueName       string      `db:"queue_name" json:"queue_name"`
	CronExpression  pgtype.Text `db:"cron_expression" json:"cron_expression"`
	IntervalSeconds pgtype.Int4 `db:"interval_seconds" json:"interval_seconds"`
	PayloadTemplate []byte      `db:"payload_template" json:"payload_template"`
	Priority        int32       `db:"priority" json:"priority"`
	MaxAttempts     int32       `db:"max_attempts" json:"max_attempts"`
	TimeoutSeconds  int32       `db:"timeout_seconds" json:"timeout_seconds"`
	// TRUE = do not enqueue a new job if a job of this kind is already pending or running. Prevents job pile-up when a schedule fires faster than jobs complete.
	SkipIfRunning bool `db:"skip_if_running" json:"skip_if_running"`
	IsActive      bool `db:"is_active" json:"is_active"`
	// Timestamp of the last successful job enqueue for this schedule. NULL until first enqueue.
	LastEnqueuedAt pgtype.Timestamptz `db:"last_enqueued_at" json:"last_enqueued_at"`
	// Next scheduled execution time. Computed by ScheduleWatcher after each successful enqueue. NULL until the first poll after the schedule is created.
	NextRunAt pgtype.Timestamptz `db:"next_run_at" json:"next_run_at"`
	// Last error encountered during schedule processing (cron parse failure, enqueue error, etc.). NULL when the most recent poll succeeded. Used for ops alerting and debugging.
	LastScheduleError pgtype.Text `db:"last_schedule_error" json:"last_schedule_error"`
	CreatedBy         pgtype.UUID `db:"created_by" json:"created_by"`
	CreatedAt         time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time   `db:"updated_at" json:"updated_at"`
}

// Single-table token store for email_verification, password_reset, magic_link, account_unlock, email_change_verify, and email_change_confirm flows.
type OneTimeToken struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	TokenType OneTimeTokenType `db:"token_type" json:"token_type"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	Email     string           `db:"email" json:"email"`
	TokenHash pgtype.Text      `db:"token_hash" json:"token_hash"`
	CodeHash  pgtype.Text      `db:"code_hash" json:"code_hash"`
	// Auxiliary payload keyed by token_type. email_change_verify stores {"new_email": "..."} so the confirm step can retrieve the destination address without a separate KV lookup.
	Metadata []byte `db:"metadata" json:"metadata"`
	Attempts int16  `db:"attempts" json:"attempts"`
	// 0 = no attempt limit (non-OTP types). OTP types use 3.
	MaxAttempts int16 `db:"max_attempts" json:"max_attempts"`
	// Timestamp of the last failed OTP attempt.
	LastAttemptAt pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	RedirectTo    pgtype.Text        `db:"redirect_to" json:"redirect_to"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt        pgtype.Timestamptz `db:"used_at" json:"used_at"`
	IpAddress     *netip.Addr        `db:"ip_address" json:"ip_address"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at" json:"updated_at"`
}

// Permission definitions. Canonical form: resource_type:name (e.g. product:create). Soft-delete via is_active.
type Permission struct {
	ID uuid.UUID `db:"id" json:"id"`
	// Action verb: create, read, update, delete, approve, export, etc.
	Name string `db:"name" json:"name"`
	// Resource domain: product, request, vendor_payout, analytics, etc.
	ResourceType string      `db:"resource_type" json:"resource_type"`
	Description  pgtype.Text `db:"description" json:"description"`
	// Generated: resource_type || ':' || name. Used for fast canonical-name lookups.
	CanonicalName    pgtype.Text           `db:"canonical_name" json:"canonical_name"`
	IsActive         bool                  `db:"is_active" json:"is_active"`
	ScopePolicy      PermissionScopePolicy `db:"scope_policy" json:"scope_policy"`
	AllowConditional bool                  `db:"allow_conditional" json:"allow_conditional"`
	AllowRequest     bool                  `db:"allow_request" json:"allow_request"`
	CreatedAt        time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time             `db:"updated_at" json:"updated_at"`
}

// Per-permission rules defining valid ABAC conditions on grants. Structural checks enforced by DB trigger; value validation in app layer.
type PermissionConditionTemplate struct {
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	// Keys that MUST be present in conditions on any grant for this permission.
	RequiredConditions []byte `db:"required_conditions" json:"required_conditions"`
	// Keys that MUST NOT appear in conditions — prevents known privilege escalation paths.
	ForbiddenConditions []byte `db:"forbidden_conditions" json:"forbidden_conditions"`
	// Per-key type/range/enum constraints. Evaluated in the app layer; adding new rule types requires no DB migration.
	ValidationRules []byte    `db:"validation_rules" json:"validation_rules"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}

// Groups permissions for UI organisation and bulk role assignment. A permission may belong to multiple groups.
type PermissionGroup struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Description  pgtype.Text `db:"description" json:"description"`
	DisplayLabel pgtype.Text `db:"display_label" json:"display_label"`
	Icon         pgtype.Text `db:"icon" json:"icon"`
	// Hex colour for UI badges. Must be #RRGGBB — enforced by chk_pg_color_hex_format.
	ColorHex     pgtype.Text `db:"color_hex" json:"color_hex"`
	DisplayOrder int32       `db:"display_order" json:"display_order"`
	// FALSE = hidden from non-admin interfaces (e.g. internal or system-only groups).
	IsVisible bool      `db:"is_visible" json:"is_visible"`
	IsActive  bool      `db:"is_active" json:"is_active"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

// Many-to-many join between permission_groups and permissions. CASCADE DELETE on both sides.
type PermissionGroupMember struct {
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
}

// Defines which roles must approve a permission-action request when access_type = 'request'. Feeds request_required_approvers at runtime.
type PermissionRequestApprover struct {
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	// Hierarchical level: 0 = first approver tier, 1 = second, etc.
	ApprovalLevel int32 `db:"approval_level" json:"approval_level"`
	// Minimum number of approvals needed from this role at this level.
	MinRequired int32     `db:"min_required" json:"min_required"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

// Immutable audit log for permission_request_approvers. Every mutation is tracked because
//
//	changes to approval chains are high-risk RBAC events. changed_by is nullable:
//	SET NULL when the actor is hard-purged to preserve audit row integrity.
type PermissionRequestApproversAudit struct {
	ID                    uuid.UUID           `db:"id" json:"id"`
	PermissionID          pgtype.UUID         `db:"permission_id" json:"permission_id"`
	RoleID                pgtype.UUID         `db:"role_id" json:"role_id"`
	ApprovalLevel         pgtype.Int4         `db:"approval_level" json:"approval_level"`
	MinRequired           pgtype.Int4         `db:"min_required" json:"min_required"`
	PreviousApprovalLevel pgtype.Int4         `db:"previous_approval_level" json:"previous_approval_level"`
	PreviousMinRequired   pgtype.Int4         `db:"previous_min_required" json:"previous_min_required"`
	ChangeType            AuditChangeTypeEnum `db:"change_type" json:"change_type"`
	ChangedBy             pgtype.UUID         `db:"changed_by" json:"changed_by"`
	ChangedAt             pgtype.Timestamptz  `db:"changed_at" json:"changed_at"`
	ChangeReason          pgtype.Text         `db:"change_reason" json:"change_reason"`
}

// Server-side refresh token ledger with individual revocation and family-based reuse detection (RFC 6819 §5.2.2.3).
type RefreshToken struct {
	Jti       pgtype.UUID `db:"jti" json:"jti"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	SessionID pgtype.UUID `db:"session_id" json:"session_id"`
	// UUID shared by all tokens in a rotation chain. Used by fn_revoke_token_family to cascade revocation on reuse detection (RFC 6819 §5.2.2.3).
	FamilyID pgtype.UUID `db:"family_id" json:"family_id"`
	// jti of the token this one was rotated from. NULL for the first token in a rotation family.
	ParentJti pgtype.UUID        `db:"parent_jti" json:"parent_jti"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	// Max 256 chars. Known values: logout, rotated, reuse_detected, pre_verification, session_revoked, session_expired, password_changed, forced_logout, family_revoked:<reason>.
	RevokeReason pgtype.Text `db:"revoke_reason" json:"revoke_reason"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time   `db:"updated_at" json:"updated_at"`
}

// Approval requests with flexible JSONB payloads and quorum support.
type Request struct {
	ID uuid.UUID `db:"id" json:"id"`
	// Discriminator: product_creation, vendor_withdrawal, permission_action, etc. FK to request_type_schemas ensures a schema row exists before requests of this type can be inserted.
	RequestType string            `db:"request_type" json:"request_type"`
	RequesterID pgtype.UUID       `db:"requester_id" json:"requester_id"`
	Status      RequestStatusEnum `db:"status" json:"status"`
	// Flexible payload. Structure validated against request_type_schemas.
	RequestData []byte `db:"request_data" json:"request_data"`
	// Higher = more urgent. Used to order the approval queue.
	Priority int32 `db:"priority" json:"priority"`
	// Number of approvals needed before the request transitions to approved. Single source of truth; request_required_approvers.min_required is per-role.
	ApprovalsRequired int32 `db:"approvals_required" json:"approvals_required"`
	// Auto-reject if still pending past this time.
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt time.Time          `db:"updated_at" json:"updated_at"`
	// Timestamp when the request entered a terminal state (rejected, cancelled, completed, failed).
	//  NULL while still in-flight. Set by the application layer on status transition.
	ResolvedAt pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
}

// Immutable audit trail of approval/rejection actions. RESTRICT FK prevents hard-deleting a request while approvals exist.
type RequestApproval struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	RequestID  pgtype.UUID `db:"request_id" json:"request_id"`
	ApproverID pgtype.UUID `db:"approver_id" json:"approver_id"`
	// Role that authorised this approval. RESTRICT preserves the reference even if the role is soft-deleted.
	RoleUsed   pgtype.UUID        `db:"role_used" json:"role_used"`
	Action     ApprovalActionEnum `db:"action" json:"action"`
	Comment    pgtype.Text        `db:"comment" json:"comment"`
	ApprovedAt pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
}

// Notification queue for request status changes with per-channel delivery tracking. One row per event per delivery channel — delivery_channel is NOT NULL.
type RequestNotification struct {
	ID               uuid.UUID            `db:"id" json:"id"`
	RequestID        pgtype.UUID          `db:"request_id" json:"request_id"`
	UserID           pgtype.UUID          `db:"user_id" json:"user_id"`
	NotificationType NotificationTypeEnum `db:"notification_type" json:"notification_type"`
	DeliveryChannel  DeliveryChannelEnum  `db:"delivery_channel" json:"delivery_channel"`
	// NULL = queued, non-NULL = delivered.
	SentAt pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	// NULL = unread. Set when the user views the notification.
	ReadAt    pgtype.Timestamptz `db:"read_at" json:"read_at"`
	Title     pgtype.Text        `db:"title" json:"title"`
	Message   pgtype.Text        `db:"message" json:"message"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
}

// Per-user, per-type sliding window counters for request creation rate limiting. Stale rows (window_start older than window duration) should be cleaned up periodically.
type RequestRateLimit struct {
	UserID               pgtype.UUID `db:"user_id" json:"user_id"`
	RequestType          string      `db:"request_type" json:"request_type"`
	RequestsCreatedCount int32       `db:"requests_created_count" json:"requests_created_count"`
	// Start of the current rate-limit window. Reset when the window expires.
	WindowStart   pgtype.Timestamptz `db:"window_start" json:"window_start"`
	LastRequestAt pgtype.Timestamptz `db:"last_request_at" json:"last_request_at"`
}

// Which roles can approve each request, with multi-level hierarchy support.
type RequestRequiredApprover struct {
	RequestID pgtype.UUID `db:"request_id" json:"request_id"`
	RoleID    pgtype.UUID `db:"role_id" json:"role_id"`
	// Hierarchical level: 0 = first, 1 = second, etc.
	ApprovalLevel int32 `db:"approval_level" json:"approval_level"`
	MinRequired   int32 `db:"min_required" json:"min_required"`
	// TRUE = all lower levels must be satisfied before this level can act.
	MustCompletePreviousLevel bool `db:"must_complete_previous_level" json:"must_complete_previous_level"`
	// JSONB conditions that must be met for this role to satisfy the approval requirement. Same key vocabulary as role_permissions.conditions.
	Conditions []byte    `db:"conditions" json:"conditions"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

// SLA thresholds per request_type for alerting and violation detection.
type RequestSlaConfig struct {
	RequestType          string `db:"request_type" json:"request_type"`
	PendingMaxHours      int32  `db:"pending_max_hours" json:"pending_max_hours"`
	ExecutionMaxMinutes  int32  `db:"execution_max_minutes" json:"execution_max_minutes"`
	NotifyApproachingSla bool   `db:"notify_approaching_sla" json:"notify_approaching_sla"`
	// Alert is triggered when this percentage of the SLA window has elapsed.
	ApproachingThresholdPercent int32     `db:"approaching_threshold_percent" json:"approaching_threshold_percent"`
	CreatedAt                   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt                   time.Time `db:"updated_at" json:"updated_at"`
}

// Records SLA breaches for monitoring, alerting, and reporting.
type RequestSlaViolation struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	RequestID pgtype.UUID `db:"request_id" json:"request_id"`
	// pending_timeout = request sat in pending too long; execution_timeout = execution took too long.
	ViolationType SlaViolationTypeEnum `db:"violation_type" json:"violation_type"`
	DetectedAt    pgtype.Timestamptz   `db:"detected_at" json:"detected_at"`
	ResolvedAt    pgtype.Timestamptz   `db:"resolved_at" json:"resolved_at"`
	// User who acknowledged or resolved this SLA breach. NULL if resolved by automated process or user was deleted.
	ResolvedBy pgtype.UUID `db:"resolved_by" json:"resolved_by"`
	// TRUE once the on-call alert has been dispatched for this violation. Never reset to FALSE — duplicate notifications are suppressed by this flag.
	Notified  bool      `db:"notified" json:"notified"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

// Immutable audit log of every status transition on a request. Populated by trg_record_request_status_history on requests INSERT/UPDATE. RESTRICT FK prevents hard-deleting a request while status history exists.
type RequestStatusHistory struct {
	ID        uuid.UUID             `db:"id" json:"id"`
	RequestID pgtype.UUID           `db:"request_id" json:"request_id"`
	OldStatus NullRequestStatusEnum `db:"old_status" json:"old_status"`
	NewStatus RequestStatusEnum     `db:"new_status" json:"new_status"`
	// Actor who triggered the transition. Read from rbac.acting_user session variable; falls back to NULL when unset (e.g. automated scheduler transitions).
	ChangedBy pgtype.UUID        `db:"changed_by" json:"changed_by"`
	ChangedAt pgtype.Timestamptz `db:"changed_at" json:"changed_at"`
	Note      pgtype.Text        `db:"note" json:"note"`
}

// JSON Schema validation rules for request_data keyed by request_type.
type RequestTypeSchema struct {
	RequestType string `db:"request_type" json:"request_type"`
	// JSON Schema for this request_type's request_data payload.
	JsonSchema []byte    `db:"json_schema" json:"json_schema"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

// Role definitions (Owner, Admin, Vendor, Customer, etc.). Soft-delete via is_active — hard DELETE is blocked by RESTRICT FKs on audit tables.
type Role struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	// TRUE = built-in role managed by ops; cannot be deleted by end users.
	IsSystemRole bool `db:"is_system_role" json:"is_system_role"`
	// TRUE = unrestricted access. chk_roles_owner_must_be_system requires is_system_role = TRUE simultaneously.
	IsOwnerRole bool      `db:"is_owner_role" json:"is_owner_role"`
	IsActive    bool      `db:"is_active" json:"is_active"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

// Maps roles → permissions with optional ABAC conditions, access_type, and scope. Every grant requires a named accountable human. All mutations logged to role_permissions_audit.
type RolePermission struct {
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	// JSONB object narrowing when the permission applies. Validated against permission_condition_templates in the app layer.
	Conditions []byte `db:"conditions" json:"conditions"`
	// direct=pass, conditional=pass+enforce conditions, request=202 approval flow, denied=403.
	AccessType PermissionAccessType `db:"access_type" json:"access_type"`
	// own=resources user owns, all=any resource of this type.
	Scope PermissionScope `db:"scope" json:"scope"`
	// RESTRICT prevents that user being deleted while the grant exists.
	GrantedBy     pgtype.UUID `db:"granted_by" json:"granted_by"`
	GrantedReason string      `db:"granted_reason" json:"granted_reason"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
}

// Immutable audit log for role_permissions. Populated by trg_audit_role_permissions.
//
//	RESTRICT FKs on role/permission prevent deletion while history exists.
//	changed_by is nullable: SET NULL when actor is hard-purged so audit rows are preserved.
//	Retention: rows older than 90 days swept by retention job using idx_rp_audit_recent (DESC scan).
type RolePermissionsAudit struct {
	ID           uuid.UUID                `db:"id" json:"id"`
	RoleID       pgtype.UUID              `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID              `db:"permission_id" json:"permission_id"`
	Conditions   []byte                   `db:"conditions" json:"conditions"`
	AccessType   NullPermissionAccessType `db:"access_type" json:"access_type"`
	Scope        NullPermissionScope      `db:"scope" json:"scope"`
	// Snapshot of conditions before the mutation.
	PreviousConditions []byte `db:"previous_conditions" json:"previous_conditions"`
	// Snapshot of access_type before the mutation.
	PreviousAccessType NullPermissionAccessType `db:"previous_access_type" json:"previous_access_type"`
	// Snapshot of scope before the mutation.
	PreviousScope NullPermissionScope `db:"previous_scope" json:"previous_scope"`
	ChangeType    AuditChangeTypeEnum `db:"change_type" json:"change_type"`
	ChangedBy     pgtype.UUID         `db:"changed_by" json:"changed_by"`
	ChangedAt     pgtype.Timestamptz  `db:"changed_at" json:"changed_at"`
	ChangeReason  pgtype.Text         `db:"change_reason" json:"change_reason"`
}

// Core identity record. Sensitive security fields (password_hash, lock state, attempt counters)
//
//	are split into user_secrets so SELECT * on users never returns ciphertext or
//	brute-force counters. trg_require_auth_method enforces at least one auth method per row.
type User struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	Email       pgtype.Text `db:"email" json:"email"`
	Username    pgtype.Text `db:"username" json:"username"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	AvatarURL   pgtype.Text `db:"avatar_url" json:"avatar_url"`
	// FALSE until email verification completes.
	IsActive      bool      `db:"is_active" json:"is_active"`
	EmailVerified bool      `db:"email_verified" json:"email_verified"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
	// Timestamp of the most recent successful login. NULL = never logged in.
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	// Soft-delete timestamp. NULL = active account. Cleared by account recovery.
	//  Hard-purged by background job after 30-day grace period.
	//  Partial unique indexes (idx_users_email_active, idx_users_username_active) enforce
	//  uniqueness for active rows only, allowing re-registration after deletion.
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

// OAuth / external auth identities. One row per (provider, external account).
//
//	Encrypted credentials (access_token, refresh_token_provider) are split into
//	user_identity_tokens so SELECT * never returns ciphertext.
type UserIdentity struct {
	ID            uuid.UUID    `db:"id" json:"id"`
	UserID        pgtype.UUID  `db:"user_id" json:"user_id"`
	Provider      AuthProvider `db:"provider" json:"provider"`
	ProviderUid   string       `db:"provider_uid" json:"provider_uid"`
	ProviderEmail pgtype.Text  `db:"provider_email" json:"provider_email"`
	DisplayName   pgtype.Text  `db:"display_name" json:"display_name"`
	AvatarURL     pgtype.Text  `db:"avatar_url" json:"avatar_url"`
	// Raw JSON blob from the provider's userinfo endpoint. Stored for debugging only — do not treat
	//  as authoritative profile data. May be NULL if the provider returned no userinfo.
	RawProfile []byte    `db:"raw_profile" json:"raw_profile"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

// Encrypted OAuth credentials split from user_identities so SELECT * on
//
//	user_identities never returns ciphertext. 1:1 with user_identities.
type UserIdentityToken struct {
	IdentityID pgtype.UUID `db:"identity_id" json:"identity_id"`
	// AES-256-GCM ciphertext with enc: prefix. chk_uit_access_token_encrypted rejects unencrypted values.
	AccessToken pgtype.Text `db:"access_token" json:"access_token"`
	// NULL if the provider does not return an expiry or the token has not been stored yet.
	AccessTokenExpiresAt pgtype.Timestamptz `db:"access_token_expires_at" json:"access_token_expires_at"`
	// AES-256-GCM ciphertext with enc: prefix. NULL if the provider does not issue refresh tokens or the user disconnected.
	RefreshTokenProvider pgtype.Text `db:"refresh_token_provider" json:"refresh_token_provider"`
	CreatedAt            time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time   `db:"updated_at" json:"updated_at"`
}

// Temporary direct permission grants — exceptions to the role model. Revocation = DELETE; history preserved in user_permissions_audit.
//
//	Granter must hold the permission themselves (trg_prevent_privilege_escalation).
//	UNIQUE(user_id, permission_id) enforced by uq_up_one_active_grant_per_user_perm (full index, not partial —
//	NOW() cannot be used in index predicates). Re-granting requires the previous grant to be
//	hard-deleted first; the cleanup job must run regularly to avoid stale-grant 409s.
type UserPermission struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
	// ABAC conditions in the same vocabulary as role_permissions. Validated against permission_condition_templates in the app layer.
	Conditions []byte `db:"conditions" json:"conditions"`
	// Always 'direct' for per-user grants. Enforced by chk_up_access_type_direct.
	//  Direct grants to individual users do not confer grant rights to the grantee.
	AccessType PermissionAccessType `db:"access_type" json:"access_type"`
	// own=resources user owns, all=any resource of this type. Defaults to own (safe default).
	Scope         PermissionScope `db:"scope" json:"scope"`
	GrantedBy     pgtype.UUID     `db:"granted_by" json:"granted_by"`
	GrantedReason string          `db:"granted_reason" json:"granted_reason"`
	// REQUIRED. Bounded by trg_validate_user_permission_expiry: min 5 min, max 90 days from now.
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt time.Time          `db:"updated_at" json:"updated_at"`
}

// Immutable audit log for user_permissions — highest-risk RBAC table; every mutation is tracked unconditionally. Populated by trg_audit_user_permissions.
//
//	changed_by is nullable: SET NULL when actor is hard-purged so audit rows are preserved.
//	Retention: rows older than 90 days swept by retention job using idx_up_audit_recent (DESC scan).
type UserPermissionsAudit struct {
	ID           uuid.UUID           `db:"id" json:"id"`
	UserID       pgtype.UUID         `db:"user_id" json:"user_id"`
	PermissionID pgtype.UUID         `db:"permission_id" json:"permission_id"`
	Conditions   []byte              `db:"conditions" json:"conditions"`
	Scope        NullPermissionScope `db:"scope" json:"scope"`
	// Snapshot of conditions before the mutation.
	PreviousConditions []byte `db:"previous_conditions" json:"previous_conditions"`
	// Snapshot of scope before the mutation.
	PreviousScope     NullPermissionScope `db:"previous_scope" json:"previous_scope"`
	ExpiresAt         pgtype.Timestamptz  `db:"expires_at" json:"expires_at"`
	PreviousExpiresAt pgtype.Timestamptz  `db:"previous_expires_at" json:"previous_expires_at"`
	ChangeType        AuditChangeTypeEnum `db:"change_type" json:"change_type"`
	ChangedBy         pgtype.UUID         `db:"changed_by" json:"changed_by"`
	ChangedAt         pgtype.Timestamptz  `db:"changed_at" json:"changed_at"`
	ChangeReason      pgtype.Text         `db:"change_reason" json:"change_reason"`
}

// Assigns exactly one role per user. user_id PK enforces this at the DB level. Deletion of the last active owner is blocked by trg_prevent_orphaned_owner.
type UserRole struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	RoleID pgtype.UUID `db:"role_id" json:"role_id"`
	// RESTRICT prevents that user being deleted while the assignment exists.
	GrantedBy     pgtype.UUID `db:"granted_by" json:"granted_by"`
	GrantedReason string      `db:"granted_reason" json:"granted_reason"`
	// NULL = permanent. Always filter: (expires_at IS NULL OR expires_at > NOW()).
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt time.Time          `db:"updated_at" json:"updated_at"`
}

// Immutable audit log for user_roles. Populated by trg_audit_user_roles.
//
//	RESTRICT FKs on user/role prevent deletion while history exists.
//	changed_by is nullable: SET NULL when actor is hard-purged so audit rows are preserved.
//	Retention: rows older than 90 days swept by retention job using idx_ur_audit_recent (DESC scan).
type UserRolesAudit struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	RoleID pgtype.UUID `db:"role_id" json:"role_id"`
	// Snapshot of role_id before the change.
	PreviousRoleID    pgtype.UUID         `db:"previous_role_id" json:"previous_role_id"`
	ExpiresAt         pgtype.Timestamptz  `db:"expires_at" json:"expires_at"`
	PreviousExpiresAt pgtype.Timestamptz  `db:"previous_expires_at" json:"previous_expires_at"`
	ChangeType        AuditChangeTypeEnum `db:"change_type" json:"change_type"`
	ChangedBy         pgtype.UUID         `db:"changed_by" json:"changed_by"`
	ChangedAt         pgtype.Timestamptz  `db:"changed_at" json:"changed_at"`
	ChangeReason      pgtype.Text         `db:"change_reason" json:"change_reason"`
}

// Security-sensitive fields for users. 1:1 with users (user_id PK).
//
//	Kept in a separate table so SELECT * on users never accidentally includes
//	password_hash, lock state, or brute-force counters in API responses.
//	Must be created in the same transaction as the parent users row.
type UserSecret struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	// bcrypt hash ($2a/$2b, length 60). NULL for OAuth-only users. Never store plaintext.
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
	// Increment atomically via SQL arithmetic — never read-then-write or concurrent increments will be silently lost.
	FailedLoginAttempts int16 `db:"failed_login_attempts" json:"failed_login_attempts"`
	// Increment atomically via SQL arithmetic — never read-then-write. Reset to 0 after every successful password change.
	FailedChangePasswordAttempts int16 `db:"failed_change_password_attempts" json:"failed_change_password_attempts"`
	// NULL = not locked by failed attempts. Account unlocks automatically on next login when NOW() > this value — no background job required.
	LoginLockedUntil pgtype.Timestamptz `db:"login_locked_until" json:"login_locked_until"`
	// Set by OTP brute-force exhaustion (LockAccount). Cleared by the account-unlock OTP flow or by admin action. Never self-clears.
	IsLocked bool `db:"is_locked" json:"is_locked"`
	// Set and cleared exclusively by admin action (RBAC). The user-facing OTP unlock flow must never touch this field. Independent of is_locked.
	AdminLocked bool `db:"admin_locked" json:"admin_locked"`
	// UUID of the admin who set admin_locked.
	AdminLockedBy pgtype.UUID `db:"admin_locked_by" json:"admin_locked_by"`
	// Human-readable reason for the lock. Required when admin_locked = TRUE.
	AdminLockedReason pgtype.Text `db:"admin_locked_reason" json:"admin_locked_reason"`
	// Timestamp when admin_locked was set.
	AdminLockedAt pgtype.Timestamptz `db:"admin_locked_at" json:"admin_locked_at"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at" json:"updated_at"`
}

// Login sessions for active-device visibility and audit. Not used for token validation.
type UserSession struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	// Provider used to initiate this session. NULL only when the session was created
	//  before provider tracking was added (backfill path). New rows must always supply
	//  a non-NULL value. CreateUserSession enforces this via a non-nullable parameter.
	AuthProvider NullAuthProvider   `db:"auth_provider" json:"auth_provider"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	LastActiveAt pgtype.Timestamptz `db:"last_active_at" json:"last_active_at"`
	EndedAt      pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	UserAgent    pgtype.Text        `db:"user_agent" json:"user_agent"`
	IpAddress    *netip.Addr        `db:"ip_address" json:"ip_address"`
	DeviceName   pgtype.Text        `db:"device_name" json:"device_name"`
	UpdatedAt    time.Time          `db:"updated_at" json:"updated_at"`
}

// One row per running Dispatcher instance. Updated every heartbeat_ttl_seconds/2.
//
//	StallDetector marks rows offline when heartbeat_at + heartbeat_ttl_seconds < NOW().
//	Stalled workers' running jobs are reset to pending.
//	Offline workers older than the retention window should be purged periodically; use idx_workers_stopped.
type Worker struct {
	ID uuid.UUID `db:"id" json:"id"`
	// Hostname of the machine running this Dispatcher instance.
	Host string `db:"host" json:"host"`
	// OS process ID of the Dispatcher. Used for signal delivery and process health checks.
	Pid int32 `db:"pid" json:"pid"`
	// Maximum concurrent job goroutines for this Dispatcher instance.
	Concurrency int32              `db:"concurrency" json:"concurrency"`
	Status      WorkerStatusEnum   `db:"status" json:"status"`
	HeartbeatAt pgtype.Timestamptz `db:"heartbeat_at" json:"heartbeat_at"`
	// Heartbeat interval in seconds. StallDetector marks this worker offline when heartbeat_at + heartbeat_ttl_seconds < NOW().
	HeartbeatTtlSeconds int32              `db:"heartbeat_ttl_seconds" json:"heartbeat_ttl_seconds"`
	StartedAt           pgtype.Timestamptz `db:"started_at" json:"started_at"`
	StoppedAt           pgtype.Timestamptz `db:"stopped_at" json:"stopped_at"`
	// Runtime counter. Resets to 0 on Dispatcher restart.
	JobsSucceeded int32 `db:"jobs_succeeded" json:"jobs_succeeded"`
	// Runtime counter. Resets to 0 on Dispatcher restart.
	JobsFailed int32 `db:"jobs_failed" json:"jobs_failed"`
	// Runtime counter. Resets to 0 on Dispatcher restart.
	JobsDead int32 `db:"jobs_dead" json:"jobs_dead"`
}
