// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_test.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const TestCountGoogleIdentities = `-- name: TestCountGoogleIdentities :one
SELECT COUNT(*) AS count
FROM user_identities
WHERE user_id  = $1::uuid
  AND provider = 'google'
`

// Returns the number of Google identity rows for a user.
// Used in T-37 and T-51 to assert no duplicate rows exist and rows are deleted.
func (q *Queries) TestCountGoogleIdentities(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestCountGoogleIdentities, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestCountTelegramIdentities = `-- name: TestCountTelegramIdentities :one
SELECT COUNT(*) AS count
FROM user_identities
WHERE user_id  = $1::uuid
  AND provider = 'telegram'
`

// Returns the number of telegram identity rows for a user.
// Used in T-S09 to verify DeleteUserIdentity removed the row.
func (q *Queries) TestCountTelegramIdentities(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestCountTelegramIdentities, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestCountUserSessions = `-- name: TestCountUserSessions :one
SELECT COUNT(*) AS count
FROM user_sessions
WHERE user_id = $1::uuid
`

// Returns the total number of session rows for a user (open or closed).
// Used in T-S11 to verify OAuthLoginTx created a session row.
func (q *Queries) TestCountUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestCountUserSessions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestGetGoogleIdentityDisplayName = `-- name: TestGetGoogleIdentityDisplayName :one
SELECT display_name
FROM user_identities
WHERE user_id  = $1::uuid
  AND provider = 'google'
`

// Returns display_name for a user's Google identity row.
// Used in T-37 to verify UpsertUserIdentity updated the correct column.
func (q *Queries) TestGetGoogleIdentityDisplayName(ctx context.Context, userID pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, TestGetGoogleIdentityDisplayName, userID)
	var display_name pgtype.Text
	err := row.Scan(&display_name)
	return display_name, err
}

const TestGetIdentityUserIDByProviderUID = `-- name: TestGetIdentityUserIDByProviderUID :one
SELECT user_id
FROM user_identities
WHERE provider_uid = $1
`

// Returns the user_id linked to a given provider_uid.
// Used in T-38 to verify the identity was linked to the correct seeded user.
func (q *Queries) TestGetIdentityUserIDByProviderUID(ctx context.Context, providerUid string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, TestGetIdentityUserIDByProviderUID, providerUid)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const TestGetLatestAuditLogByUser = `-- name: TestGetLatestAuditLogByUser :one
SELECT event_type, provider::text AS provider
FROM auth_audit_log
WHERE user_id    = $1::uuid
  AND event_type = $2
ORDER BY created_at DESC
LIMIT 1
`

type TestGetLatestAuditLogByUserParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	EventType string      `db:"event_type" json:"event_type"`
}

type TestGetLatestAuditLogByUserRow struct {
	EventType string `db:"event_type" json:"event_type"`
	Provider  string `db:"provider" json:"provider"`
}

// Returns event_type and provider (as text) for the most recent audit_log row
// matching the given user_id and event_type.
// Used in T-S15 to verify InsertAuditLogTx wrote the correct row.
// provider is cast to text so the test can compare against a plain string.
func (q *Queries) TestGetLatestAuditLogByUser(ctx context.Context, arg TestGetLatestAuditLogByUserParams) (TestGetLatestAuditLogByUserRow, error) {
	row := q.db.QueryRow(ctx, TestGetLatestAuditLogByUser, arg.UserID, arg.EventType)
	var i TestGetLatestAuditLogByUserRow
	err := row.Scan(&i.EventType, &i.Provider)
	return i, err
}

const TestGetTelegramIdentityDetails = `-- name: TestGetTelegramIdentityDetails :one
/*
  Test-support queries for the oauth package.

  !! FOR TEST USE ONLY !!
  These queries expose read-only assertions that production code must never
  perform directly. They are generated into the db package alongside production
  queries and restricted to integration test binaries via the
  //go:build integration_test tag added by the sqlc-generate make target.
*/


SELECT display_name, avatar_url
FROM user_identities
WHERE user_id  = $1::uuid
  AND provider = 'telegram'
`

type TestGetTelegramIdentityDetailsRow struct {
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	AvatarURL   pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

// Returns display_name and avatar_url for a user's Telegram identity row.
// Used in T-S08 to verify InsertUserIdentity wrote the correct values.
func (q *Queries) TestGetTelegramIdentityDetails(ctx context.Context, userID pgtype.UUID) (TestGetTelegramIdentityDetailsRow, error) {
	row := q.db.QueryRow(ctx, TestGetTelegramIdentityDetails, userID)
	var i TestGetTelegramIdentityDetailsRow
	err := row.Scan(&i.DisplayName, &i.AvatarURL)
	return i, err
}

const TestGetTelegramIdentityProviderDetails = `-- name: TestGetTelegramIdentityProviderDetails :one
SELECT ui.provider_uid, uit.access_token, ui.provider_email
FROM user_identities ui
LEFT JOIN user_identity_tokens uit ON uit.identity_id = ui.id
WHERE ui.user_id  = $1::uuid
  AND ui.provider = 'telegram'
`

type TestGetTelegramIdentityProviderDetailsRow struct {
	ProviderUid   string      `db:"provider_uid" json:"provider_uid"`
	AccessToken   pgtype.Text `db:"access_token" json:"access_token"`
	ProviderEmail pgtype.Text `db:"provider_email" json:"provider_email"`
}

// Returns the provider-specific fields for a user's Telegram identity row.
// Used in T-S13 to verify that provider_uid is set and access_token /
// provider_email are empty (Telegram does not use them — D-04).
// access_token was moved to user_identity_tokens (001_core.sql schema split);
// LEFT JOIN keeps the result row when no token row exists yet.
func (q *Queries) TestGetTelegramIdentityProviderDetails(ctx context.Context, userID pgtype.UUID) (TestGetTelegramIdentityProviderDetailsRow, error) {
	row := q.db.QueryRow(ctx, TestGetTelegramIdentityProviderDetails, userID)
	var i TestGetTelegramIdentityProviderDetailsRow
	err := row.Scan(&i.ProviderUid, &i.AccessToken, &i.ProviderEmail)
	return i, err
}

const TestGetUserFlags = `-- name: TestGetUserFlags :one
SELECT u.email_verified, us.password_hash, u.is_active, u.email
FROM users u
LEFT JOIN user_secrets us ON us.user_id = u.id
WHERE u.id = $1::uuid
`

type TestGetUserFlagsRow struct {
	EmailVerified bool        `db:"email_verified" json:"email_verified"`
	PasswordHash  pgtype.Text `db:"password_hash" json:"password_hash"`
	IsActive      bool        `db:"is_active" json:"is_active"`
	Email         pgtype.Text `db:"email" json:"email"`
}

// Returns the boolean and nullable columns that OAuth registration must set correctly.
// Used in T-S12 to assert new Telegram users have:
//
//	email_verified = TRUE, is_active = TRUE, password_hash = NULL, email = NULL/empty.
//
// password_hash was moved to user_secrets (001_core.sql schema split); LEFT JOIN
// keeps the result row even when no user_secrets row exists yet.
func (q *Queries) TestGetUserFlags(ctx context.Context, userID pgtype.UUID) (TestGetUserFlagsRow, error) {
	row := q.db.QueryRow(ctx, TestGetUserFlags, userID)
	var i TestGetUserFlagsRow
	err := row.Scan(
		&i.EmailVerified,
		&i.PasswordHash,
		&i.IsActive,
		&i.Email,
	)
	return i, err
}
