// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ON CONFLICT (role_id, permission_id) DO NOTHING: returns 0 when the grant
	// already exists. The service maps 0 rows → ErrGrantAlreadyExists → 409.
	// To update access_type/scope on an existing grant, remove it first then re-add.
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) (int64, error)
	// Inserts or replaces a user's role assignment. ON CONFLICT targets the user_id
	// PRIMARY KEY (one-role-per-user invariant). fn_prevent_owner_role_escalation fires
	// as a DB backstop before each INSERT/UPDATE OF role_id.
	//
	// The bootstrap handler calls this with granted_by = user_id (self-grant; only valid
	// because bootstrap is the chicken-and-egg path before any owner exists).
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) (AssignUserRoleRow, error)
	// Clears deleted_at for a pending-deletion user.
	// Returns rows-affected: 0 means the user was not pending deletion → 409 not_pending_deletion.
	CancelUserDeletion(ctx context.Context, userID pgtype.UUID) (int64, error)
	// ── Email change ───────────────────────────────────────────────────────────
	// Returns true when no active (non-deleted) user holds @new_email.
	// Excludes the calling user (id != @user_id) so a same-address re-request
	// is not rejected here — the same-email guard in the service handles that case.
	// SetUserEmail catches concurrent races via 23505 on idx_users_email_active.
	CheckEmailAvailableForChange(ctx context.Context, arg CheckEmailAvailableForChangeParams) (bool, error)
	// ── Permission check (hot path) ────────────────────────────────────────────
	// Returns the full access context for (user_id, permission) in one round-trip.
	// is_owner short-circuits in Go — all other fields are ignored when is_owner = true.
	//
	// Single-pass rewrite: resolves user_role_ctx and perm_id exactly once each,
	// then derives all output columns from those two materialized CTEs. Eliminates the
	// previous triple traversal of user_roles and the duplicate 4-table join chain.
	//
	// Index usage:
	//   user_role_ctx: user_roles PK (user_id) — at most 1 row
	//   perm_id:       idx_permissions_canonical — O(1) index-only seek
	//   role_grant:    idx_role_perms_covering(role_id, permission_id) INCLUDE(conditions,access_type,scope)
	//   direct_grant:  uq_up_one_active_grant_per_user_perm(user_id, permission_id) — point lookup,
	//                  replaces previous (user_id, expires_at) range scan
	CheckUserAccess(ctx context.Context, arg CheckUserAccessParams) (CheckUserAccessRow, error)
	// ── Username ───────────────────────────────────────────────────────────────────
	// Returns true when no active (non-deleted) row with username = @username exists.
	// Scoped to deleted_at IS NULL (via active_users view) so deleted accounts release
	// their username for re-registration.
	// No FOR UPDATE — point-in-time check; write path enforces uniqueness via
	// idx_users_username_active (23505 on conflict).
	CheckUsernameAvailable(ctx context.Context, username pgtype.Text) (bool, error)
	// queued → constructing: sweep job claims this payout for batch construction.
	// Sets batch_id. Caller MUST assert RowsAffected() == 1.
	// If RowsAffected() == 0 a concurrent worker already claimed it — skip.
	ClaimPayoutForConstruction(ctx context.Context, arg ClaimPayoutForConstructionParams) (int64, error)
	// Clear the sweep hold after admin investigation. Caller is responsible for
	// recording step-up authentication before executing.
	// fn_ops_audit_platform_config trigger writes to ops_audit_log automatically.
	// Returns 0 if the hold was already cleared (idempotent on re-run).
	ClearSweepHold(ctx context.Context, network string) (int64, error)
	// Record the end of an outage. Caller MUST assert RowsAffected() == 1.
	CloseOutageRecord(ctx context.Context, outageID int64) (int64, error)
	// Close an in-progress reconciliation run with its final result and discrepancy.
	CloseReconciliationRunHistory(ctx context.Context, arg CloseReconciliationRunHistoryParams) error
	// Maintenance job (runs every 6 hours): close outage records older than 48 hours.
	// Caps ended_at at started_at + 48h so the formula does not overcount.
	CloseStaleOutages(ctx context.Context) error
	// Marks the token as used. Returns rows-affected: 0 means already consumed.
	ConsumeAccountDeletionToken(ctx context.Context, id pgtype.UUID) (int64, error)
	// Marks an email_change_verify or email_change_confirm token as used.
	// AND used_at IS NULL ensures idempotency — a concurrent correct submission cannot
	// consume the same token twice.
	// Shared by step 2 (consume verify token) and step 3 (consume confirm token).
	ConsumeEmailChangeToken(ctx context.Context, id pgtype.UUID) (int64, error)
	// Marks the token as used. The AND used_at IS NULL guard ensures idempotency:
	// a race between two concurrent correct submissions cannot consume the same token twice.
	ConsumeEmailVerificationToken(ctx context.Context, id pgtype.UUID) (int64, error)
	// Marks the token as used. Returns rows-affected: 0 means already consumed (idempotency).
	ConsumeOwnershipTransferToken(ctx context.Context, id pgtype.UUID) (int64, error)
	// Marks the token as used. AND used_at IS NULL ensures idempotency:
	// a race between two concurrent reset submissions cannot consume the same token twice.
	ConsumePasswordResetToken(ctx context.Context, id pgtype.UUID) (int64, error)
	// Marks an account_unlock token as used. AND used_at IS NULL ensures idempotency:
	// a race between two concurrent correct submissions cannot consume the same token twice.
	ConsumeUnlockToken(ctx context.Context, id pgtype.UUID) (int64, error)
	// ── Bootstrap ───────────────────────────────────────────────────────────────
	// Used by /owner/bootstrap to gate on whether an active owner already exists.
	CountActiveOwners(ctx context.Context) (int64, error)
	// Issues a new account_deletion OTP token. max_attempts = 3. TTL supplied as @ttl_seconds.
	//
	// On 23505 (unique_violation) on idx_ott_account_deletion_active:
	// a deletion token is already active for this user.
	// Store layer maps pgErr.ConstraintName == "idx_ott_account_deletion_active"
	// → ErrDeletionTokenCooldown → handler returns 429.
	CreateAccountDeletionToken(ctx context.Context, arg CreateAccountDeletionTokenParams) (CreateAccountDeletionTokenRow, error)
	// Issues a new email_change_confirm OTP token for step 2.
	// @new_email is stored in the email column so step 3 can retrieve the destination
	// address directly from the token row without a separate query.
	// max_attempts = 5. The DB constraint chk_ott_ecc_ttl_max caps the TTL at 15 minutes.
	CreateEmailChangeConfirmToken(ctx context.Context, arg CreateEmailChangeConfirmTokenParams) (CreateEmailChangeConfirmTokenRow, error)
	// Issues a new email_change_verify OTP token.
	// @email is the user's CURRENT address (for audit readability).
	// @metadata stores {"new_email": "..."} so step 2 can retrieve the destination
	// without a separate KV lookup (stored in one_time_tokens.metadata JSONB).
	// max_attempts = 5. TTL via @ttl_seconds::float8 — same clock pattern as other OTP queries.
	// The DB constraint chk_ott_ecv_ttl_max caps the TTL at 15 minutes.
	CreateEmailChangeVerifyToken(ctx context.Context, arg CreateEmailChangeVerifyTokenParams) (CreateEmailChangeVerifyTokenRow, error)
	// Issues a new email_verification OTP token with a caller-controlled TTL and max 3 attempts.
	// 3 attempts × 1-in-1,000,000 chance per attempt = 0.0003% brute-force success rate per token.
	//
	// TTL is passed as @ttl_seconds (float8) so PostgreSQL computes expires_at = NOW() + ttl,
	// keeping both timestamps on the same clock and preventing chk_ott_ev_ttl_max violations
	// caused by application/DB clock skew.
	// The DB constraint chk_ott_ev_ttl_max caps the TTL at 15 minutes.
	// The authoritative TTL value lives in config.Config.OTPValidMinutes (env: OTP_VALID_MINUTES).
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (CreateEmailVerificationTokenRow, error)
	// Creates a new invoice with a full tier/wallet snapshot baked in at creation.
	// The application MUST resolve every snapshot column as
	//   COALESCE(vendor_tier_overrides.field, btc_tier_config.field)
	// before calling this query. The settlement engine reads ONLY from the snapshot
	// columns — live tier/config changes have zero effect on in-flight invoices.
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	// Inserts the invoice address row immediately after getnewaddress returns.
	// On 23505 (uq_invoice_address_network): duplicate address from the keypool —
	// KeypoolOrRPCError CRITICAL alert. Do NOT retry automatically.
	// On 23505 (uq_invoice_address_per_invoice): invoice already has an address — bug.
	CreateInvoiceAddress(ctx context.Context, arg CreateInvoiceAddressParams) (InvoiceAddress, error)
	// Register an address in the ZMQ watch list.
	// MUST be called AFTER CreateInvoiceAddress commits so the
	// fn_iam_address_consistency trigger can verify the address/network match.
	// After this INSERT commits, call RegisterImmediate() on the ZMQ subscriber.
	// The 5-minute periodic reload is a safety net only — never rely on it for
	// newly created invoices.
	CreateInvoiceAddressMonitoring(ctx context.Context, arg CreateInvoiceAddressMonitoringParams) (CreateInvoiceAddressMonitoringRow, error)
	// Creates a new user account for a first-time OAuth sign-in.
	// Atomically inserts both the users row and its companion user_secrets row (NULL
	// password_hash) using a CTE so trg_require_auth_method (DEFERRABLE INITIALLY
	// DEFERRED) sees both rows. The caller must INSERT into user_identities in the
	// same transaction before commit to satisfy the auth-method requirement.
	// email_verified = TRUE and is_active = TRUE because the provider has already
	// confirmed the email address.
	// avatar_url is seeded from the provider's profile picture so the user's profile
	// shows an avatar immediately without a separate update step.
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (uuid.UUID, error)
	// Issues a new password_reset OTP token with a caller-controlled TTL and max 3 attempts.
	// Caller must call InvalidateAllUserPasswordResetTokens first (within the same transaction).
	// TTL via @ttl_seconds::float8 — same clock pattern as CreateEmailVerificationToken.
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (CreatePasswordResetTokenRow, error)
	// Create a payout record for a settled invoice.
	// Three BEFORE INSERT triggers fire: fn_btc_payout_guard (checks invoice.status
	// = 'settled'), fn_pr_vendor_consistency (checks vendor_id match),
	// fn_pr_destination_consistency (checks destination_address match).
	// UNIQUE (invoice_id) is the race-safe double-payout guard — on 23505
	// roll back and return ErrDuplicatePayout.
	CreatePayoutRecord(ctx context.Context, arg CreatePayoutRecordParams) (PayoutRecord, error)
	// Issues a new root refresh token (no parent_jti) with a 30-day TTL.
	// family_id is generated by the DB DEFAULT (gen_random_uuid()) so each fresh
	// login starts an independent token family with no shared revocation surface.
	// The caller embeds jti in a signed JWT — never expose the raw UUID directly.
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	// is_system_role and is_owner_role are always FALSE for end-user-created roles.
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// Issues a child refresh token linked to the presented (now-revoked) parent_jti.
	// Inherits family_id and session_id from the caller. TTL resets to 30 days from NOW()
	// rather than inheriting the parent's remaining TTL, consistent with initial login issuance.
	CreateRotatedRefreshToken(ctx context.Context, arg CreateRotatedRefreshTokenParams) (CreateRotatedRefreshTokenRow, error)
	// Issues a new account_unlock OTP token. TTL is caller-controlled via @ttl_seconds.
	// expires_at is computed as NOW() + make_interval(secs => ttl_seconds) so both
	// timestamps stay on the same PostgreSQL clock, preventing chk_ott_au_ttl_max
	// violations caused by application/DB clock skew.
	// No token_hash needed — account_unlock tokens use the OTP code path exclusively.
	CreateUnlockToken(ctx context.Context, arg CreateUnlockTokenParams) (CreateUnlockTokenRow, error)
	// ── Registration ────────────────────────────────────────────────────────────
	// Atomically inserts both the users row and its companion user_secrets row
	// using a CTE so trg_require_auth_method (DEFERRABLE INITIALLY DEFERRED) sees
	// both rows before it fires at transaction commit.
	// Returns the minimal fields needed for the registration response.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Opens a new login session row. The returned id is embedded in JWT claims and
	// stored on the refresh_token row so tokens can be tied back to a specific device session.
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (CreateUserSessionRow, error)
	// Credit the vendor's internal balance atomically via btc_credit_balance.
	// Returns the new balance for use in financial_audit_events.balance_after_sat.
	// The caller MUST write the audit event in the same transaction.
	// Raises an exception if no vendor_balances row exists for (vendor_id, network).
	CreditVendorBalance(ctx context.Context, arg CreditVendorBalanceParams) (int64, error)
	// Soft-deletes a non-system role. Zero rows → ErrSystemRoleImmutable → 409.
	DeactivateRole(ctx context.Context, id pgtype.UUID) (int64, error)
	// Debit the vendor's internal balance atomically via btc_debit_balance.
	// Returns the new balance for use in financial_audit_events.balance_after_sat.
	// Raises SQLSTATE 23514 (ErrInsufficientBalance) when balance < amount.
	// Never retry on 23514 — it is a deterministic error.
	DebitVendorBalance(ctx context.Context, arg DebitVendorBalanceParams) (int64, error)
	// Deletes the pending transfer token initiated by @initiated_by.
	// Scoped by metadata->>'initiated_by' so only the initiating owner's transfer is removed.
	// Returns rows-affected: 0 means no pending transfer found → ErrNoPendingTransfer.
	DeletePendingOwnershipTransferToken(ctx context.Context, initiatedBy string) (int64, error)
	// Removes the linked identity for the given (user, provider) pair.
	// Returns rows affected: 0 means the identity did not exist (idempotent).
	// trg_prevent_orphan_on_identity_delete (002_core_functions.sql) will raise an
	// exception if this would leave a password-less user with no remaining identity.
	DeleteUserIdentity(ctx context.Context, arg DeleteUserIdentityParams) (int64, error)
	// Closes every open session for the user.
	// Called in the same transaction as RevokeAllUserRefreshTokens so the token ledger
	// and the session list stay consistent.
	EndAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	// Closes a single session row identified by its id.
	// AND ended_at IS NULL makes the operation idempotent.
	// Called during logout to mark the device's session as explicitly ended.
	// For mass session termination use EndAllUserSessions.
	EndUserSession(ctx context.Context, id pgtype.UUID) error
	// GDPR Article 17: nullify source_ip_hash and set erased = TRUE for all
	// non-erased issuances belonging to the given vendor.
	// chk_sti_erased_coherent constraint enforces source_ip_hash IS NULL when erased.
	EraseSSETokenIssuances(ctx context.Context, vendorID pgtype.UUID) (int64, error)
	// Fetches the active account_deletion token for the given user.
	// FOR UPDATE prevents concurrent double-consumption.
	GetAccountDeletionToken(ctx context.Context, userID pgtype.UUID) (GetAccountDeletionTokenRow, error)
	// ── Background purge worker ──
	// Returns up to 100 user IDs whose 30-day grace period has expired.
	// The worker processes these in a loop, purging each in its own transaction
	// to bound the blast radius of any single failure.
	// Index: idx_users_pending_deletion ON users(deleted_at) WHERE deleted_at IS NOT NULL
	// avoids a full scan of active (deleted_at IS NULL) rows.
	GetAccountsDueForPurge(ctx context.Context) ([]uuid.UUID, error)
	// ZMQ hashtx handler: resolve (address, network) → invoice_id.
	// This is on the critical path of every received Bitcoin transaction.
	// The unique partial index uq_iam_active_address_network guarantees at most
	// one active row per (address, network), so this always returns 0 or 1 rows.
	// Index: idx_iam_active ON invoice_address_monitoring(address, network)
	//        WHERE status = 'active'
	GetActiveMonitoringByAddress(ctx context.Context, arg GetActiveMonitoringByAddressParams) (GetActiveMonitoringByAddressRow, error)
	// ── Sessions ─────────────────────────────────────────────────────────────────
	// Returns all open sessions for the user, most recently active first.
	// Limited to 50 rows — enough for any realistic number of concurrent devices.
	GetActiveSessions(ctx context.Context, userID pgtype.UUID) ([]GetActiveSessionsRow, error)
	// Verifies a target user exists, is active, and has confirmed their email.
	// Used by bootstrap to reject unknown or unverified user_ids.
	GetActiveUserByID(ctx context.Context, userID pgtype.UUID) (GetActiveUserByIDRow, error)
	// Fetch the effective tier override for a vendor if one exists and has not
	// expired. Used at invoice creation to resolve the COALESCE snapshot.
	// NOTE: do NOT use a partial index with NOW() — indexes cannot have STABLE
	// function predicates. This uses a plain index and filters in the query.
	// Index: idx_vto_vendor_network ON vendor_tier_overrides(vendor_id, network)
	GetActiveVendorTierOverride(ctx context.Context, arg GetActiveVendorTierOverrideParams) (VendorTierOverride, error)
	// Return all financial audit events for an invoice, most recent first.
	// Index: idx_fae_invoice ON financial_audit_events(invoice_id, timestamp DESC)
	//        WHERE invoice_id IS NOT NULL
	GetAuditEventsForInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]GetAuditEventsForInvoiceRow, error)
	// Return all financial audit events for a payout record, most recent first.
	// Index: idx_fae_payout ON financial_audit_events(payout_record_id, timestamp DESC)
	//        WHERE payout_record_id IS NOT NULL
	GetAuditEventsForPayout(ctx context.Context, payoutRecordID pgtype.UUID) ([]GetAuditEventsForPayoutRow, error)
	GetBitcoinSyncState(ctx context.Context, network string) (BitcoinSyncState, error)
	// Fetch processed blocks in a height range for reconciliation gap detection.
	// Index: idx_bbh_network_height ON bitcoin_block_history(network, height DESC)
	GetBlockHistoryRange(ctx context.Context, arg GetBlockHistoryRangeParams) ([]BitcoinBlockHistory, error)
	// Settlement worker: return invoices that have reached their required
	// confirmation depth and are ready to settle.
	// Caller pre-computes @max_confirmed_height = current_chain_height - confirmation_depth
	// for each tier; pass the lowest (most conservative) value to get all eligible invoices,
	// then filter per-tier in the application if needed.
	// Index: idx_inv_confirming ON invoices(network, first_confirmed_block_height)
	//        WHERE status = 'confirming'
	GetConfirmingInvoices(ctx context.Context, arg GetConfirmingInvoicesParams) ([]Invoice, error)
	// Mempool-drop watchdog: return all detected invoices for a network so the
	// watchdog can call getmempoolentry on each txid to check if it is still live.
	// Index: idx_inv_detected ON invoices(network, detected_at)
	//        WHERE status = 'detected'
	GetDetectedInvoices(ctx context.Context, network string) ([]GetDetectedInvoicesRow, error)
	// Fetches the active email_change_confirm token for the given authenticated user.
	// The email column holds new_email for use in step 3.
	// FOR UPDATE prevents concurrent double-consumption.
	GetEmailChangeConfirmToken(ctx context.Context, userID pgtype.UUID) (GetEmailChangeConfirmTokenRow, error)
	// Fetches the active email_change_verify token for the given authenticated user.
	// Lookup is by (user_id, token_type) — no email param needed since the user is
	// already authenticated via JWT.
	// Returns metadata so the caller can extract new_email.
	// FOR UPDATE prevents concurrent double-consumption.
	GetEmailChangeVerifyToken(ctx context.Context, userID pgtype.UUID) (GetEmailChangeVerifyTokenRow, error)
	// ── Email verification ───────────────────────────────────────────────────────
	// Looks up by email only — the client sends email + OTP code, no user_id required.
	// ORDER BY created_at DESC, id DESC picks the most recent valid token.
	// FOR UPDATE prevents concurrent double-use (two simultaneous correct submissions).
	GetEmailVerificationToken(ctx context.Context, email string) (GetEmailVerificationTokenRow, error)
	// Expiry cleanup job: return invoices whose unadjusted expires_at has passed.
	// IMPORTANT: this returns a SUPERSET. The job must apply the outage compensation
	// formula (GetOutageOverlapForInvoice) before marking any invoice expired.
	// Never mark an invoice expired based on expires_at alone.
	// Index: idx_inv_expiry_candidates ON invoices(network, expires_at)
	//        WHERE status IN ('pending', 'mempool_dropped')
	GetExpiryCandidates(ctx context.Context, network string) ([]GetExpiryCandidatesRow, error)
	// Held-aging monitor: return held payouts older than the given age threshold.
	// Caller pre-computes @older_than = NOW() - age duration
	// (e.g. NOW() - 7*24h for WARNING, NOW() - 30*24h for CRITICAL).
	// Index: idx_pr_held_aging ON payout_records(network, created_at)
	//        WHERE status = 'held'
	GetHeldAgingPayouts(ctx context.Context, arg GetHeldAgingPayoutsParams) ([]GetHeldAgingPayoutsRow, error)
	// ── OAuth Identity ──
	// Looks up an identity by provider + provider_uid (the external account's stable ID).
	// Used during OAuth callback to determine whether an incoming provider account is
	// already linked to an internal user.
	// access_token is intentionally excluded — it lives in user_identity_tokens and
	// must never be returned in bulk identity lookups (ciphertext in API response risk).
	// Callers that need the token must query user_identity_tokens separately by identity_id.
	GetIdentityByProviderUID(ctx context.Context, arg GetIdentityByProviderUIDParams) (GetIdentityByProviderUIDRow, error)
	// Returns the identity row for a specific (user, provider) pair.
	// Used to check whether a user already has a linked account for a given provider
	// before attempting to link or unlink.
	GetIdentityByUserAndProvider(ctx context.Context, arg GetIdentityByUserAndProviderParams) (GetIdentityByUserAndProviderRow, error)
	// Fetch a single invoice by ID.
	GetInvoice(ctx context.Context, invoiceID pgtype.UUID) (Invoice, error)
	// Fetch the address allocated to an invoice.
	// Uses the unique index created by uq_invoice_address_per_invoice on invoice_id.
	GetInvoiceAddress(ctx context.Context, invoiceID pgtype.UUID) (InvoiceAddress, error)
	// Fetch an invoice with an exclusive row-level lock for settlement or status
	// transitions that require a read-modify-write within a transaction.
	GetInvoiceWithLock(ctx context.Context, invoiceID pgtype.UUID) (Invoice, error)
	// Reorg rollback: return all invoices first-confirmed at the disconnected
	// block height. The settlement engine rolls them back or escalates to
	// reorg_admin_required based on sweep_completed.
	// Index: idx_inv_first_confirmed_height ON invoices(network, first_confirmed_block_height)
	//        WHERE first_confirmed_block_height IS NOT NULL
	GetInvoicesAtBlockHeight(ctx context.Context, arg GetInvoicesAtBlockHeightParams) ([]GetInvoicesAtBlockHeightRow, error)
	// Returns created_at of the most recent active email_change_verify token for this user.
	// Used by the service to enforce a 2-minute cooldown before allowing a new request.
	// Returns pgx.ErrNoRows when no active verify token exists.
	GetLatestEmailChangeVerifyTokenCreatedAt(ctx context.Context, userID pgtype.UUID) (time.Time, error)
	// Invoice creation hot path: fetch the most recent rate for a (network, currency).
	// Index: idx_ber_network_currency_time ON btc_exchange_rate_log(network, fiat_currency, fetched_at DESC)
	GetLatestExchangeRate(ctx context.Context, arg GetLatestExchangeRateParams) (GetLatestExchangeRateRow, error)
	// Returns created_at of the most recent unused email_verification token for this user.
	// Used to enforce the resend cooldown window in the application layer.
	// idx_ott_active covers the filter (user_id, token_type, used_at IS NULL);
	// the ORDER BY created_at DESC sorts a tiny in-memory result set.
	GetLatestVerificationTokenCreatedAt(ctx context.Context, userID pgtype.UUID) (time.Time, error)
	// Wallet recovery Scenario B: keypool cursor advance.
	// Returns MAX(hd_derivation_index) for the given network so the application
	// can compute the next keypool refill target as MAX * 1.2 with a minimum buffer.
	// Index: idx_ia_max_derivation ON invoice_addresses(network, hd_derivation_index DESC)
	// Returns NULL on a fresh deployment before any addresses have been allocated.
	GetMaxHDDerivationIndex(ctx context.Context, network string) (interface{}, error)
	// Hot-path check: "is there an open outage for this network?"
	// Also used on startup to detect outage records left by a crashed process.
	// Index: uq_outage_one_open_per_network (unique partial WHERE ended_at IS NULL)
	GetOpenOutage(ctx context.Context, network string) (GetOpenOutageRow, error)
	// Expiry compensation formula: total outage duration that overlapped with
	// an invoice's life. The expiry cleanup job adds this to expires_at before
	// deciding whether to mark the invoice expired.
	//
	// Overlap = LEAST(outage_end, invoice_expires_at)
	//           - GREATEST(outage_start, invoice_created_at)
	// Summed across all outages that touch the invoice window.
	// Returns INTERVAL '0' when no overlapping outages exist.
	// Index: idx_outage_range ON btc_outage_log(network, started_at, ended_at)
	GetOutageOverlapForInvoice(ctx context.Context, arg GetOutageOverlapForInvoiceParams) (interface{}, error)
	// Looks up the owner role seeded by 001_roles.sql.
	GetOwnerRoleID(ctx context.Context) (uuid.UUID, error)
	// Fetches the most recent active (unused) password_reset token for the email.
	// FOR UPDATE prevents concurrent double-consumption (same pattern as
	// GetEmailVerificationToken and GetUnlockToken).
	GetPasswordResetToken(ctx context.Context, email string) (GetPasswordResetTokenRow, error)
	// ── Forgot / reset password ──────────────────────────────────────────────────
	// Returns created_at of the most recent active (used_at IS NULL) password_reset
	// token for the given email. Used by the service to enforce a 60-second cooldown
	// between reset requests. Returns pgx.ErrNoRows when no active token exists.
	GetPasswordResetTokenCreatedAt(ctx context.Context, email string) (time.Time, error)
	// Returns the token row for OTP validation without locking the row.
	// Used by VerifyResetCode: no FOR UPDATE because the token is not consumed here.
	// The consuming query (GetPasswordResetToken) uses FOR UPDATE separately.
	GetPasswordResetTokenForVerify(ctx context.Context, email string) (GetPasswordResetTokenForVerifyRow, error)
	GetPayoutRecord(ctx context.Context, payoutID pgtype.UUID) (PayoutRecord, error)
	// Fetch the payout for a settled invoice. Uses the implicit unique index
	// created by UNIQUE constraint uq_pr_invoice_id on invoice_id.
	GetPayoutRecordByInvoice(ctx context.Context, invoiceID pgtype.UUID) (PayoutRecord, error)
	// Confirmation handler and RBF: find all payout records sharing a sweep TX.
	// Used to mark all outputs confirmed when the sweep TX gets sufficient depth.
	// Index: idx_pr_batch_txid ON payout_records(batch_txid)
	//        WHERE batch_txid IS NOT NULL
	GetPayoutsByBatchTxid(ctx context.Context, batchTxid pgtype.Text) ([]GetPayoutsByBatchTxidRow, error)
	// Returns the active (unused, unexpired) ownership transfer token.
	// FOR UPDATE prevents concurrent accept/cancel races.
	// Returns pgx.ErrNoRows when no pending transfer exists.
	GetPendingOwnershipTransferToken(ctx context.Context) (GetPendingOwnershipTransferTokenRow, error)
	// Delivery worker poll: return pending deliveries due for attempt.
	// Oldest-due deliveries (next_retry_at ASC NULLS FIRST) are processed first.
	// Index: idx_wd_pending ON webhook_deliveries(next_retry_at)
	//        WHERE status = 'pending'
	GetPendingWebhookDeliveries(ctx context.Context) ([]GetPendingWebhookDeliveriesRow, error)
	GetPermissionByCanonicalName(ctx context.Context, canonicalName pgtype.Text) (GetPermissionByCanonicalNameRow, error)
	// Returns the capability flags for a single permission by primary key.
	// Used by AddRolePermission to validate access_type and scope before inserting.
	GetPermissionByID(ctx context.Context, id pgtype.UUID) (GetPermissionByIDRow, error)
	GetPermissionGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GetPermissionGroupMembersRow, error)
	GetPermissionGroups(ctx context.Context) ([]GetPermissionGroupsRow, error)
	// ── Permissions ─────────────────────────────────────────────────────────────
	GetPermissions(ctx context.Context) ([]GetPermissionsRow, error)
	// Read the operational config for a network. Called by the sweep job to check
	// sweep_hold_mode before constructing any batch, and by the reconciliation job
	// to read reconciliation_start_height and treasury_reserve_satoshis.
	GetPlatformConfig(ctx context.Context, network string) (PlatformConfig, error)
	// Approval workflow: find queued payouts at or above the withdrawal approval
	// threshold, highest value first. The application then checks each against
	// the vendor's tier threshold.
	// Index: idx_pr_queued_net_satoshis ON payout_records(network, net_satoshis DESC)
	//        WHERE status = 'queued'
	GetQueuedPayoutsAboveThreshold(ctx context.Context, arg GetQueuedPayoutsAboveThresholdParams) ([]GetQueuedPayoutsAboveThresholdRow, error)
	// Sweep job: return all queued payouts for a specific vendor on a network,
	// ordered by creation time (oldest first).
	// Index: idx_pr_queued_vendor ON payout_records(network, vendor_id)
	//        WHERE status = 'queued'
	GetQueuedPayoutsForVendor(ctx context.Context, arg GetQueuedPayoutsForVendorParams) ([]GetQueuedPayoutsForVendorRow, error)
	GetReconciliationJobState(ctx context.Context, network string) (ReconciliationJobState, error)
	// ── Refresh token lifecycle ──────────────────────────────────────────────────
	// Fetches a refresh_tokens row by jti (primary key).
	// Used by the /refresh endpoint to validate the presented token before rotation.
	// Returns pgx.ErrNoRows when the jti does not exist in the table.
	GetRefreshTokenByJTI(ctx context.Context, jti pgtype.UUID) (GetRefreshTokenByJTIRow, error)
	GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	// ── Role permissions ────────────────────────────────────────────────────────
	GetRolePermissions(ctx context.Context, roleID pgtype.UUID) ([]GetRolePermissionsRow, error)
	// ── Roles ───────────────────────────────────────────────────────────────────
	GetRoles(ctx context.Context) ([]Role, error)
	// Used by DELETE /sessions/:id to verify the session belongs to the calling user
	// before revoking it.
	GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error)
	// Stuck-sweep watchdog: return payout records stuck in 'constructing' longer
	// than the configured threshold (default 10 min). The watchdog reclaims them
	// back to 'queued' so the sweep job can retry.
	// Caller pre-computes @stale_before = NOW() - threshold duration.
	// Index: idx_pr_stale_constructing ON payout_records(network, updated_at)
	//        WHERE status = 'constructing'
	GetStaleConstructingPayouts(ctx context.Context, arg GetStaleConstructingPayoutsParams) ([]GetStaleConstructingPayoutsRow, error)
	// Stale settling-claim watchdog: return invoices stuck in 'settling' longer
	// than the configured threshold (default 5 minutes).
	// Caller pre-computes @stale_before = NOW() - threshold duration.
	// Index: idx_inv_stale_settling ON invoices(network, updated_at)
	//        WHERE status = 'settling'
	GetStaleSettlingInvoices(ctx context.Context, arg GetStaleSettlingInvoicesParams) ([]GetStaleSettlingInvoicesRow, error)
	// Underpaid re-settlement: a new payment has arrived and may top up an
	// underpaid invoice. Returns all underpaid invoices for payment matching.
	// Index: idx_inv_underpaid ON invoices(network) WHERE status = 'underpaid'
	GetUnderpaidInvoices(ctx context.Context, network string) ([]GetUnderpaidInvoicesRow, error)
	// Fetches the active account_unlock OTP for the given email.
	// No is_locked guard — the token exists precisely because the account is locked.
	// ORDER BY created_at DESC, id DESC picks the most recently issued token.
	// FOR UPDATE prevents concurrent double-consumption.
	GetUnlockToken(ctx context.Context, email string) (GetUnlockTokenRow, error)
	// Periodic review: return unresolved dead letters for investigation.
	// Index: idx_zdl_unresolved ON btc_zmq_dead_letter(network, received_at DESC)
	//        WHERE resolved = FALSE
	GetUnresolvedDeadLetters(ctx context.Context, network string) ([]GetUnresolvedDeadLettersRow, error)
	// ── OAuth User ──
	// Returns whether the user has a password set and how many OAuth identities are linked.
	// Used by the account-settings page to determine which auth methods are available
	// and whether it is safe to unlink an identity or remove a password.
	// password_hash lives in user_secrets; a LEFT JOIN on user_identities counts linked providers.
	GetUserAuthMethods(ctx context.Context, userID pgtype.UUID) (GetUserAuthMethodsRow, error)
	// Looks up an existing user by email during OAuth callback processing.
	// Used when a provider returns an email that matches an existing account
	// (e.g. signing in with Google using an email already registered via password).
	// Returns is_locked and admin_locked so the OAuth callback handler can gate the
	// flow with the same lockout checks as the password login path.
	GetUserByEmailForOAuth(ctx context.Context, email pgtype.Text) (GetUserByEmailForOAuthRow, error)
	// Returns email_verified for a user looked up by email.
	// NOTE: used by store tests only — not used in production store code.
	GetUserEmailVerified(ctx context.Context, email pgtype.Text) (bool, error)
	// ── Delete Account ──
	// Returns id, email, password_hash, and deleted_at for the authenticated user.
	// password_hash is needed by DeleteWithPassword to verify credentials.
	// Returns no-rows for expired-grace-period accounts (deleted_at older than 30 days),
	// consistent with the login gate. The handler treats no-rows as a 500
	// (JWT user must always exist within the active window).
	GetUserForDeletion(ctx context.Context, userID pgtype.UUID) (GetUserForDeletionRow, error)
	// Returns id and current email for the authenticated user inside a transaction.
	// FOR UPDATE locks the row to prevent a concurrent email-change from racing past
	// the uniqueness re-check or producing stale old_email in audit metadata.
	// Uses active_users view to exclude soft-deleted accounts.
	GetUserForEmailChangeTx(ctx context.Context, userID pgtype.UUID) (GetUserForEmailChangeTxRow, error)
	// ── Login ────────────────────────────────────────────────────────────────────
	// Fetches the fields needed to authenticate a login by either email or username.
	// The caller passes the raw identifier; the query matches against whichever column equals it.
	// Only one can match because idx_users_email_active and idx_users_username_active are unique.
	//
	// Recently soft-deleted accounts (within 30-day grace period) are returned so the handler
	// can show a "your account is pending deletion" message and offer cancellation.
	// The handler must check deleted_at IS NOT NULL before proceeding with auth logic.
	//
	// password_hash IS NOT NULL filters out OAuth-only accounts that have no bcrypt path —
	// they must authenticate via their identity provider.
	//
	// Returns pgx.ErrNoRows when no match; caller must still run a dummy bcrypt compare
	// before surfacing ErrInvalidCredentials to equalise response timing.
	GetUserForLogin(ctx context.Context, identifier pgtype.Text) (GetUserForLoginRow, error)
	// Fetches the account state for a user identified by id during OAuth callback processing.
	// Used after GetIdentityByProviderUID returns an existing linked identity to verify the
	// account is still active before issuing tokens.
	GetUserForOAuthCallback(ctx context.Context, userID pgtype.UUID) (GetUserForOAuthCallbackRow, error)
	// Fetches the minimal fields needed to gate a password-reset request.
	// Returns the row regardless of lock state so the service can make its own
	// anti-enumeration decision without leaking account state to the caller.
	GetUserForPasswordReset(ctx context.Context, email pgtype.Text) (GetUserForPasswordResetRow, error)
	// ── Resend verification ──────────────────────────────────────────────────────
	// Fetches the minimal fields needed to decide whether a resend is valid.
	// Returns the row regardless of is_locked / email_verified so the handler can
	// respond uniformly (anti-enumeration) while still making the right decision internally.
	// is_active is intentionally excluded — an unverified account has is_active=FALSE
	// and must still receive a resend. Only is_locked=TRUE and already-verified accounts
	// are suppressed.
	GetUserForResend(ctx context.Context, email pgtype.Text) (GetUserForResendRow, error)
	// ── Set password (OAuth-only accounts) ────────────────────────────────────
	// Returns whether the user currently has no password (signed up via OAuth only).
	// Used by POST /set-password to gate the operation before attempting the write.
	GetUserForSetPassword(ctx context.Context, userID pgtype.UUID) (GetUserForSetPasswordRow, error)
	// Fetches the minimal fields needed to gate a self-service unlock request.
	// Returns the row regardless of lock state so the service can decide whether to
	// issue a token without leaking account state to unauthenticated callers.
	GetUserForUnlock(ctx context.Context, email pgtype.Text) (GetUserForUnlockRow, error)
	// Returns id and current username for the calling user.
	// FOR UPDATE locks the row inside UpdateUsernameTx to prevent a concurrent
	// rename from racing past the same-username guard or producing stale
	// old_username in the audit log.
	GetUserForUsernameUpdate(ctx context.Context, userID pgtype.UUID) (GetUserForUsernameUpdateRow, error)
	// Returns all linked OAuth identities for the given user, oldest first.
	// Used by the account-settings page to display connected providers.
	// access_token and refresh_token_provider are intentionally excluded —
	// they are provider secrets stored in user_identity_tokens and must never
	// be returned to clients.
	GetUserIdentities(ctx context.Context, userID pgtype.UUID) ([]GetUserIdentitiesRow, error)
	// Returns the full lock state: both OTP lock (is_locked, login_locked_until)
	// and admin lock (admin_locked + metadata). JOIN to users guards deleted_at.
	GetUserLockStatus(ctx context.Context, userID pgtype.UUID) (GetUserLockStatusRow, error)
	// ── Change password ───────────────────────────────────────────────────────────
	// Fetches the current bcrypt hash for credential re-verification before a password change.
	// password_hash lives in user_secrets; a JOIN on users is not needed here.
	GetUserPasswordHash(ctx context.Context, userID pgtype.UUID) (GetUserPasswordHashRow, error)
	// ── User permissions (direct grants) ───────────────────────────────────────
	// Returns only active (non-expired) grants for the given user.
	GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]GetUserPermissionsRow, error)
	// ── Profile ───────────────────────────────────────────────────────────────────
	// Returns the full profile for the authenticated user.
	// is_locked and admin_locked come from user_secrets; all other fields from users.
	GetUserProfile(ctx context.Context, userID pgtype.UUID) (GetUserProfileRow, error)
	// ── User role ───────────────────────────────────────────────────────────────
	// Returns nil (no rows) when the user has no active role assignment.
	GetUserRole(ctx context.Context, userID pgtype.UUID) (GetUserRoleRow, error)
	// Returns email_verified, is_locked, admin_locked, and is_active in a single round-trip.
	// Called when MarkEmailVerified returns 0 rows to distinguish:
	//   is_locked = TRUE or admin_locked = TRUE → ErrAccountLocked
	//   email_verified = TRUE                   → already verified (no-op, not an error)
	// Avoids a second query race window compared to checking each column separately.
	GetUserVerifiedAndLocked(ctx context.Context, userID pgtype.UUID) (GetUserVerifiedAndLockedRow, error)
	// Read the current vendor balance. SELECT only — never UPDATE directly.
	GetVendorBalance(ctx context.Context, arg GetVendorBalanceParams) (GetVendorBalanceRow, error)
	// Fetch the full wallet config for a vendor. Used at invoice creation and
	// settlement to read wallet_mode, bridge_destination_address, tier_id, etc.
	GetVendorWalletConfig(ctx context.Context, arg GetVendorWalletConfigParams) (VendorWalletConfig, error)
	// Privilege escalation is blocked by fn_prevent_privilege_escalation trigger.
	// uq_up_one_active_grant_per_user_perm is a full UNIQUE index on (user_id, permission_id),
	// so re-granting the same permission requires revoking the previous grant first.
	// The service layer should call RevokeUserPermission before this when re-granting.
	//
	// On 23505 (unique_violation) on uq_up_one_active_grant_per_user_perm:
	// service maps → ErrPermissionAlreadyGranted → 409.
	GrantUserPermission(ctx context.Context, arg GrantUserPermissionParams) (GrantUserPermissionRow, error)
	// Permanently deletes the user row. All child rows are removed via ON DELETE CASCADE:
	// refresh_tokens, user_sessions, one_time_tokens, user_identities, user_secrets,
	// auth_audit_log (user_id SET NULL — row is kept), user_roles.
	// MUST be called AFTER InsertPurgeLog within the same transaction.
	HardDeleteUser(ctx context.Context, userID pgtype.UUID) error
	// Returns true when a consumed (used_at IS NOT NULL) account_unlock token exists
	// for the email. Called by ConsumeUnlockTokenTx when GetUnlockToken returns no
	// active rows, to distinguish ErrTokenAlreadyUsed from ErrTokenNotFound.
	HasConsumedUnlockToken(ctx context.Context, email string) (bool, error)
	// Increments failed_change_password_attempts and returns the new count.
	// Called when the user submits a wrong old_password on POST /change-password.
	// AND failed_change_password_attempts < 32767 guards against SMALLINT overflow
	// on pathological inputs (the service threshold is 5, so overflow is unreachable
	// in normal operation).
	// Returns pgx.ErrNoRows when the user no longer exists — callers treat this as non-fatal.
	IncrementChangePasswordFailures(ctx context.Context, userID pgtype.UUID) (int16, error)
	// ── Login lockout & account unlock ───────────────────────────────────────────
	// Increments failed_login_attempts and sets login_locked_until to 15 minutes
	// in the future when the threshold (10) is reached.
	// Returns the updated counter and the new (possibly NULL) lock timestamp so the
	// caller can decide whether to emit a login_lockout audit row.
	IncrementLoginFailures(ctx context.Context, userID pgtype.UUID) (IncrementLoginFailuresRow, error)
	// Increment the platform treasury reserve by the miner fees retained from a
	// confirmed sweep batch. MUST be called in the SAME transaction as
	// SetPayoutConfirmed so the reconciliation formula remains balanced.
	// Omitting this causes a permanent negative discrepancy on every reconciliation run.
	IncrementTreasuryReserve(ctx context.Context, arg IncrementTreasuryReserveParams) error
	// AND attempts < max_attempts prevents incrementing past the brute-force ceiling.
	// Returns the post-increment attempts value so the caller can compare it to
	// max_attempts without relying on the stale caller-supplied count (TOCTOU fix).
	// Returns pgx.ErrNoRows when the token is already at max_attempts (no row updated);
	// callers must treat ErrNoRows as "already at ceiling" and proceed to lock logic.
	IncrementVerificationAttempts(ctx context.Context, id pgtype.UUID) (int16, error)
	// Appends one row to auth_audit_log. provider is typed as non-nullable auth_provider
	// because every event in the auth domain always has a known provider context,
	// producing a cleaner Go API than pgtype.NullAuthProvider at every call site.
	// If a future domain needs providerless events, add a separate InsertAuditLogNoProvider query.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// Record a rate fetch. Written on every successful fetch from the provider
	// regardless of whether the rate changed — this gives a complete audit trail.
	InsertExchangeRate(ctx context.Context, arg InsertExchangeRateParams) (InsertExchangeRateRow, error)
	// Append an event to the immutable financial audit trail.
	// fn_fae_validate_actor_label trigger verifies actor_label matches
	// COALESCE(email, username) for the given actor_id. Use actor_type = 'system'
	// for background job events (skips the label validation).
	// For balance-change events, BOTH balance_before_sat and balance_after_sat
	// MUST be set — chk_fae_balance_required_for_credit_debit enforces this.
	InsertFinancialAuditEvent(ctx context.Context, arg InsertFinancialAuditEventParams) (InsertFinancialAuditEventRow, error)
	// Record the start of a node outage.
	// Use pg_try_advisory_lock on the caller side to prevent concurrent duplicate
	// INSERTs from horizontal instances. The unique partial index
	// uq_outage_one_open_per_network (WHERE ended_at IS NULL) is the DB-level
	// backstop if the lock is skipped.
	// ON CONFLICT DO NOTHING: a concurrent instance already inserted — log and continue.
	InsertOutageRecord(ctx context.Context, network string) (InsertOutageRecordRow, error)
	// ── Ownership transfer ──────────────────────────────────────────────────────
	// Inserts a new pending ownership transfer token for @target_user_id.
	// token_type = 'ownership_transfer'; expires in 48 hours.
	// max_attempts = 1 (single accept attempt is all that's needed — token is consumed on success).
	// metadata carries {"initiated_by": "<owner_uuid>"} so cancel can scope the delete.
	// The caller must check for an existing pending token first and return
	// ErrTransferAlreadyPending if one exists (service layer guard).
	InsertOwnershipTransferToken(ctx context.Context, arg InsertOwnershipTransferTokenParams) (InsertOwnershipTransferTokenRow, error)
	// Writes a permanent compliance record of the purge to account_purge_log.
	// account_purge_log has no FK to users so this row survives the subsequent DELETE.
	// @metadata is a JSONB blob — callers pass {"deleted_at": "<RFC3339>"} at minimum.
	// Recommended additional keys: purged_by (UUID of the worker job), reason (string),
	// anonymized_email (one-way hash of the purged email for re-registration dedup).
	InsertPurgeLog(ctx context.Context, arg InsertPurgeLogParams) error
	// Append a history record at the start of each run. Call CloseReconciliationRunHistory
	// at the end to fill finished_at and result.
	InsertReconciliationRunHistory(ctx context.Context, network string) (InsertReconciliationRunHistoryRow, error)
	// Record an SSE token issuance with pseudonymised hashes.
	// jti_hash       = HMAC-SHA256(jti, server_secret) — computed by caller.
	// source_ip_hash = SHA256(ip || daily_rotation_key) — computed by caller.
	// uq_sti_jti_hash UNIQUE index catches any accidental duplicate issuances.
	InsertSSETokenIssuance(ctx context.Context, arg InsertSSETokenIssuanceParams) (InsertSSETokenIssuanceRow, error)
	// Write a vendor notification to the outbox. MUST be in the same transaction
	// as the triggering state change to guarantee at-least-once delivery.
	InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (InsertWebhookDeliveryRow, error)
	// Record an unmatched ZMQ event rather than silently dropping it.
	// Covers: late payments, double-spend attempts, retired addresses, unknown txids.
	// Not all dead letters are errors — late payments on expired invoices are expected.
	InsertZMQDeadLetter(ctx context.Context, arg InsertZMQDeadLetterParams) (InsertZMQDeadLetterRow, error)
	// Voids all unused password_reset tokens for this user before issuing a new one.
	// Prevents token accumulation and reduces the concurrent-reset attack window.
	// Called by RequestPasswordResetTx immediately before CreatePasswordResetToken.
	InvalidateAllUserPasswordResetTokens(ctx context.Context, userID pgtype.UUID) error
	// Voids all unused email_verification tokens for this user.
	// Scoped to token_type = 'email_verification' so in-flight password-reset or
	// magic-link tokens are not silently cancelled on a re-registration attempt.
	// Called inside the same transaction as CreateEmailVerificationToken.
	InvalidateAllUserTokens(ctx context.Context, userID pgtype.UUID) error
	// Voids all unused account_deletion OTP tokens for this user before issuing a new one.
	// Prevents token accumulation from repeated step-1 calls.
	InvalidateUserDeletionTokens(ctx context.Context, userID pgtype.UUID) error
	// Voids all unused email_change_confirm tokens for this user before issuing a new one.
	// Called inside the same transaction as CreateEmailChangeConfirmToken (step 2).
	InvalidateUserEmailChangeConfirmTokens(ctx context.Context, userID pgtype.UUID) error
	// Voids all unused email_change_verify tokens for this user before issuing a new one.
	// Called inside the same transaction as CreateEmailChangeVerifyToken.
	InvalidateUserEmailChangeVerifyTokens(ctx context.Context, userID pgtype.UUID) error
	// ZMQ startup / reconnect: rebuild the in-memory watch set for a network.
	// Called on every startup and after every reconnect so the subscriber
	// knows which addresses to watch before it starts dispatching events.
	// Index: idx_iam_reload ON invoice_address_monitoring(network, invoice_id)
	//        WHERE status = 'active'
	LoadActiveMonitoringByNetwork(ctx context.Context, network string) ([]LoadActiveMonitoringByNetworkRow, error)
	// Sets is_locked = TRUE after max OTP attempts are exhausted.
	// Does NOT touch is_active: a verified account stays active so the user can
	// still see "account locked" messaging rather than "account not found".
	// AND is_locked = FALSE makes the operation idempotent. Rowcount tells the
	// caller whether the lock actually changed state.
	// Clearing requires admin action or the account-unlock OTP flow.
	LockAccount(ctx context.Context, userID pgtype.UUID) (int64, error)
	// ── User lock ───────────────────────────────────────────────────────────────
	// NOTE: admin_locked, admin_locked_by, admin_locked_reason, admin_locked_at,
	// is_locked, and login_locked_until are all in user_secrets, not users.
	// Sets admin_locked = TRUE with actor, reason, and timestamp in user_secrets.
	// chk_us_admin_lock_coherent: reason + at required when locked = TRUE.
	// chk_us_no_self_lock: admin_locked_by must differ from user_id.
	LockUser(ctx context.Context, arg LockUserParams) error
	// Activates the account and marks email_verified = TRUE in one statement.
	// Guards:
	//   email_verified = FALSE  → prevents double-activation (idempotency guard)
	//   is_locked = TRUE        → blocks an OTP-brute-force-locked account from being
	//                             re-activated via the verification path.
	//   admin_locked = TRUE     → blocks an admin-locked account from verifying;
	//                             only admin action can clear admin_locked.
	// Returns rows affected so callers can detect a no-op and investigate the cause
	// with GetUserVerifiedAndLocked.
	MarkEmailVerified(ctx context.Context, userID pgtype.UUID) (int64, error)
	// Set sweep_completed = TRUE atomically with the constructing → broadcast
	// payout transition. The reorg rollback logic pivots on this field:
	//   TRUE  → reorg_admin_required (sweep may already be broadcast)
	//   FALSE → roll back to detected (safe to re-settle)
	// Called in the same transaction as SetPayoutBroadcast.
	// Caller MUST assert RowsAffected() == 1.
	MarkInvoiceSweepCompleted(ctx context.Context, invoiceID pgtype.UUID) (int64, error)
	// Any pre-terminal state → failed. Used when all retries are exhausted.
	// fn_pr_status_guard enforces the transition is permitted from the current state.
	// Caller MUST assert RowsAffected() == 1.
	MarkPayoutFailed(ctx context.Context, arg MarkPayoutFailedParams) (int64, error)
	// Record a failed delivery attempt. The caller computes next_retry_at with
	// exponential backoff. Pass status = 'dead_lettered' when
	// attempt_count + 1 >= max_attempts.
	MarkWebhookAttempted(ctx context.Context, arg MarkWebhookAttemptedParams) (int64, error)
	// Mark a delivery as successfully acknowledged by the vendor's endpoint.
	MarkWebhookDelivered(ctx context.Context, deliveryID pgtype.UUID) (int64, error)
	// held → queued: net_satoshis has cleared the miner fee floor.
	// fn_pr_status_guard trigger enforces this is a permitted transition.
	// Caller MUST assert RowsAffected() == 1.
	PromoteHeldToQueued(ctx context.Context, payoutID pgtype.UUID) (int64, error)
	RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) (int64, error)
	// Hard-deletes a user's role assignment. Returns rows affected (0 = no assignment found).
	// fn_prevent_orphaned_owner fires as a DB backstop before DELETE.
	RemoveUserRole(ctx context.Context, userID pgtype.UUID) (int64, error)
	// Resets failed_change_password_attempts to 0 after a successful password change.
	// AND failed_change_password_attempts > 0 makes the update a no-op when already zero,
	// avoiding a write on the happy path for users who never had a failed attempt.
	ResetChangePasswordFailures(ctx context.Context, userID pgtype.UUID) error
	// Clears the failed-attempt counter and removes any time-based login lock.
	// Called inside LoginTx after a successful authentication so the next wrong password
	// starts a fresh count from zero.
	ResetLoginFailures(ctx context.Context, userID pgtype.UUID) error
	// Reset a stale 'settling' invoice back to its predecessor status
	// (confirming or underpaid, as recorded in settling_source).
	// Called by the stale-settling watchdog after the 5-minute threshold.
	// Caller MUST assert RowsAffected() == 1.
	ResetStaleSettlingInvoice(ctx context.Context, invoiceID pgtype.UUID) (int64, error)
	// Mark a dead letter as investigated and resolved with a note.
	ResolveDeadLetter(ctx context.Context, arg ResolveDeadLetterParams) (int64, error)
	// failed → manual_payout: admin declares an out-of-band payment was made.
	// fn_pr_status_guard enforces failed → manual_payout is a permitted transition.
	// Caller MUST assert RowsAffected() == 1.
	ResolvePayoutManually(ctx context.Context, arg ResolvePayoutManuallyParams) (int64, error)
	// Expiry cleanup job: retire active monitoring records whose window has elapsed.
	// Retired rows are NEVER deleted — they form the permanent monitoring audit trail.
	// The partial index on status = 'active' keeps all queries fast regardless of
	// how many retired rows accumulate.
	// Index: idx_iam_expiry_cleanup ON invoice_address_monitoring(monitor_until)
	//        WHERE status = 'active' AND monitor_until IS NOT NULL
	RetireExpiredMonitoringRecords(ctx context.Context) ([]pgtype.UUID, error)
	// ── Mass revocation ──────────────────────────────────────────────────────────
	// Revokes every active (non-expired, non-revoked) refresh token for the user.
	// @reason distinguishes mass-revocations in the audit trail
	// (e.g. 'password_changed', 'forced_logout').
	// Scoped to expires_at > NOW() so already-expired rows are left untouched —
	// they carry no security risk and bulk-updating them wastes I/O.
	RevokeAllUserRefreshTokens(ctx context.Context, arg RevokeAllUserRefreshTokensParams) error
	// Revokes every non-revoked token in the given token family.
	// Called with reason = 'reuse_detected' when the refresh endpoint receives a token
	// that has already been consumed (token-replay attack). Kills the entire family to
	// force re-authentication regardless of which generation the attacker holds.
	RevokeFamilyRefreshTokens(ctx context.Context, arg RevokeFamilyRefreshTokensParams) error
	// Revokes all non-revoked refresh tokens issued before email verification completes.
	// Pre-verification tokens must never create authenticated sessions — they were issued
	// during the registration window before the user proved ownership of the email address.
	RevokePreVerificationTokens(ctx context.Context, userID pgtype.UUID) error
	// Marks a single refresh token as revoked. AND revoked_at IS NULL makes it idempotent.
	// Called with reason = 'rotated' during token rotation and 'logout' during explicit logout.
	// The 'logout' reason is excluded from the family-cascade trigger so only the presented
	// token is revoked, not the entire family.
	RevokeRefreshTokenByJTI(ctx context.Context, arg RevokeRefreshTokenByJTIParams) (pgconn.CommandTag, error)
	// Revokes all non-revoked refresh tokens for a specific session.
	// Called by RevokeSessionTx when a user explicitly ends a single device session.
	RevokeSessionRefreshTokens(ctx context.Context, sessionID pgtype.UUID) error
	// Hard-deletes by surrogate id scoped to user_id (prevents cross-user deletion).
	RevokeUserPermission(ctx context.Context, arg RevokeUserPermissionParams) (int64, error)
	// Stamps deleted_at = NOW() for the given active user.
	// Returns deleted_at so the handler can compute scheduled_deletion_at = deleted_at + 30d.
	ScheduleUserDeletion(ctx context.Context, userID pgtype.UUID) (*time.Time, error)
	// Sets rbac.acting_user for the current transaction so audit triggers
	// (fn_audit_role_permissions, etc.) record the correct deletion actor.
	// set_config(name, value, is_local=true) is equivalent to SET LOCAL and
	// accepts a parameterized value, unlike the SET statement.
	SetActingUser(ctx context.Context, userID string) error
	// Set the monitor_until timestamp when an invoice reaches a terminal status.
	// MUST be called in the SAME transaction as the terminal status transition.
	// monitor_until = terminal_at + 30 days.
	// Caller MUST assert RowsAffected() == 1.
	SetMonitoringWindow(ctx context.Context, arg SetMonitoringWindowParams) (int64, error)
	// Sets password_hash for an OAuth-only account that has no password yet.
	// WHERE password_hash IS NULL is the DB-level concurrency guard:
	// a concurrent set-password call that races past the service guard returns
	// 0 rows affected, which the store maps to ErrPasswordAlreadySet.
	SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) (int64, error)
	// constructing → broadcast. Sets batch_txid, vout_index_in_batch, fee fields.
	// CRITICAL: this UPDATE MUST commit BEFORE sendrawtransaction is called.
	// See BROADCAST ORDERING INVARIANT in payout_records table comment.
	// If RowsAffected() == 0 the watchdog reclaimed the record — abort broadcast.
	SetPayoutBroadcast(ctx context.Context, arg SetPayoutBroadcastParams) (int64, error)
	// broadcast → confirmed. Sets confirmed_at.
	// MUST be called in the SAME transaction as IncrementTreasuryReserve to keep
	// the reconciliation formula balanced.
	// Caller MUST assert RowsAffected() == 1.
	SetPayoutConfirmed(ctx context.Context, payoutID pgtype.UUID) (int64, error)
	// Record an RBF fee bump on a broadcast payout. Saves the original txid to
	// original_txid and replaces batch_txid with the replacement txid.
	// Status remains 'broadcast' — the confirmation handler detects the new txid.
	SetPayoutRBF(ctx context.Context, arg SetPayoutRBFParams) (int64, error)
	// Suppresses fn_prevent_owner_role_escalation for the duration of the current
	// transaction. SET LOCAL means the setting is automatically cleared at transaction end.
	// Called as the FIRST statement in AcceptTransferTx before any role mutations.
	SetSkipEscalationCheck(ctx context.Context) error
	// Activate the sweep hold emergency brake. Requires a written reason.
	// fn_ops_audit_platform_config trigger writes to ops_audit_log automatically.
	// Set app.current_actor_id and app.current_actor_label session variables before
	// executing so the ops audit entry captures who activated the hold.
	SetSweepHold(ctx context.Context, arg SetSweepHoldParams) error
	// Updates users.email for the given active user.
	// Returns rows affected so the store can distinguish:
	//   23505 on idx_users_email_active → ErrEmailTaken (concurrent race past service guard)
	//   rows == 0                       → ErrUserNotFound (account deleted between steps)
	SetUserEmail(ctx context.Context, arg SetUserEmailParams) (int64, error)
	// Sets username for the user identified by id.
	// Returns rows affected so the store can distinguish:
	//   23505 unique_violation on idx_users_username_active → ErrUsernameTaken
	//   rows == 0                                           → ErrUserNotFound
	SetUsername(ctx context.Context, arg SetUsernameParams) (int64, error)
	// Reconciliation formula term: sum of satoshis locked in non-terminal invoice states.
	// Index: idx_inv_network_status_inflight with INCLUDE (amount_sat, created_at)
	// enables an index-only scan — no heap fetch required.
	SumInflightInvoiceAmounts(ctx context.Context, network string) (int64, error)
	// Reconciliation formula term: sum of pre-confirmation payout obligations.
	// Includes held, queued, constructing, broadcast — all states where on-chain
	// funds are still owed to vendors but not yet confirmed.
	SumInflightPayoutRecords(ctx context.Context, network string) (int64, error)
	// Settlement Phase 1: sum all received satoshis for the given invoice and txid.
	// A single TX may send multiple vouts to the same address — this SUM covers all.
	// Index: idx_ip_invoice_id with INCLUDE (value_sat, txid) enables index-only scan.
	SumInvoicePayments(ctx context.Context, arg SumInvoicePaymentsParams) (int64, error)
	// Reconciliation formula term: sum of all platform-mode vendor balances.
	// Hybrid-mode balances are intentionally EXCLUDED — they are threshold
	// accumulators only, not value-bearing. Their value is fully captured in
	// held/queued payout_records. Including both would double-count hybrid funds.
	SumPlatformVendorBalances(ctx context.Context, network string) (int64, error)
	// detected → confirming: first block confirmation received.
	// Sets first_confirmed_block_height ATOMICALLY — this is required by the reorg
	// rollback query which filters on this column.
	// Caller MUST assert RowsAffected() == 1.
	TransitionInvoiceToConfirming(ctx context.Context, arg TransitionInvoiceToConfirmingParams) (int64, error)
	// pending → detected: payment seen in mempool. Freezes the expiry timer.
	// Sets detected_txid and detected_at atomically.
	// Caller MUST assert RowsAffected() == 1.
	TransitionInvoiceToDetected(ctx context.Context, arg TransitionInvoiceToDetectedParams) (int64, error)
	// pending|mempool_dropped → expired. Sets expired_at.
	// Caller MUST assert RowsAffected() == 1.
	TransitionInvoiceToExpired(ctx context.Context, arg TransitionInvoiceToExpiredParams) (int64, error)
	// detected → mempool_dropped: payment disappeared from mempool.
	// Sets mempool_absent_since on the first absent check.
	// Caller MUST assert RowsAffected() == 1.
	TransitionInvoiceToMempoolDropped(ctx context.Context, invoiceID pgtype.UUID) (int64, error)
	// settling → settled: settlement complete, payout queued or balance credited.
	// Caller MUST assert RowsAffected() == 1.
	TransitionInvoiceToSettled(ctx context.Context, arg TransitionInvoiceToSettledParams) (int64, error)
	// settling → settlement_failed: all retries exhausted. Increments retry_count.
	// Caller MUST assert RowsAffected() == 1.
	TransitionInvoiceToSettlementFailed(ctx context.Context, invoiceID pgtype.UUID) (int64, error)
	// confirming|underpaid → settling: settlement worker claims this invoice.
	// Sets settling_source so admin retry uses the correct code path.
	// Caller MUST assert RowsAffected() == 1.
	TransitionInvoiceToSettling(ctx context.Context, arg TransitionInvoiceToSettlingParams) (int64, error)
	// mempool_dropped → detected: payment re-appeared in the mempool.
	// Clears mempool_absent_since per the two-cycle watchdog design.
	// Caller MUST assert RowsAffected() == 1.
	TransitionMempoolDroppedToDetected(ctx context.Context, invoiceID pgtype.UUID) (int64, error)
	// Clears is_locked, failed_login_attempts, and login_locked_until atomically.
	// Called after a successful account-unlock OTP confirmation.
	UnlockAccount(ctx context.Context, userID pgtype.UUID) error
	// Clears admin_locked and all metadata fields in user_secrets.
	// chk_us_admin_lock_coherent requires all three metadata fields to be NULL
	// when admin_locked = FALSE, so all four must be cleared atomically.
	UnlockUser(ctx context.Context, userID pgtype.UUID) error
	// Advance the block-height cursor inside a reconcileSegment transaction.
	// Updated every BTC_RECONCILIATION_CHECKPOINT_INTERVAL blocks so a crash
	// mid-backfill resumes from the checkpoint rather than the beginning.
	UpdateBitcoinSyncState(ctx context.Context, arg UpdateBitcoinSyncStateParams) error
	// Stamps last_login_at after a successful authentication.
	// updated_at is omitted: trg_users_updated_at (BEFORE UPDATE trigger) already
	// sets updated_at = NOW() on every UPDATE, making an explicit assignment a dead no-op.
	// Called inside the same transaction as CreateUserSession so a rolled-back login
	// does not leave a stale last_login_at.
	UpdateLastLoginAt(ctx context.Context, userID pgtype.UUID) error
	// Replaces the stored bcrypt password hash for a user.
	// Called after successful OTP validation in a transaction that also revokes all
	// existing sessions — a password change must invalidate every active device.
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	// WHERE is_system_role = FALSE prevents renaming system roles at the DB level.
	// Zero rows affected → service returns ErrSystemRoleImmutable → 409.
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	// Stamps last_active_at = NOW() for a session that is still open.
	// Called by the /refresh endpoint after successful token rotation so the
	// device session shows real activity, not just creation time.
	// AND ended_at IS NULL makes the update a no-op for already-closed sessions.
	UpdateSessionLastActive(ctx context.Context, id pgtype.UUID) error
	// Backfills avatar_url from an OAuth provider only when the user has no avatar set.
	// Called during OAuth login to sync the provider's picture without overwriting
	// a profile picture the user has explicitly set via PATCH /profile/me.
	UpdateUserAvatarIfNull(ctx context.Context, arg UpdateUserAvatarIfNullParams) error
	// Updates display_name and/or avatar_url using COALESCE so that a NULL
	// parameter leaves the current column value unchanged (partial-update pattern).
	// Called by UpdateProfileTx after input validation confirms at least one field is non-nil.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	// Record a processed block. Pruned blocks use block_hash = NULL, pruned = TRUE.
	// ON CONFLICT DO NOTHING: the PK is (height, network) — duplicate processing
	// attempts are silently ignored for idempotency.
	UpsertBlockHistory(ctx context.Context, arg UpsertBlockHistoryParams) error
	// Append-only payment record. Always ON CONFLICT DO NOTHING for idempotency —
	// ZMQ events may deliver the same txid multiple times on reconnect.
	// Returns NULL when the row already exists (conflict); callers discard NULLs.
	// Conflict target: UNIQUE constraint uq_inv_payment_txid_vout on (txid, vout_index).
	UpsertInvoicePayment(ctx context.Context, arg UpsertInvoicePaymentParams) (InvoicePayment, error)
	// Update reconciliation state after each run.
	// Pass last_successful_run_at = NOW() on result = 'ok'.
	// Pass last_successful_run_at = NULL on failure — the COALESCE preserves
	// the previous successful timestamp so the staleness alert fires correctly.
	UpsertReconciliationJobState(ctx context.Context, arg UpsertReconciliationJobStateParams) error
	// Inserts or updates the identity metadata row for an OAuth account.
	// Token columns (access_token, access_token_expires_at, refresh_token_provider)
	// are NOT handled here — call UpsertUserIdentityTokens immediately after in the
	// same transaction to persist encrypted tokens.
	//
	// ON CONFLICT ON CONSTRAINT uq_identity_user_provider refreshes provider-side
	// metadata (display name, avatar, raw profile) on each login without creating duplicate rows.
	//
	// RETURNING uses an explicit column list (not *) so future column additions to
	// user_identities do not silently change the generated Go struct.
	UpsertUserIdentity(ctx context.Context, arg UpsertUserIdentityParams) (UpsertUserIdentityRow, error)
	// Persists encrypted OAuth tokens for the given identity.
	// access_token MUST be AES-256-GCM encrypted (enc: prefix) before being passed here.
	// refresh_token_provider MUST also be encrypted if non-NULL.
	// chk_uit_access_token_encrypted and chk_uit_refresh_token_encrypted enforce this at the DB layer.
	// Must be called in the same transaction as UpsertUserIdentity, using the returned identity_id.
	UpsertUserIdentityTokens(ctx context.Context, arg UpsertUserIdentityTokensParams) error
}

var _ Querier = (*Queries)(nil)
