// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const AddRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (
    role_id, permission_id, granted_by, granted_reason,
    access_type, scope, conditions
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6,
    COALESCE($7::jsonb, '{}')
)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID        pgtype.UUID          `db:"role_id" json:"role_id"`
	PermissionID  pgtype.UUID          `db:"permission_id" json:"permission_id"`
	GrantedBy     pgtype.UUID          `db:"granted_by" json:"granted_by"`
	GrantedReason string               `db:"granted_reason" json:"granted_reason"`
	AccessType    PermissionAccessType `db:"access_type" json:"access_type"`
	Scope         PermissionScope      `db:"scope" json:"scope"`
	Conditions    []byte               `db:"conditions" json:"conditions"`
}

// ON CONFLICT DO NOTHING: idempotent — adding a permission the role already has is a no-op.
// To update access_type/scope on an existing grant, remove + re-add from the service layer.
func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, AddRolePermission,
		arg.RoleID,
		arg.PermissionID,
		arg.GrantedBy,
		arg.GrantedReason,
		arg.AccessType,
		arg.Scope,
		arg.Conditions,
	)
	return err
}

const AssignUserRole = `-- name: AssignUserRole :one
INSERT INTO user_roles (user_id, role_id, granted_by, granted_reason, expires_at)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5::timestamptz
)
ON CONFLICT (user_id) DO UPDATE
    SET role_id        = EXCLUDED.role_id,
        granted_by     = EXCLUDED.granted_by,
        granted_reason = EXCLUDED.granted_reason,
        expires_at     = EXCLUDED.expires_at,
        updated_at     = NOW()
RETURNING user_id, role_id, expires_at, created_at, updated_at
`

type AssignUserRoleParams struct {
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	RoleID        pgtype.UUID        `db:"role_id" json:"role_id"`
	GrantedBy     pgtype.UUID        `db:"granted_by" json:"granted_by"`
	GrantedReason string             `db:"granted_reason" json:"granted_reason"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type AssignUserRoleRow struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	RoleID    pgtype.UUID        `db:"role_id" json:"role_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt time.Time          `db:"updated_at" json:"updated_at"`
}

// Inserts or replaces a user's role assignment. ON CONFLICT targets the user_id
// PRIMARY KEY (one-role-per-user invariant). fn_prevent_owner_role_escalation fires
// as a DB backstop before each INSERT/UPDATE OF role_id.
//
// The bootstrap handler calls this with granted_by = user_id (self-grant; only valid
// because bootstrap is the chicken-and-egg path before any owner exists).
func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) (AssignUserRoleRow, error) {
	row := q.db.QueryRow(ctx, AssignUserRole,
		arg.UserID,
		arg.RoleID,
		arg.GrantedBy,
		arg.GrantedReason,
		arg.ExpiresAt,
	)
	var i AssignUserRoleRow
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CheckUserAccess = `-- name: CheckUserAccess :one
/* ============================================================
   sql/queries/rbac.sql
   RBAC domain queries for sqlc code generation.

   Covers all role-based access control flows in dependency order:
     Permission check (hot path)
     Bootstrap
     Roles
     Role permissions
     Permissions
     User role
     User permissions (direct grants)
     User lock

   Security-sensitive admin-lock fields (admin_locked, admin_locked_by,
   admin_locked_reason, admin_locked_at, is_locked, login_locked_until)
   live in user_secrets, not users. Every query that reads or writes those
   columns JOINs or targets user_secrets directly.
   ============================================================ */



WITH user_role_ctx AS MATERIALIZED (
    -- Single lookup: the user's one role row + owner/active flags.
    -- user_id is the PK of user_roles so this is always at most one row.
    SELECT
        ur.role_id,
        ur.expires_at,
        r.is_owner_role,
        r.is_active AS role_active
    FROM   user_roles ur
    JOIN   roles r ON r.id = ur.role_id
    WHERE  ur.user_id  = $1::uuid
      AND  r.is_active = TRUE
      AND  (ur.expires_at IS NULL OR ur.expires_at > NOW())
),
perm_id AS MATERIALIZED (
    -- Resolve permission_id once; shared by both role_grant and direct_grant.
    -- idx_permissions_canonical gives an O(1) index-only seek on canonical_name.
    SELECT id AS permission_id
    FROM   permissions
    WHERE  canonical_name = $2
      AND  is_active      = TRUE
),
role_grant AS MATERIALIZED (
    -- Point lookup: (role_id, permission_id) on role_permissions.
    -- idx_role_perms_covering INCLUDE(conditions, access_type, scope) → index-only scan,
    -- no heap fetch required.
    SELECT rp.access_type, rp.scope, rp.conditions
    FROM   user_role_ctx rc
    CROSS JOIN perm_id pi
    JOIN   role_permissions rp
               ON rp.role_id       = rc.role_id
              AND rp.permission_id = pi.permission_id
),
direct_grant AS MATERIALIZED (
    -- Point lookup: (user_id, permission_id) on user_permissions.
    -- uq_up_one_active_grant_per_user_perm replaces the previous (user_id, expires_at)
    -- range scan; O(1) regardless of how many grants the user holds.
    SELECT up.scope, up.conditions
    FROM   perm_id pi
    JOIN   user_permissions up
               ON up.user_id       = $1::uuid
              AND up.permission_id = pi.permission_id
    WHERE  up.expires_at > NOW()
    -- No LIMIT: uq_up_one_active_grant_per_user_perm guarantees at most 1 row
)
SELECT
    -- Layer 1: owner check — read from already-materialized user_role_ctx; zero extra seeks.
    COALESCE((SELECT is_owner_role FROM user_role_ctx), FALSE) AS is_owner,

    -- Layer 2: explicit denial — denied takes priority over all other grants.
    EXISTS(
        SELECT 1 FROM role_grant WHERE access_type = 'denied'
    ) AS is_explicitly_denied,

    -- Layer 3: permission existence via role (non-denied) or direct grant.
    (
        EXISTS(SELECT 1 FROM role_grant WHERE access_type != 'denied')
        OR
        EXISTS(SELECT 1 FROM direct_grant)
    ) AS has_permission,

    -- access_type: role path (non-denied) takes priority; fallback to 'direct' for direct grants.
    COALESCE(
        (SELECT access_type FROM role_grant WHERE access_type != 'denied'),
        'direct'::permission_access_type
    ) AS access_type,

    -- scope: role path (non-denied) takes priority; fallback to direct grant scope.
    COALESCE(
        (SELECT scope FROM role_grant WHERE access_type != 'denied'),
        (SELECT scope FROM direct_grant)
    ) AS scope,

    -- conditions: role path (non-denied) takes priority; fallback to direct grant; default '{}'.
    COALESCE(
        (SELECT conditions FROM role_grant WHERE access_type != 'denied'),
        (SELECT conditions FROM direct_grant),
        '{}'::jsonb
    ) AS conditions
`

type CheckUserAccessParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	Permission pgtype.Text `db:"permission" json:"permission"`
}

type CheckUserAccessRow struct {
	IsOwner            interface{} `db:"is_owner" json:"is_owner"`
	IsExplicitlyDenied bool        `db:"is_explicitly_denied" json:"is_explicitly_denied"`
	HasPermission      pgtype.Bool `db:"has_permission" json:"has_permission"`
	AccessType         interface{} `db:"access_type" json:"access_type"`
	Scope              interface{} `db:"scope" json:"scope"`
	Conditions         interface{} `db:"conditions" json:"conditions"`
}

// ── Permission check (hot path) ────────────────────────────────────────────
// Returns the full access context for (user_id, permission) in one round-trip.
// is_owner short-circuits in Go — all other fields are ignored when is_owner = true.
//
// Single-pass rewrite: resolves user_role_ctx and perm_id exactly once each,
// then derives all output columns from those two materialized CTEs. Eliminates the
// previous triple traversal of user_roles and the duplicate 4-table join chain.
//
// Index usage:
//
//	user_role_ctx: user_roles PK (user_id) — at most 1 row
//	perm_id:       idx_permissions_canonical — O(1) index-only seek
//	role_grant:    idx_role_perms_covering(role_id, permission_id) INCLUDE(conditions,access_type,scope)
//	direct_grant:  uq_up_one_active_grant_per_user_perm(user_id, permission_id) — point lookup,
//	               replaces previous (user_id, expires_at) range scan
func (q *Queries) CheckUserAccess(ctx context.Context, arg CheckUserAccessParams) (CheckUserAccessRow, error) {
	row := q.db.QueryRow(ctx, CheckUserAccess, arg.UserID, arg.Permission)
	var i CheckUserAccessRow
	err := row.Scan(
		&i.IsOwner,
		&i.IsExplicitlyDenied,
		&i.HasPermission,
		&i.AccessType,
		&i.Scope,
		&i.Conditions,
	)
	return i, err
}

const CountActiveOwners = `-- name: CountActiveOwners :one

SELECT COUNT(*) AS count
FROM   user_roles ur
JOIN   roles r ON r.id = ur.role_id
WHERE  r.is_owner_role = TRUE
  AND  r.is_active     = TRUE
  AND  (ur.expires_at IS NULL OR ur.expires_at > NOW())
`

// ── Bootstrap ───────────────────────────────────────────────────────────────
// Used by /owner/bootstrap to gate on whether an active owner already exists.
func (q *Queries) CountActiveOwners(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountActiveOwners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateRole = `-- name: CreateRole :one
INSERT INTO roles (name, description, is_system_role, is_owner_role)
VALUES ($1, $2, FALSE, FALSE)
RETURNING id, name, description, is_system_role, is_owner_role, is_active, created_at, updated_at
`

type CreateRoleParams struct {
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

// is_system_role and is_owner_role are always FALSE for end-user-created roles.
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, CreateRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.IsOwnerRole,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeactivateRole = `-- name: DeactivateRole :execrows
UPDATE roles
SET is_active = FALSE
WHERE id             = $1::uuid
  AND is_system_role = FALSE
  AND is_active      = TRUE
`

// Soft-deletes a non-system role. Zero rows → ErrSystemRoleImmutable → 409.
func (q *Queries) DeactivateRole(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, DeactivateRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const GetActiveUserByID = `-- name: GetActiveUserByID :one
SELECT id, email, is_active, email_verified
FROM   users
WHERE  id         = $1::uuid
  AND  deleted_at IS NULL
`

type GetActiveUserByIDRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	Email         pgtype.Text `db:"email" json:"email"`
	IsActive      bool        `db:"is_active" json:"is_active"`
	EmailVerified bool        `db:"email_verified" json:"email_verified"`
}

// Verifies a target user exists, is active, and has confirmed their email.
// Used by bootstrap to reject unknown or unverified user_ids.
func (q *Queries) GetActiveUserByID(ctx context.Context, userID pgtype.UUID) (GetActiveUserByIDRow, error) {
	row := q.db.QueryRow(ctx, GetActiveUserByID, userID)
	var i GetActiveUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsActive,
		&i.EmailVerified,
	)
	return i, err
}

const GetOwnerRoleID = `-- name: GetOwnerRoleID :one
SELECT id FROM roles
WHERE  is_owner_role  = TRUE
  AND  is_system_role = TRUE
LIMIT 1
`

// Looks up the owner role seeded by 001_roles.sql.
func (q *Queries) GetOwnerRoleID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, GetOwnerRoleID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const GetPermissionByCanonicalName = `-- name: GetPermissionByCanonicalName :one
SELECT id, canonical_name, name, resource_type, description, is_active
FROM   permissions
WHERE  canonical_name = $1
  AND  is_active      = TRUE
`

type GetPermissionByCanonicalNameRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	CanonicalName pgtype.Text `db:"canonical_name" json:"canonical_name"`
	Name          string      `db:"name" json:"name"`
	ResourceType  string      `db:"resource_type" json:"resource_type"`
	Description   pgtype.Text `db:"description" json:"description"`
	IsActive      bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) GetPermissionByCanonicalName(ctx context.Context, canonicalName pgtype.Text) (GetPermissionByCanonicalNameRow, error) {
	row := q.db.QueryRow(ctx, GetPermissionByCanonicalName, canonicalName)
	var i GetPermissionByCanonicalNameRow
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.Name,
		&i.ResourceType,
		&i.Description,
		&i.IsActive,
	)
	return i, err
}

const GetPermissionGroupMembers = `-- name: GetPermissionGroupMembers :many
SELECT p.id, p.canonical_name, p.name, p.resource_type, p.description
FROM   permission_group_members pgm
JOIN   permissions p ON p.id = pgm.permission_id
WHERE  pgm.group_id = $1::uuid
  AND  p.is_active  = TRUE
ORDER  BY p.canonical_name
`

type GetPermissionGroupMembersRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	CanonicalName pgtype.Text `db:"canonical_name" json:"canonical_name"`
	Name          string      `db:"name" json:"name"`
	ResourceType  string      `db:"resource_type" json:"resource_type"`
	Description   pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) GetPermissionGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GetPermissionGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, GetPermissionGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPermissionGroupMembersRow{}
	for rows.Next() {
		var i GetPermissionGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalName,
			&i.Name,
			&i.ResourceType,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPermissionGroups = `-- name: GetPermissionGroups :many
SELECT id, name, display_label, icon, color_hex, display_order, is_visible
FROM   permission_groups
WHERE  is_active = TRUE
ORDER  BY display_order, name
`

type GetPermissionGroupsRow struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	DisplayLabel pgtype.Text `db:"display_label" json:"display_label"`
	Icon         pgtype.Text `db:"icon" json:"icon"`
	ColorHex     pgtype.Text `db:"color_hex" json:"color_hex"`
	DisplayOrder int32       `db:"display_order" json:"display_order"`
	IsVisible    bool        `db:"is_visible" json:"is_visible"`
}

func (q *Queries) GetPermissionGroups(ctx context.Context) ([]GetPermissionGroupsRow, error) {
	rows, err := q.db.Query(ctx, GetPermissionGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPermissionGroupsRow{}
	for rows.Next() {
		var i GetPermissionGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayLabel,
			&i.Icon,
			&i.ColorHex,
			&i.DisplayOrder,
			&i.IsVisible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPermissions = `-- name: GetPermissions :many

SELECT id, canonical_name, name, resource_type, description, is_active, created_at
FROM   permissions
WHERE  is_active = TRUE
ORDER  BY canonical_name
`

type GetPermissionsRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	CanonicalName pgtype.Text `db:"canonical_name" json:"canonical_name"`
	Name          string      `db:"name" json:"name"`
	ResourceType  string      `db:"resource_type" json:"resource_type"`
	Description   pgtype.Text `db:"description" json:"description"`
	IsActive      bool        `db:"is_active" json:"is_active"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
}

// ── Permissions ─────────────────────────────────────────────────────────────
func (q *Queries) GetPermissions(ctx context.Context) ([]GetPermissionsRow, error) {
	rows, err := q.db.Query(ctx, GetPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPermissionsRow{}
	for rows.Next() {
		var i GetPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalName,
			&i.Name,
			&i.ResourceType,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, is_system_role, is_owner_role, is_active, created_at, updated_at
FROM   roles
WHERE  id = $1::uuid
`

func (q *Queries) GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, GetRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.IsOwnerRole,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system_role, is_owner_role, is_active, created_at, updated_at
FROM   roles
WHERE  name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, GetRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.IsOwnerRole,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRolePermissions = `-- name: GetRolePermissions :many

SELECT p.id, p.canonical_name, p.name, p.resource_type, p.description,
       rp.access_type, rp.scope, rp.conditions, rp.created_at AS granted_at
FROM   role_permissions rp
JOIN   permissions p ON p.id = rp.permission_id
WHERE  rp.role_id  = $1::uuid
  AND  p.is_active = TRUE
ORDER  BY p.canonical_name
`

type GetRolePermissionsRow struct {
	ID            uuid.UUID            `db:"id" json:"id"`
	CanonicalName pgtype.Text          `db:"canonical_name" json:"canonical_name"`
	Name          string               `db:"name" json:"name"`
	ResourceType  string               `db:"resource_type" json:"resource_type"`
	Description   pgtype.Text          `db:"description" json:"description"`
	AccessType    PermissionAccessType `db:"access_type" json:"access_type"`
	Scope         PermissionScope      `db:"scope" json:"scope"`
	Conditions    []byte               `db:"conditions" json:"conditions"`
	GrantedAt     time.Time            `db:"granted_at" json:"granted_at"`
}

// ── Role permissions ────────────────────────────────────────────────────────
func (q *Queries) GetRolePermissions(ctx context.Context, roleID pgtype.UUID) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, GetRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRolePermissionsRow{}
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalName,
			&i.Name,
			&i.ResourceType,
			&i.Description,
			&i.AccessType,
			&i.Scope,
			&i.Conditions,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRoles = `-- name: GetRoles :many

SELECT id, name, description, is_system_role, is_owner_role, is_active, created_at, updated_at
FROM   roles
WHERE  is_active = TRUE
ORDER  BY name
`

// ── Roles ───────────────────────────────────────────────────────────────────
func (q *Queries) GetRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, GetRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystemRole,
			&i.IsOwnerRole,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserLockStatus = `-- name: GetUserLockStatus :one
SELECT
    u.id,
    us.admin_locked,
    us.admin_locked_by,
    us.admin_locked_reason,
    us.admin_locked_at,
    us.is_locked,
    us.login_locked_until
FROM   users u
JOIN   user_secrets us ON us.user_id = u.id
WHERE  u.id         = $1::uuid
  AND  u.deleted_at IS NULL
`

type GetUserLockStatusRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	AdminLocked       bool               `db:"admin_locked" json:"admin_locked"`
	AdminLockedBy     pgtype.UUID        `db:"admin_locked_by" json:"admin_locked_by"`
	AdminLockedReason pgtype.Text        `db:"admin_locked_reason" json:"admin_locked_reason"`
	AdminLockedAt     pgtype.Timestamptz `db:"admin_locked_at" json:"admin_locked_at"`
	IsLocked          bool               `db:"is_locked" json:"is_locked"`
	LoginLockedUntil  pgtype.Timestamptz `db:"login_locked_until" json:"login_locked_until"`
}

// Returns the full lock state: both OTP lock (is_locked, login_locked_until)
// and admin lock (admin_locked + metadata). JOIN to users guards deleted_at.
func (q *Queries) GetUserLockStatus(ctx context.Context, userID pgtype.UUID) (GetUserLockStatusRow, error) {
	row := q.db.QueryRow(ctx, GetUserLockStatus, userID)
	var i GetUserLockStatusRow
	err := row.Scan(
		&i.ID,
		&i.AdminLocked,
		&i.AdminLockedBy,
		&i.AdminLockedReason,
		&i.AdminLockedAt,
		&i.IsLocked,
		&i.LoginLockedUntil,
	)
	return i, err
}

const GetUserPermissions = `-- name: GetUserPermissions :many

SELECT up.id, p.canonical_name, p.name, p.resource_type,
       up.scope, up.conditions, up.expires_at,
       up.created_at AS granted_at, up.granted_reason
FROM   user_permissions up
JOIN   permissions p ON p.id = up.permission_id
WHERE  up.user_id    = $1::uuid
  AND  up.expires_at > NOW()
  AND  p.is_active   = TRUE
ORDER  BY p.canonical_name
`

type GetUserPermissionsRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	CanonicalName pgtype.Text        `db:"canonical_name" json:"canonical_name"`
	Name          string             `db:"name" json:"name"`
	ResourceType  string             `db:"resource_type" json:"resource_type"`
	Scope         PermissionScope    `db:"scope" json:"scope"`
	Conditions    []byte             `db:"conditions" json:"conditions"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	GrantedAt     time.Time          `db:"granted_at" json:"granted_at"`
	GrantedReason string             `db:"granted_reason" json:"granted_reason"`
}

// ── User permissions (direct grants) ───────────────────────────────────────
// Returns only active (non-expired) grants for the given user.
func (q *Queries) GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, GetUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalName,
			&i.Name,
			&i.ResourceType,
			&i.Scope,
			&i.Conditions,
			&i.ExpiresAt,
			&i.GrantedAt,
			&i.GrantedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserRole = `-- name: GetUserRole :one

SELECT ur.user_id, ur.role_id, r.name AS role_name, r.is_owner_role,
       ur.expires_at, ur.created_at AS granted_at, ur.granted_reason
FROM   user_roles ur
JOIN   roles r ON r.id = ur.role_id
WHERE  ur.user_id  = $1::uuid
  AND  r.is_active = TRUE
  AND  (ur.expires_at IS NULL OR ur.expires_at > NOW())
`

type GetUserRoleRow struct {
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	RoleID        pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleName      string             `db:"role_name" json:"role_name"`
	IsOwnerRole   bool               `db:"is_owner_role" json:"is_owner_role"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	GrantedAt     time.Time          `db:"granted_at" json:"granted_at"`
	GrantedReason string             `db:"granted_reason" json:"granted_reason"`
}

// ── User role ───────────────────────────────────────────────────────────────
// Returns nil (no rows) when the user has no active role assignment.
func (q *Queries) GetUserRole(ctx context.Context, userID pgtype.UUID) (GetUserRoleRow, error) {
	row := q.db.QueryRow(ctx, GetUserRole, userID)
	var i GetUserRoleRow
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.RoleName,
		&i.IsOwnerRole,
		&i.ExpiresAt,
		&i.GrantedAt,
		&i.GrantedReason,
	)
	return i, err
}

const GrantUserPermission = `-- name: GrantUserPermission :one
INSERT INTO user_permissions (
    user_id, permission_id, granted_by, granted_reason,
    expires_at, scope, conditions
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5::timestamptz,
    $6,
    COALESCE($7::jsonb, '{}')
)
RETURNING id, user_id, permission_id, scope, expires_at, created_at
`

type GrantUserPermissionParams struct {
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	PermissionID  pgtype.UUID        `db:"permission_id" json:"permission_id"`
	GrantedBy     pgtype.UUID        `db:"granted_by" json:"granted_by"`
	GrantedReason string             `db:"granted_reason" json:"granted_reason"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Scope         PermissionScope    `db:"scope" json:"scope"`
	Conditions    []byte             `db:"conditions" json:"conditions"`
}

type GrantUserPermissionRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	PermissionID pgtype.UUID        `db:"permission_id" json:"permission_id"`
	Scope        PermissionScope    `db:"scope" json:"scope"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time          `db:"created_at" json:"created_at"`
}

// Privilege escalation is blocked by fn_prevent_privilege_escalation trigger.
// uq_up_one_active_grant_per_user_perm is a full UNIQUE index on (user_id, permission_id),
// so re-granting the same permission requires revoking the previous grant first.
// The service layer should call RevokeUserPermission before this when re-granting.
//
// On 23505 (unique_violation) on uq_up_one_active_grant_per_user_perm:
// service maps → ErrPermissionAlreadyGranted → 409.
func (q *Queries) GrantUserPermission(ctx context.Context, arg GrantUserPermissionParams) (GrantUserPermissionRow, error) {
	row := q.db.QueryRow(ctx, GrantUserPermission,
		arg.UserID,
		arg.PermissionID,
		arg.GrantedBy,
		arg.GrantedReason,
		arg.ExpiresAt,
		arg.Scope,
		arg.Conditions,
	)
	var i GrantUserPermissionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PermissionID,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const LockUser = `-- name: LockUser :exec


UPDATE user_secrets
SET admin_locked        = TRUE,
    admin_locked_by     = $1::uuid,
    admin_locked_reason = $2,
    admin_locked_at     = NOW(),
    updated_at          = NOW()
WHERE user_id = $3::uuid
`

type LockUserParams struct {
	LockedBy pgtype.UUID `db:"locked_by" json:"locked_by"`
	Reason   pgtype.Text `db:"reason" json:"reason"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

// ── User lock ───────────────────────────────────────────────────────────────
// NOTE: admin_locked, admin_locked_by, admin_locked_reason, admin_locked_at,
// is_locked, and login_locked_until are all in user_secrets, not users.
// Sets admin_locked = TRUE with actor, reason, and timestamp in user_secrets.
// chk_us_admin_lock_coherent: reason + at required when locked = TRUE.
// chk_us_no_self_lock: admin_locked_by must differ from user_id.
func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, LockUser, arg.LockedBy, arg.Reason, arg.UserID)
	return err
}

const RemoveRolePermission = `-- name: RemoveRolePermission :execrows
DELETE FROM role_permissions
WHERE role_id = $1::uuid AND permission_id = $2::uuid
`

type RemoveRolePermissionParams struct {
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
}

func (q *Queries) RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, RemoveRolePermission, arg.RoleID, arg.PermissionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const RemoveUserRole = `-- name: RemoveUserRole :execrows
DELETE FROM user_roles WHERE user_id = $1::uuid
`

// Hard-deletes a user's role assignment. Returns rows affected (0 = no assignment found).
// fn_prevent_orphaned_owner fires as a DB backstop before DELETE.
func (q *Queries) RemoveUserRole(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, RemoveUserRole, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const RevokeUserPermission = `-- name: RevokeUserPermission :execrows
DELETE FROM user_permissions WHERE id = $1::uuid AND user_id = $2::uuid
`

type RevokeUserPermissionParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

// Hard-deletes by surrogate id scoped to user_id (prevents cross-user deletion).
func (q *Queries) RevokeUserPermission(ctx context.Context, arg RevokeUserPermissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, RevokeUserPermission, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const UnlockUser = `-- name: UnlockUser :exec
UPDATE user_secrets
SET admin_locked        = FALSE,
    admin_locked_by     = NULL,
    admin_locked_reason = NULL,
    admin_locked_at     = NULL,
    updated_at          = NOW()
WHERE user_id = $1::uuid
`

// Clears admin_locked and all metadata fields in user_secrets.
// chk_us_admin_lock_coherent requires all three metadata fields to be NULL
// when admin_locked = FALSE, so all four must be cleared atomically.
func (q *Queries) UnlockUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, UnlockUser, userID)
	return err
}

const UpdateRole = `-- name: UpdateRole :one
UPDATE roles
SET name        = COALESCE($1,        name),
    description = COALESCE($2, description)
WHERE id             = $3::uuid
  AND is_system_role = FALSE
RETURNING id, name, description, is_system_role, is_owner_role, is_active, created_at, updated_at
`

type UpdateRoleParams struct {
	Name        pgtype.Text `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	ID          pgtype.UUID `db:"id" json:"id"`
}

// WHERE is_system_role = FALSE prevents renaming system roles at the DB level.
// Zero rows affected → service returns ErrSystemRoleImmutable → 409.
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, UpdateRole, arg.Name, arg.Description, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.IsOwnerRole,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
