//go:build integration_test

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac_test.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateActiveUnverifiedUserForTest = `-- name: CreateActiveUnverifiedUserForTest :one
/*
  Test-support queries for the rbac package.

  !! FOR TEST USE ONLY !!
  These queries expose mutations that production code must never perform directly.
  They are generated into the db package alongside production queries and restricted
  to integration test binaries via the //go:build integration_test tag added by the
  sqlc-generate make target.
*/


WITH new_user AS (
    INSERT INTO users (email, display_name, is_active, email_verified)
    VALUES ($1, 'Test User', TRUE, FALSE)
    RETURNING id
),
secrets AS (
    INSERT INTO user_secrets (user_id, password_hash)
    SELECT id, $2 FROM new_user
)
SELECT id FROM new_user
`

type CreateActiveUnverifiedUserForTestParams struct {
	Email        pgtype.Text `db:"email" json:"email"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

// Inserts an active but email-unverified user, bypassing the OTP flow.
// Sets is_active = TRUE and email_verified = FALSE directly.
// Used by T-R21 to verify that bootstrap rejects users who have not yet
// confirmed their email address.
func (q *Queries) CreateActiveUnverifiedUserForTest(ctx context.Context, arg CreateActiveUnverifiedUserForTestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, CreateActiveUnverifiedUserForTest, arg.Email, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const CreatePermissionGroupForTest = `-- name: CreatePermissionGroupForTest :one
INSERT INTO permission_groups (name, display_order)
VALUES ($1, 999)
RETURNING id
`

// Inserts a bare permission group with no members, returning its id.
// Used by TestGetPermissionGroups_ZeroMemberGroup to verify that a group
// with no permission_group_members rows returns Members = [] (not nil).
func (q *Queries) CreatePermissionGroupForTest(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, CreatePermissionGroupForTest, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const CreateVerifiedActiveUserForTest = `-- name: CreateVerifiedActiveUserForTest :one
WITH new_user AS (
    INSERT INTO users (email, display_name, is_active, email_verified)
    VALUES ($1, 'Test User', TRUE, TRUE)
    RETURNING id
),
secrets AS (
    INSERT INTO user_secrets (user_id, password_hash)
    SELECT id, $2 FROM new_user
)
SELECT id FROM new_user
`

type CreateVerifiedActiveUserForTestParams struct {
	Email        pgtype.Text `db:"email" json:"email"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

// Inserts a fully active and email-verified user, bypassing the OTP and registration flow.
// Returns the new user's UUID.
// Used by owner integration tests that need a ready-to-use user for AssignOwnerTx
// and ownership-transfer operations.
func (q *Queries) CreateVerifiedActiveUserForTest(ctx context.Context, arg CreateVerifiedActiveUserForTestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, CreateVerifiedActiveUserForTest, arg.Email, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const DeactivateAllPermissionsForTest = `-- name: DeactivateAllPermissionsForTest :exec
UPDATE permissions SET is_active = FALSE
`

// Soft-deactivates every permission row inside the current transaction.
// Used by TestGetPermissions_Empty to verify that GetPermissions returns
// an allocated empty slice (not nil) when no active rows exist.
func (q *Queries) DeactivateAllPermissionsForTest(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeactivateAllPermissionsForTest)
	return err
}

const GetAuditLogEventCountForTest = `-- name: GetAuditLogEventCountForTest :one
SELECT COUNT(*)
FROM   auth_audit_log
WHERE  user_id    = $1::uuid
  AND  event_type = $2::text
`

type GetAuditLogEventCountForTestParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	EventType string      `db:"event_type" json:"event_type"`
}

// Returns the count of auth_audit_log entries matching the given user_id and event_type.
// Used by owner integration tests to verify that store methods write the expected
// audit entries.
func (q *Queries) GetAuditLogEventCountForTest(ctx context.Context, arg GetAuditLogEventCountForTestParams) (int64, error) {
	row := q.db.QueryRow(ctx, GetAuditLogEventCountForTest, arg.UserID, arg.EventType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetLatestRolePermissionAuditEntry = `-- name: GetLatestRolePermissionAuditEntry :one
SELECT changed_by, changed_at, change_type
FROM   role_permissions_audit
WHERE  role_id       = $1::uuid
  AND  permission_id = $2::uuid
  AND  change_type   = $3::audit_change_type_enum
ORDER  BY changed_at DESC
LIMIT  1
`

type GetLatestRolePermissionAuditEntryParams struct {
	RoleID       pgtype.UUID         `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID         `db:"permission_id" json:"permission_id"`
	ChangeType   AuditChangeTypeEnum `db:"change_type" json:"change_type"`
}

type GetLatestRolePermissionAuditEntryRow struct {
	ChangedBy  pgtype.UUID         `db:"changed_by" json:"changed_by"`
	ChangedAt  pgtype.Timestamptz  `db:"changed_at" json:"changed_at"`
	ChangeType AuditChangeTypeEnum `db:"change_type" json:"change_type"`
}

// Returns the most recent audit row for a given (role_id, permission_id, change_type).
// Used by integration tests to assert that the correct actor was recorded by
// fn_audit_role_permissions after a DELETE.
func (q *Queries) GetLatestRolePermissionAuditEntry(ctx context.Context, arg GetLatestRolePermissionAuditEntryParams) (GetLatestRolePermissionAuditEntryRow, error) {
	row := q.db.QueryRow(ctx, GetLatestRolePermissionAuditEntry, arg.RoleID, arg.PermissionID, arg.ChangeType)
	var i GetLatestRolePermissionAuditEntryRow
	err := row.Scan(&i.ChangedBy, &i.ChangedAt, &i.ChangeType)
	return i, err
}

const GetUserRoleNameForTest = `-- name: GetUserRoleNameForTest :one
SELECT r.name
FROM   user_roles ur
JOIN   roles r ON r.id = ur.role_id
WHERE  ur.user_id = $1::uuid
`

// Returns the role name currently assigned to the given user (active assignment only).
// Returns no-rows if the user has no role.
// Used by owner integration tests to verify that AssignOwnerTx and AcceptTransferTx
// set and clear the owner role on the correct users.
func (q *Queries) GetUserRoleNameForTest(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, GetUserRoleNameForTest, userID)
	var name string
	err := row.Scan(&name)
	return name, err
}
