// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const GetAccountsDueForPurge = `-- name: GetAccountsDueForPurge :many
/* ============================================================
   sql/queries/worker.sql
   Queries for background worker jobs.
   ============================================================ */



SELECT id
FROM users
WHERE deleted_at < NOW() - INTERVAL '30 days'
LIMIT 100
`

// ── Background purge worker ──
// Returns up to 100 user IDs whose grace period has expired.
// The worker processes these in a loop, purging each in its own transaction.
func (q *Queries) GetAccountsDueForPurge(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, GetAccountsDueForPurge)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const HardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users
WHERE id = $1::uuid
`

// Permanently deletes a user row. All child rows (refresh_tokens, user_sessions,
// one_time_tokens, user_identities, auth_audit_log, user_roles) are removed via
// CASCADE. Must be called AFTER InsertPurgeLog within the same transaction (D-14).
func (q *Queries) HardDeleteUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, HardDeleteUser, userID)
	return err
}

const InsertPurgeLog = `-- name: InsertPurgeLog :exec
INSERT INTO account_purge_log (user_id, metadata)
VALUES ($1::uuid, $2::jsonb)
`

type InsertPurgeLogParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Metadata []byte      `db:"metadata" json:"metadata"`
}

// Writes a permanent record of the purge before the user row is deleted (D-15).
// metadata is a JSONB blob — callers pass {"deleted_at": "<RFC3339>"} at minimum.
func (q *Queries) InsertPurgeLog(ctx context.Context, arg InsertPurgeLogParams) error {
	_, err := q.db.Exec(ctx, InsertPurgeLog, arg.UserID, arg.Metadata)
	return err
}
